In [1]:
!pip uninstall -y protobuf
!pip install protobuf==3.20.3

Found existing installation: protobuf 6.33.0
Uninstalling protobuf-6.33.0:
  Successfully uninstalled protobuf-6.33.0
Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-py2.py3-none-any.whl.metadata (720 bytes)
Downloading protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 4.1 MB/s eta 0:00:00a 0:00:01
Installing collected packages: protobuf
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.12.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
opentelemetry-proto 1.37.0 requires protobuf<7.0,>=5.0, but you have protobuf 3.20.3 which is incompatible.
onnx 1.18.0 requires protobuf>=4.25.1, but you have protobuf 3.20.3 which is incompatible.
a2a-sdk 0.3.10 requires protobuf>=5.29.5, but you have protobuf 3.20.3 which is incompatible.
ray 2.51.1 requires click!=8.3.0,>=7.0, but you have click 8.3.0 which is incompatible.
bigframes 2.12.0 requires rich<14,>=12.4.4, but you have rich 14.2.0 which is incompatible.
tensorflow-metadata 1.17.2 requires protobuf>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.3 which is incompatible.
pydrive2 1.21.3 requires cryptography<44, but you have cryptography 46.0.3 which is incompatible.
pydrive2 1.21.3 requires pyOpenSSL<=24.2.1,>=19.1.0, but you have pyopenssl 25.3.0 which is incompatible.
ydf 0.13.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 3.20.3 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 3.20.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.10.0 which is incompatible.
Successfully installed protobuf-3.20.3

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [3]:
%env TOKENIZERS_PARALLELISM=false

env: TOKENIZERS_PARALLELISM=false

In [4]:
import io
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
import re
import seaborn as sns
import tokenize
import torch
import transformers

from datasets import Dataset

from math import ceil

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import StratifiedShuffleSplit

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    EarlyStoppingCallback,
    TrainingArguments,
    Trainer,
    logging
)

from tqdm.auto import tqdm

2026-01-13 04:25:25.164232: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768278325.351080      47 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768278325.408656      47 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

(OBS) Code block added to delete the SQL status of the checkpoint (it has 7 GBs, so it ocuppies much space on the output). Add this code block at the beginning of the script, right after the imports.

In [5]:
path = "/kaggle/working/state.db"

if os.path.exists(path):
    os.remove(path)
    print("state.db deleted")
else:
    print("state.db not found")

state.db not found

In [6]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    macro_f1 = f1_score(labels, predictions, average="macro")
    accuracy = accuracy_score(labels, predictions)
    precision = precision_score(labels, predictions, average="weighted")
    recall = recall_score(labels, predictions, average="weighted")

    return {
        "macro_f1": macro_f1,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall
    }

In [7]:
MODEL_NAME = "microsoft/unixcoder-base"
MAX_LENGTH = 192

In [8]:
base_path = "/kaggle/input/sem-eval-2026-task-13-subtask-b/Task_B"

training_path = "/kaggle/input/sample/training_sample_set.parquet"
validation_path = "/kaggle/input/sample/validation_sample_set.parquet"
test_sample_path = base_path + "/test_sample.parquet"
test_full_path = base_path + "/test.parquet"

training_df = pd.read_parquet(training_path)
validation_df = pd.read_parquet(validation_path)
test_sample_df = pd.read_parquet(test_sample_path)
test_full_df = pd.read_parquet(test_full_path)

test_df = pd.merge(test_sample_df, test_full_df, on="code", how="inner")

In [9]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

The functions below preprocess code samples and erase the comments.

In [10]:
def is_escaped(result, i):
    count = 0
    i -= 1
    while i >= 0 and result[i] == '\\':
        count += 1
        i -= 1
    return count % 2 == 1

In [11]:
def strip_jcg_comments(code: str) -> str:
    result = list(code)
    i = 0
    n = len(code)

    in_single_line_comment = False
    in_multi_line_comment = False
    string_delimiter = None
    in_verbatim_string = False

    while i < n:
        c = code[i]
        next_c = code[i + 1] if i + 1 < n else ''

        if in_single_line_comment:
            if c != '\n':
                result[i] = ' '
            else:
                in_single_line_comment = False
            i += 1
            continue

        if in_multi_line_comment:
            if c == '*' and next_c == '/':
                result[i] = result[i + 1] = ' '
                in_multi_line_comment = False
                i += 2
            else:
                if c != '\n':
                    result[i] = ' '
                i += 1
            continue

        if string_delimiter is not None:
            if string_delimiter == '`':
                if c == '`':
                    string_delimiter = None
            elif string_delimiter == '"':
                if c == '"' and not is_escaped(code, i):
                    string_delimiter = None
            elif string_delimiter == "'":
                if c == "'" and not is_escaped(code, i):
                    string_delimiter = None
            i += 1
            continue

        if in_verbatim_string:
            if c == '"' and next_c == '"':
                i += 2
            else:
                if c == '"' and next_c != '"':
                    in_verbatim_string = False
                i += 1
            continue

        if c == '@' and next_c == '"':
            in_verbatim_string = True
            i += 2
            continue

        if c == "'" or c == '"' or c == '`':
            string_delimiter = c
            i += 1
            continue

        if c == '/' and next_c == '/':
            result[i] = result[i + 1] = ' '
            in_single_line_comment = True
            i += 2
            continue

        if c == '/' and next_c == '*':
            result[i] = result[i + 1] = ' '
            in_multi_line_comment = True
            i += 2
            continue

        i += 1

    return ''.join(result)

In [12]:
def strip_php_comments(code: str) -> str:
    result = list(code)
    i = 0
    n = len(code)

    in_single_line_comment = False
    in_multi_line_comment = False
    string_delimiter = None
    in_heredoc = False
    heredoc_id = None

    while i < n:
        c = code[i]
        next_c = code[i + 1] if i + 1 < n else ''

        if i == 0 or code[i - 1] == '\n':
            line_start = i
        else:
            line_start = None

        if in_heredoc:
            if line_start is not None:
                j = line_start
                k = 0
                while j < n and k < len(heredoc_id) and code[j] == heredoc_id[k]:
                    j += 1
                    k += 1
                if k == len(heredoc_id) and (j == n or code[j] in (';', '\n')):
                    in_heredoc = False
                    heredoc_id = None
            i += 1
            continue

        if in_single_line_comment:
            if c != '\n':
                result[i] = ' '
            else:
                in_single_line_comment = False
            i += 1
            continue

        if in_multi_line_comment:
            if c == '*' and next_c == '/':
                result[i] = result[i + 1] = ' '
                in_multi_line_comment = False
                i += 2
            else:
                if c != '\n':
                    result[i] = ' '
                i += 1
            continue

        if string_delimiter is not None:
            if c == string_delimiter and not is_escaped(code, i):
                string_delimiter = None
            i += 1
            continue

        if c == '<' and code[i:i+3] == '<<<':
            j = i + 3

            while j < n and code[j].isspace():
                j += 1

            if j < n and code[j] in ("'", '"'):
                quote = code[j]
                j += 1
                start = j
                while j < n and code[j] != quote:
                    j += 1
                heredoc_id = code[start:j]
                j += 1
            else:
                start = j
                while j < n and (code[j].isalnum() or code[j] == '_'):
                    j += 1
                heredoc_id = code[start:j]

            in_heredoc = True
            i = j
            continue


        if c == "'" or c == '"':
            string_delimiter = c
            i += 1
            continue

        if c == '/' and next_c == '/':
            result[i] = result[i + 1] = ' '
            in_single_line_comment = True
            i += 2
            continue

        if c == '#':
            result[i] = ' '
            in_single_line_comment = True
            i += 1
            continue

        if c == '/' and next_c == '*':
            result[i] = result[i + 1] = ' '
            in_multi_line_comment = True
            i += 2
            continue

        i += 1

    return ''.join(result)

In [13]:
def strip_python_comments(code: str) -> str:
    result = list(code)
    i = 0
    n = len(code)

    string_delimiter = None
    in_comment = False

    while i < n:
        c = code[i]

        if in_comment:
            if c != '\n':
                result[i] = ' '
            else:
                in_comment = False
            i += 1
            continue

        if string_delimiter is not None:
            if c == string_delimiter and not is_escaped(code, i):
                string_delimiter = None
            i += 1
            continue

        if c in ("'", '"'):
            string_delimiter = c
            i += 1
            continue

        if c == '#':
            result[i] = ' '
            in_comment = True
            i += 1
            continue

        i += 1

    return ''.join(result)

In [14]:
fallback_count = 0

def remove_python_docstrings(code: str) -> str:
    global fallback_count
    try:
        tokens = tokenize.generate_tokens(io.StringIO(code).readline)
        result = []
    
        scope_stack = [True]
    
        for tok in tokens:
            tok_type, tok_str, _, _, _ = tok
    
            if tok_type == tokenize.INDENT:
                scope_stack.append(True)
            elif tok_type == tokenize.DEDENT:
                scope_stack.pop()
            elif tok_type == tokenize.STRING and scope_stack[-1]:
                scope_stack[-1] = False
                continue
            elif tok_type not in (tokenize.NL, tokenize.NEWLINE):
                scope_stack[-1] = False
    
            result.append(tok)
    
        return tokenize.untokenize(result)

    except (IndentationError, SyntaxError, tokenize.TokenError):
        fallback_count += 1
        return code

In [15]:
def strip_python_comments_and_docstrings(code: str) -> str:
    code = strip_python_comments(code)
    code = remove_python_docstrings(code)
    return code

In [16]:
def normalize_whitespace(code: str) -> str:
    lines = code.splitlines()
    normalized = []

    for line in lines:
        stripped = line.rstrip()

        if stripped:
            m = re.match(r'^(\s*)(.*)$', stripped)
            indent, content = m.groups()
            content = re.sub(r' {2,}', ' ', content)
            normalized.append(indent + content)

    return '\n'.join(normalized)

In [17]:
def remove_jcg_comments(code: str) -> str:
    return normalize_whitespace(strip_jcg_comments(code))


def remove_php_comments(code: str) -> str:
    return normalize_whitespace(strip_php_comments(code))


def remove_python_comments(code: str) -> str:
    return normalize_whitespace(strip_python_comments_and_docstrings(code))

In [18]:
def clean_code(code: str, language: str) -> str:
    lang = language.lower() if isinstance(language, str) else ""
    if lang == "python":
        return remove_python_comments(code)
    elif lang == "php":
        return remove_php_comments(code)
    else:
        return remove_jcg_comments(code)

In [19]:
def preprocess_function(examples: pd.DataFrame):
    cleaned_code = [
        clean_code(code, lang)
        for code, lang in zip(examples["code"], examples["language"])
    ]

    examples["code"] = cleaned_code

    tokenized = tokenizer(
        examples["code"],
        truncation=True,
        max_length=MAX_LENGTH
    )

    return tokenized

In [20]:
def binary_label(generator):
    return 0 if generator == "Human" else 1

for df in (training_df, validation_df, test_df):
    for col in ["label", "labels", "binary_label"]:
        if col in df.columns:
            df.drop(columns=[col], inplace=True)

    df["binary_label"] = df["generator"].apply(binary_label).astype("int64")

(OBS) It is good practice to set the format to torch after you tokenize the datasets. Add the .set_format("torch") instructions right after you tokenized the datasets.

In [21]:
columns_to_remove = ["binary_label", "code", "generator", "language", "__index_level_0__"]

training_dataset = Dataset.from_pandas(training_df, preserve_index=False)
validation_dataset = Dataset.from_pandas(validation_df, preserve_index=False)
test_dataset = Dataset.from_pandas(test_df, preserve_index=False)

training_dataset = training_dataset.add_column(
    "labels",
    [int(x) for x in training_df["binary_label"].tolist()]
)
validation_dataset = validation_dataset.add_column(
    "labels",
    [int(x) for x in validation_df["binary_label"].tolist()]
)
test_dataset = test_dataset.add_column(
    "labels",
    [int(x) for x in test_df["binary_label"].tolist()]
)

training_tokenized_set = training_dataset.map(preprocess_function, batched=True)
validation_tokenized_set = validation_dataset.map(preprocess_function, batched=True)
test_tokenized_set = test_dataset.map(preprocess_function, batched=True)

training_tokenized_set = training_tokenized_set.remove_columns(
    [c for c in columns_to_remove if c in training_tokenized_set.column_names]
)
validation_tokenized_set = validation_tokenized_set.remove_columns(
    [c for c in columns_to_remove if c in validation_tokenized_set.column_names]
)
test_tokenized_set = test_tokenized_set.remove_columns(
    [c for c in columns_to_remove if c in test_tokenized_set.column_names]
)

training_tokenized_set.set_format("torch")
validation_tokenized_set.set_format("torch")
test_tokenized_set.set_format("torch")

Map:   0%|          | 0/300000 [00:00<?, ? examples/s]

Map:   0%|          | 0/60000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [22]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print("\nRunning on device:", device)
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

Running on device: cuda
1
Tesla T4

In [23]:
print("Docstring fallback count:", fallback_count)

Docstring fallback count: 872

In [24]:
logging.set_verbosity_info()

In [25]:
class TrainingProgressCallback(transformers.TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        if state.is_local_process_zero:
            tqdm.write(f"Step {state.global_step}/{state.max_steps}")

In [26]:
binary_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

binary_model.to(device)

config.json:   0%|          | 0.00/691 [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--microsoft--unixcoder-base/snapshots/5604afdc964f6c53782a6813140ade5216b99006/config.json
Model config RobertaConfig {
  "architectures": [
    "RobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 1026,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 10,
  "use_cache": true,
  "vocab_size": 51416
}

pytorch_model.bin:   0%|          | 0.00/504M [00:00<?, ?B/s]

loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--microsoft--unixcoder-base/snapshots/5604afdc964f6c53782a6813140ade5216b99006/pytorch_model.bin
Attempting to create safetensors variant
Some weights of the model checkpoint at microsoft/unixcoder-base were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at microsoft/unixcoder-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Safetensors PR exists

model.safetensors:   0%|          | 0.00/504M [00:00<?, ?B/s]

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(51416, 768, padding_idx=1)
      (position_embeddings): Embedding(1026, 768, padding_idx=1)
      (token_type_embeddings): Embedding(10, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=2, bias=True)
  )
)

In [27]:
binary_args = TrainingArguments(
    output_dir="/kaggle/working/checkpoints_a",
    seed=42,
    learning_rate=3e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    weight_decay=0.01,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=64,
    gradient_accumulation_steps=2,
    num_train_epochs=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    fp16=True,
    disable_tqdm=False,
    ddp_find_unused_parameters=False,
    dataloader_num_workers=0,
    no_cuda=False,
    report_to=[]
)

PyTorch: setting up devices

In [28]:
binary_trainer = Trainer(
    model=binary_model,
    args=binary_args,
    train_dataset=training_tokenized_set,
    eval_dataset=validation_tokenized_set,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(
                   early_stopping_patience=1,
                   early_stopping_threshold=0.001
               ),
               TrainingProgressCallback()]
)

Using auto half precision backend

In [29]:
binary_trainer.train()

***** Running training *****
  Num examples = 300,000
  Num Epochs = 3
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 2
  Total optimization steps = 14,064
  Number of trainable parameters = 125,931,266

Step 1/14064

Step 2/14064
Step 3/14064
Step 4/14064
Step 5/14064
Step 6/14064
Step 7/14064
Step 8/14064
Step 9/14064
Step 10/14064
Step 11/14064
Step 12/14064
Step 13/14064
Step 14/14064
Step 15/14064
Step 16/14064
Step 17/14064
Step 18/14064
Step 19/14064
Step 20/14064
Step 21/14064
Step 22/14064
Step 23/14064
Step 24/14064
Step 25/14064
Step 26/14064
Step 27/14064
Step 28/14064
Step 29/14064
Step 30/14064
Step 31/14064
Step 32/14064
Step 33/14064
Step 34/14064
Step 35/14064
Step 36/14064
Step 37/14064
Step 38/14064
Step 39/14064
Step 40/14064
Step 41/14064
Step 42/14064
Step 43/14064
Step 44/14064
Step 45/14064
Step 46/14064
Step 47/14064
Step 48/14064
Step 49/14064
Step 50/14064
Step 51/14064
Step 52/14064
Step 53/14064
Step 54/14064
Step 55/14064
Step 56/14064
Step 57/14064
Step 58/14064
Step 59/14064
Step 60/14064
Step 61/14064
Step 62/14064
Step 63/14064
Step 64/14064
Step 65/14064
Step 66/14064
Step 67/14064
Step 68/14064
Step 69/14064
Step 70/14064
Step 71/14064
Step 72/14064
Step 73/14064
Step 74/14064
Step 75/14064
Step 76/14064
Step 77/14064
Step 78/14064
Step 79/14064
Step 80/14064
Step 81/14064
Step 82/14064
Step 83/14064
Step 84/14064
Step 85/14064
Step 86/14064
Step 87/14064
Step 88/14064
Step 89/14064
Step 90/14064
Step 91/14064
Step 92/14064
Step 93/14064
Step 94/14064
Step 95/14064
Step 96/14064
Step 97/14064
Step 98/14064
Step 99/14064
Step 100/14064
Step 101/14064
Step 102/14064
Step 103/14064
Step 104/14064
Step 105/14064
Step 106/14064
Step 107/14064
Step 108/14064
Step 109/14064
Step 110/14064
Step 111/14064
Step 112/14064
Step 113/14064
Step 114/14064
Step 115/14064
Step 116/14064
Step 117/14064
Step 118/14064
Step 119/14064
Step 120/14064
Step 121/14064
Step 122/14064
Step 123/14064
Step 124/14064
Step 125/14064
Step 126/14064
Step 127/14064
Step 128/14064
Step 129/14064
Step 130/14064
Step 131/14064
Step 132/14064
Step 133/14064
Step 134/14064
Step 135/14064
Step 136/14064
Step 137/14064
Step 138/14064
Step 139/14064
Step 140/14064
Step 141/14064
Step 142/14064
Step 143/14064
Step 144/14064
Step 145/14064
Step 146/14064
Step 147/14064
Step 148/14064
Step 149/14064
Step 150/14064
Step 151/14064
Step 152/14064
Step 153/14064
Step 154/14064
Step 155/14064
Step 156/14064
Step 157/14064
Step 158/14064
Step 159/14064
Step 160/14064
Step 161/14064
Step 162/14064
Step 163/14064
Step 164/14064
Step 165/14064
Step 166/14064
Step 167/14064
Step 168/14064
Step 169/14064
Step 170/14064
Step 171/14064
Step 172/14064
Step 173/14064
Step 174/14064
Step 175/14064
Step 176/14064
Step 177/14064
Step 178/14064
Step 179/14064
Step 180/14064
Step 181/14064
Step 182/14064
Step 183/14064
Step 184/14064
Step 185/14064
Step 186/14064
Step 187/14064
Step 188/14064
Step 189/14064
Step 190/14064
Step 191/14064
Step 192/14064
Step 193/14064
Step 194/14064
Step 195/14064
Step 196/14064
Step 197/14064
Step 198/14064
Step 199/14064
Step 200/14064
Step 201/14064
Step 202/14064
Step 203/14064
Step 204/14064
Step 205/14064
Step 206/14064
Step 207/14064
Step 208/14064
Step 209/14064
Step 210/14064
Step 211/14064
Step 212/14064
Step 213/14064
Step 214/14064
Step 215/14064
Step 216/14064
Step 217/14064
Step 218/14064
Step 219/14064
Step 220/14064
Step 221/14064
Step 222/14064
Step 223/14064
Step 224/14064
Step 225/14064
Step 226/14064
Step 227/14064
Step 228/14064
Step 229/14064
Step 230/14064
Step 231/14064
Step 232/14064
Step 233/14064
Step 234/14064
Step 235/14064
Step 236/14064
Step 237/14064
Step 238/14064
Step 239/14064
Step 240/14064
Step 241/14064
Step 242/14064
Step 243/14064
Step 244/14064
Step 245/14064
Step 246/14064
Step 247/14064
Step 248/14064
Step 249/14064
Step 250/14064
Step 251/14064
Step 252/14064
Step 253/14064
Step 254/14064
Step 255/14064
Step 256/14064
Step 257/14064
Step 258/14064
Step 259/14064
Step 260/14064
Step 261/14064
Step 262/14064
Step 263/14064
Step 264/14064
Step 265/14064
Step 266/14064
Step 267/14064
Step 268/14064
Step 269/14064
Step 270/14064
Step 271/14064
Step 272/14064
Step 273/14064
Step 274/14064
Step 275/14064
Step 276/14064
Step 277/14064
Step 278/14064
Step 279/14064
Step 280/14064
Step 281/14064
Step 282/14064
Step 283/14064
Step 284/14064
Step 285/14064
Step 286/14064
Step 287/14064
Step 288/14064
Step 289/14064
Step 290/14064
Step 291/14064
Step 292/14064
Step 293/14064
Step 294/14064
Step 295/14064
Step 296/14064
Step 297/14064
Step 298/14064
Step 299/14064
Step 300/14064
Step 301/14064
Step 302/14064
Step 303/14064
Step 304/14064
Step 305/14064
Step 306/14064
Step 307/14064
Step 308/14064
Step 309/14064
Step 310/14064
Step 311/14064
Step 312/14064
Step 313/14064
Step 314/14064
Step 315/14064
Step 316/14064
Step 317/14064
Step 318/14064
Step 319/14064
Step 320/14064
Step 321/14064
Step 322/14064
Step 323/14064
Step 324/14064
Step 325/14064
Step 326/14064
Step 327/14064
Step 328/14064
Step 329/14064
Step 330/14064
Step 331/14064
Step 332/14064
Step 333/14064
Step 334/14064
Step 335/14064
Step 336/14064
Step 337/14064
Step 338/14064
Step 339/14064
Step 340/14064
Step 341/14064
Step 342/14064
Step 343/14064
Step 344/14064
Step 345/14064
Step 346/14064
Step 347/14064
Step 348/14064
Step 349/14064
Step 350/14064
Step 351/14064
Step 352/14064
Step 353/14064
Step 354/14064
Step 355/14064
Step 356/14064
Step 357/14064
Step 358/14064
Step 359/14064
Step 360/14064
Step 361/14064
Step 362/14064
Step 363/14064
Step 364/14064
Step 365/14064
Step 366/14064
Step 367/14064
Step 368/14064
Step 369/14064
Step 370/14064
Step 371/14064
Step 372/14064
Step 373/14064
Step 374/14064
Step 375/14064
Step 376/14064
Step 377/14064
Step 378/14064
Step 379/14064
Step 380/14064
Step 381/14064
Step 382/14064
Step 383/14064
Step 384/14064
Step 385/14064
Step 386/14064
Step 387/14064
Step 388/14064
Step 389/14064
Step 390/14064
Step 391/14064
Step 392/14064
Step 393/14064
Step 394/14064
Step 395/14064
Step 396/14064
Step 397/14064
Step 398/14064
Step 399/14064
Step 400/14064
Step 401/14064
Step 402/14064
Step 403/14064
Step 404/14064
Step 405/14064
Step 406/14064
Step 407/14064
Step 408/14064
Step 409/14064
Step 410/14064
Step 411/14064
Step 412/14064
Step 413/14064
Step 414/14064
Step 415/14064
Step 416/14064
Step 417/14064
Step 418/14064
Step 419/14064
Step 420/14064
Step 421/14064
Step 422/14064
Step 423/14064
Step 424/14064
Step 425/14064
Step 426/14064
Step 427/14064
Step 428/14064
Step 429/14064
Step 430/14064
Step 431/14064
Step 432/14064
Step 433/14064
Step 434/14064
Step 435/14064
Step 436/14064
Step 437/14064
Step 438/14064
Step 439/14064
Step 440/14064
Step 441/14064
Step 442/14064
Step 443/14064
Step 444/14064
Step 445/14064
Step 446/14064
Step 447/14064
Step 448/14064
Step 449/14064
Step 450/14064
Step 451/14064
Step 452/14064
Step 453/14064
Step 454/14064
Step 455/14064
Step 456/14064
Step 457/14064
Step 458/14064
Step 459/14064
Step 460/14064
Step 461/14064
Step 462/14064
Step 463/14064
Step 464/14064
Step 465/14064
Step 466/14064
Step 467/14064
Step 468/14064
Step 469/14064
Step 470/14064
Step 471/14064
Step 472/14064
Step 473/14064
Step 474/14064
Step 475/14064
Step 476/14064
Step 477/14064
Step 478/14064
Step 479/14064
Step 480/14064
Step 481/14064
Step 482/14064
Step 483/14064
Step 484/14064
Step 485/14064
Step 486/14064
Step 487/14064
Step 488/14064
Step 489/14064
Step 490/14064
Step 491/14064
Step 492/14064
Step 493/14064
Step 494/14064
Step 495/14064
Step 496/14064
Step 497/14064
Step 498/14064
Step 499/14064
Step 500/14064
Step 501/14064
Step 502/14064
Step 503/14064
Step 504/14064
Step 505/14064
Step 506/14064
Step 507/14064
Step 508/14064
Step 509/14064
Step 510/14064
Step 511/14064
Step 512/14064
Step 513/14064
Step 514/14064
Step 515/14064
Step 516/14064
Step 517/14064
Step 518/14064
Step 519/14064
Step 520/14064
Step 521/14064
Step 522/14064
Step 523/14064
Step 524/14064
Step 525/14064
Step 526/14064
Step 527/14064
Step 528/14064
Step 529/14064
Step 530/14064
Step 531/14064
Step 532/14064
Step 533/14064
Step 534/14064
Step 535/14064
Step 536/14064
Step 537/14064
Step 538/14064
Step 539/14064
Step 540/14064
Step 541/14064
Step 542/14064
Step 543/14064
Step 544/14064
Step 545/14064
Step 546/14064
Step 547/14064
Step 548/14064
Step 549/14064
Step 550/14064
Step 551/14064
Step 552/14064
Step 553/14064
Step 554/14064
Step 555/14064
Step 556/14064
Step 557/14064
Step 558/14064
Step 559/14064
Step 560/14064
Step 561/14064
Step 562/14064
Step 563/14064
Step 564/14064
Step 565/14064
Step 566/14064
Step 567/14064
Step 568/14064
Step 569/14064
Step 570/14064
Step 571/14064
Step 572/14064
Step 573/14064
Step 574/14064
Step 575/14064
Step 576/14064
Step 577/14064
Step 578/14064
Step 579/14064
Step 580/14064
Step 581/14064
Step 582/14064
Step 583/14064
Step 584/14064
Step 585/14064
Step 586/14064
Step 587/14064
Step 588/14064
Step 589/14064
Step 590/14064
Step 591/14064
Step 592/14064
Step 593/14064
Step 594/14064
Step 595/14064
Step 596/14064
Step 597/14064
Step 598/14064
Step 599/14064
Step 600/14064
Step 601/14064
Step 602/14064
Step 603/14064
Step 604/14064
Step 605/14064
Step 606/14064
Step 607/14064
Step 608/14064
Step 609/14064
Step 610/14064
Step 611/14064
Step 612/14064
Step 613/14064
Step 614/14064
Step 615/14064
Step 616/14064
Step 617/14064
Step 618/14064
Step 619/14064
Step 620/14064
Step 621/14064
Step 622/14064
Step 623/14064
Step 624/14064
Step 625/14064
Step 626/14064
Step 627/14064
Step 628/14064
Step 629/14064
Step 630/14064
Step 631/14064
Step 632/14064
Step 633/14064
Step 634/14064
Step 635/14064
Step 636/14064
Step 637/14064
Step 638/14064
Step 639/14064
Step 640/14064
Step 641/14064
Step 642/14064
Step 643/14064
Step 644/14064
Step 645/14064
Step 646/14064
Step 647/14064
Step 648/14064
Step 649/14064
Step 650/14064
Step 651/14064
Step 652/14064
Step 653/14064
Step 654/14064
Step 655/14064
Step 656/14064
Step 657/14064
Step 658/14064
Step 659/14064
Step 660/14064
Step 661/14064
Step 662/14064
Step 663/14064
Step 664/14064
Step 665/14064
Step 666/14064
Step 667/14064
Step 668/14064
Step 669/14064
Step 670/14064
Step 671/14064
Step 672/14064
Step 673/14064
Step 674/14064
Step 675/14064
Step 676/14064
Step 677/14064
Step 678/14064
Step 679/14064
Step 680/14064
Step 681/14064
Step 682/14064
Step 683/14064
Step 684/14064
Step 685/14064
Step 686/14064
Step 687/14064
Step 688/14064
Step 689/14064
Step 690/14064
Step 691/14064
Step 692/14064
Step 693/14064
Step 694/14064
Step 695/14064
Step 696/14064
Step 697/14064
Step 698/14064
Step 699/14064
Step 700/14064
Step 701/14064
Step 702/14064
Step 703/14064
Step 704/14064
Step 705/14064
Step 706/14064
Step 707/14064
Step 708/14064
Step 709/14064
Step 710/14064
Step 711/14064
Step 712/14064
Step 713/14064
Step 714/14064
Step 715/14064
Step 716/14064
Step 717/14064
Step 718/14064
Step 719/14064
Step 720/14064
Step 721/14064
Step 722/14064
Step 723/14064
Step 724/14064
Step 725/14064
Step 726/14064
Step 727/14064
Step 728/14064
Step 729/14064
Step 730/14064
Step 731/14064
Step 732/14064
Step 733/14064
Step 734/14064
Step 735/14064
Step 736/14064
Step 737/14064
Step 738/14064
Step 739/14064
Step 740/14064
Step 741/14064
Step 742/14064
Step 743/14064
Step 744/14064
Step 745/14064
Step 746/14064
Step 747/14064
Step 748/14064
Step 749/14064
Step 750/14064
Step 751/14064
Step 752/14064
Step 753/14064
Step 754/14064
Step 755/14064
Step 756/14064
Step 757/14064
Step 758/14064
Step 759/14064
Step 760/14064
Step 761/14064
Step 762/14064
Step 763/14064
Step 764/14064
Step 765/14064
Step 766/14064
Step 767/14064
Step 768/14064
Step 769/14064
Step 770/14064
Step 771/14064
Step 772/14064
Step 773/14064
Step 774/14064
Step 775/14064
Step 776/14064
Step 777/14064
Step 778/14064
Step 779/14064
Step 780/14064
Step 781/14064
Step 782/14064
Step 783/14064
Step 784/14064
Step 785/14064
Step 786/14064
Step 787/14064
Step 788/14064
Step 789/14064
Step 790/14064
Step 791/14064
Step 792/14064
Step 793/14064
Step 794/14064
Step 795/14064
Step 796/14064
Step 797/14064
Step 798/14064
Step 799/14064
Step 800/14064
Step 801/14064
Step 802/14064
Step 803/14064
Step 804/14064
Step 805/14064
Step 806/14064
Step 807/14064
Step 808/14064
Step 809/14064
Step 810/14064
Step 811/14064
Step 812/14064
Step 813/14064
Step 814/14064
Step 815/14064
Step 816/14064
Step 817/14064
Step 818/14064
Step 819/14064
Step 820/14064
Step 821/14064
Step 822/14064
Step 823/14064
Step 824/14064
Step 825/14064
Step 826/14064
Step 827/14064
Step 828/14064
Step 829/14064
Step 830/14064
Step 831/14064
Step 832/14064
Step 833/14064
Step 834/14064
Step 835/14064
Step 836/14064
Step 837/14064
Step 838/14064
Step 839/14064
Step 840/14064
Step 841/14064
Step 842/14064
Step 843/14064
Step 844/14064
Step 845/14064
Step 846/14064
Step 847/14064
Step 848/14064
Step 849/14064
Step 850/14064
Step 851/14064
Step 852/14064
Step 853/14064
Step 854/14064
Step 855/14064
Step 856/14064
Step 857/14064
Step 858/14064
Step 859/14064
Step 860/14064
Step 861/14064
Step 862/14064
Step 863/14064
Step 864/14064
Step 865/14064
Step 866/14064
Step 867/14064
Step 868/14064
Step 869/14064
Step 870/14064
Step 871/14064
Step 872/14064
Step 873/14064
Step 874/14064
Step 875/14064
Step 876/14064
Step 877/14064
Step 878/14064
Step 879/14064
Step 880/14064
Step 881/14064
Step 882/14064
Step 883/14064
Step 884/14064
Step 885/14064
Step 886/14064
Step 887/14064
Step 888/14064
Step 889/14064
Step 890/14064
Step 891/14064
Step 892/14064
Step 893/14064
Step 894/14064
Step 895/14064
Step 896/14064
Step 897/14064
Step 898/14064
Step 899/14064
Step 900/14064
Step 901/14064
Step 902/14064
Step 903/14064
Step 904/14064
Step 905/14064
Step 906/14064
Step 907/14064
Step 908/14064
Step 909/14064
Step 910/14064
Step 911/14064
Step 912/14064
Step 913/14064
Step 914/14064
Step 915/14064
Step 916/14064
Step 917/14064
Step 918/14064
Step 919/14064
Step 920/14064
Step 921/14064
Step 922/14064
Step 923/14064
Step 924/14064
Step 925/14064
Step 926/14064
Step 927/14064
Step 928/14064
Step 929/14064
Step 930/14064
Step 931/14064
Step 932/14064
Step 933/14064
Step 934/14064
Step 935/14064
Step 936/14064
Step 937/14064
Step 938/14064
Step 939/14064
Step 940/14064
Step 941/14064
Step 942/14064
Step 943/14064
Step 944/14064
Step 945/14064
Step 946/14064
Step 947/14064
Step 948/14064
Step 949/14064
Step 950/14064
Step 951/14064
Step 952/14064
Step 953/14064
Step 954/14064
Step 955/14064
Step 956/14064
Step 957/14064
Step 958/14064
Step 959/14064
Step 960/14064
Step 961/14064
Step 962/14064
Step 963/14064
Step 964/14064
Step 965/14064
Step 966/14064
Step 967/14064
Step 968/14064
Step 969/14064
Step 970/14064
Step 971/14064
Step 972/14064
Step 973/14064
Step 974/14064
Step 975/14064
Step 976/14064
Step 977/14064
Step 978/14064
Step 979/14064
Step 980/14064
Step 981/14064
Step 982/14064
Step 983/14064
Step 984/14064
Step 985/14064
Step 986/14064
Step 987/14064
Step 988/14064
Step 989/14064
Step 990/14064
Step 991/14064
Step 992/14064
Step 993/14064
Step 994/14064
Step 995/14064
Step 996/14064
Step 997/14064
Step 998/14064
Step 999/14064
Step 1000/14064
Step 1001/14064
Step 1002/14064
Step 1003/14064
Step 1004/14064
Step 1005/14064
Step 1006/14064
Step 1007/14064
Step 1008/14064
Step 1009/14064
Step 1010/14064
Step 1011/14064
Step 1012/14064
Step 1013/14064
Step 1014/14064
Step 1015/14064
Step 1016/14064
Step 1017/14064
Step 1018/14064
Step 1019/14064
Step 1020/14064
Step 1021/14064
Step 1022/14064
Step 1023/14064
Step 1024/14064
Step 1025/14064
Step 1026/14064
Step 1027/14064
Step 1028/14064
Step 1029/14064
Step 1030/14064
Step 1031/14064
Step 1032/14064
Step 1033/14064
Step 1034/14064
Step 1035/14064
Step 1036/14064
Step 1037/14064
Step 1038/14064
Step 1039/14064
Step 1040/14064
Step 1041/14064
Step 1042/14064
Step 1043/14064
Step 1044/14064
Step 1045/14064
Step 1046/14064
Step 1047/14064
Step 1048/14064
Step 1049/14064
Step 1050/14064
Step 1051/14064
Step 1052/14064
Step 1053/14064
Step 1054/14064
Step 1055/14064
Step 1056/14064
Step 1057/14064
Step 1058/14064
Step 1059/14064
Step 1060/14064
Step 1061/14064
Step 1062/14064
Step 1063/14064
Step 1064/14064
Step 1065/14064
Step 1066/14064
Step 1067/14064
Step 1068/14064
Step 1069/14064
Step 1070/14064
Step 1071/14064
Step 1072/14064
Step 1073/14064
Step 1074/14064
Step 1075/14064
Step 1076/14064
Step 1077/14064
Step 1078/14064
Step 1079/14064
Step 1080/14064
Step 1081/14064
Step 1082/14064
Step 1083/14064
Step 1084/14064
Step 1085/14064
Step 1086/14064
Step 1087/14064
Step 1088/14064
Step 1089/14064
Step 1090/14064
Step 1091/14064
Step 1092/14064
Step 1093/14064
Step 1094/14064
Step 1095/14064
Step 1096/14064
Step 1097/14064
Step 1098/14064
Step 1099/14064
Step 1100/14064
Step 1101/14064
Step 1102/14064
Step 1103/14064
Step 1104/14064
Step 1105/14064
Step 1106/14064
Step 1107/14064
Step 1108/14064
Step 1109/14064
Step 1110/14064
Step 1111/14064
Step 1112/14064
Step 1113/14064
Step 1114/14064
Step 1115/14064
Step 1116/14064
Step 1117/14064
Step 1118/14064
Step 1119/14064
Step 1120/14064
Step 1121/14064
Step 1122/14064
Step 1123/14064
Step 1124/14064
Step 1125/14064
Step 1126/14064
Step 1127/14064
Step 1128/14064
Step 1129/14064
Step 1130/14064
Step 1131/14064
Step 1132/14064
Step 1133/14064
Step 1134/14064
Step 1135/14064
Step 1136/14064
Step 1137/14064
Step 1138/14064
Step 1139/14064
Step 1140/14064
Step 1141/14064
Step 1142/14064
Step 1143/14064
Step 1144/14064
Step 1145/14064
Step 1146/14064
Step 1147/14064
Step 1148/14064
Step 1149/14064
Step 1150/14064
Step 1151/14064
Step 1152/14064
Step 1153/14064
Step 1154/14064
Step 1155/14064
Step 1156/14064
Step 1157/14064
Step 1158/14064
Step 1159/14064
Step 1160/14064
Step 1161/14064
Step 1162/14064
Step 1163/14064
Step 1164/14064
Step 1165/14064
Step 1166/14064
Step 1167/14064
Step 1168/14064
Step 1169/14064
Step 1170/14064
Step 1171/14064
Step 1172/14064
Step 1173/14064
Step 1174/14064
Step 1175/14064
Step 1176/14064
Step 1177/14064
Step 1178/14064
Step 1179/14064
Step 1180/14064
Step 1181/14064
Step 1182/14064
Step 1183/14064
Step 1184/14064
Step 1185/14064
Step 1186/14064
Step 1187/14064
Step 1188/14064
Step 1189/14064
Step 1190/14064
Step 1191/14064
Step 1192/14064
Step 1193/14064
Step 1194/14064
Step 1195/14064
Step 1196/14064
Step 1197/14064
Step 1198/14064
Step 1199/14064
Step 1200/14064
Step 1201/14064
Step 1202/14064
Step 1203/14064
Step 1204/14064
Step 1205/14064
Step 1206/14064
Step 1207/14064
Step 1208/14064
Step 1209/14064
Step 1210/14064
Step 1211/14064
Step 1212/14064
Step 1213/14064
Step 1214/14064
Step 1215/14064
Step 1216/14064
Step 1217/14064
Step 1218/14064
Step 1219/14064
Step 1220/14064
Step 1221/14064
Step 1222/14064
Step 1223/14064
Step 1224/14064
Step 1225/14064
Step 1226/14064
Step 1227/14064
Step 1228/14064
Step 1229/14064
Step 1230/14064
Step 1231/14064
Step 1232/14064
Step 1233/14064
Step 1234/14064
Step 1235/14064
Step 1236/14064
Step 1237/14064
Step 1238/14064
Step 1239/14064
Step 1240/14064
Step 1241/14064
Step 1242/14064
Step 1243/14064
Step 1244/14064
Step 1245/14064
Step 1246/14064
Step 1247/14064
Step 1248/14064
Step 1249/14064
Step 1250/14064
Step 1251/14064
Step 1252/14064
Step 1253/14064
Step 1254/14064
Step 1255/14064
Step 1256/14064
Step 1257/14064
Step 1258/14064
Step 1259/14064
Step 1260/14064
Step 1261/14064
Step 1262/14064
Step 1263/14064
Step 1264/14064
Step 1265/14064
Step 1266/14064
Step 1267/14064
Step 1268/14064
Step 1269/14064
Step 1270/14064
Step 1271/14064
Step 1272/14064
Step 1273/14064
Step 1274/14064
Step 1275/14064
Step 1276/14064
Step 1277/14064
Step 1278/14064
Step 1279/14064
Step 1280/14064
Step 1281/14064
Step 1282/14064
Step 1283/14064
Step 1284/14064
Step 1285/14064
Step 1286/14064
Step 1287/14064
Step 1288/14064
Step 1289/14064
Step 1290/14064
Step 1291/14064
Step 1292/14064
Step 1293/14064
Step 1294/14064
Step 1295/14064
Step 1296/14064
Step 1297/14064
Step 1298/14064
Step 1299/14064
Step 1300/14064
Step 1301/14064
Step 1302/14064
Step 1303/14064
Step 1304/14064
Step 1305/14064
Step 1306/14064
Step 1307/14064
Step 1308/14064
Step 1309/14064
Step 1310/14064
Step 1311/14064
Step 1312/14064
Step 1313/14064
Step 1314/14064
Step 1315/14064
Step 1316/14064
Step 1317/14064
Step 1318/14064
Step 1319/14064
Step 1320/14064

***** Running Evaluation *****
  Num examples = 60000
  Batch size = 64
Saving model checkpoint to /kaggle/working/checkpoints_a/checkpoint-4688
Configuration saved in /kaggle/working/checkpoints_a/checkpoint-4688/config.json
Model weights saved in /kaggle/working/checkpoints_a/checkpoint-4688/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_a/checkpoint-4688/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_a/checkpoint-4688/special_tokens_map.json

Step 4689/14064
Step 4690/14064
Step 4691/14064
Step 4692/14064
Step 4693/14064
Step 4694/14064
Step 4695/14064
Step 4696/14064
Step 4697/14064
Step 4698/14064
Step 4699/14064
Step 4700/14064
Step 4701/14064
Step 4702/14064
Step 4703/14064
Step 4704/14064
Step 4705/14064
Step 4706/14064
Step 4707/14064
Step 4708/14064
Step 4709/14064
Step 4710/14064
Step 4711/14064
Step 4712/14064
Step 4713/14064
Step 4714/14064
Step 4715/14064
Step 4716/14064
Step 4717/14064
Step 4718/14064
Step 4719/14064
Step 4720/14064
Step 4721/14064
Step 4722/14064
Step 4723/14064
Step 4724/14064
Step 4725/14064
Step 4726/14064
Step 4727/14064
Step 4728/14064
Step 4729/14064
Step 4730/14064
Step 4731/14064
Step 4732/14064
Step 4733/14064
Step 4734/14064
Step 4735/14064
Step 4736/14064
Step 4737/14064
Step 4738/14064
Step 4739/14064
Step 4740/14064
Step 4741/14064
Step 4742/14064
Step 4743/14064
Step 4744/14064
Step 4745/14064
Step 4746/14064
Step 4747/14064
Step 4748/14064
Step 4749/14064
Step 4750/14064
Step 4751/14064
Step 4752/14064
Step 4753/14064
Step 4754/14064
Step 4755/14064
Step 4756/14064
Step 4757/14064
Step 4758/14064
Step 4759/14064
Step 4760/14064
Step 4761/14064
Step 4762/14064
Step 4763/14064
Step 4764/14064
Step 4765/14064
Step 4766/14064
Step 4767/14064
Step 4768/14064
Step 4769/14064
Step 4770/14064
Step 4771/14064
Step 4772/14064
Step 4773/14064
Step 4774/14064
Step 4775/14064
Step 4776/14064
Step 4777/14064
Step 4778/14064
Step 4779/14064
Step 4780/14064
Step 4781/14064
Step 4782/14064
Step 4783/14064
Step 4784/14064
Step 4785/14064
Step 4786/14064
Step 4787/14064
Step 4788/14064
Step 4789/14064
Step 4790/14064
Step 4791/14064
Step 4792/14064
Step 4793/14064
Step 4794/14064
Step 4795/14064
Step 4796/14064
Step 4797/14064
Step 4798/14064
Step 4799/14064
Step 4800/14064
Step 4801/14064
Step 4802/14064
Step 4803/14064
Step 4804/14064
Step 4805/14064
Step 4806/14064
Step 4807/14064
Step 4808/14064
Step 4809/14064
Step 4810/14064
Step 4811/14064
Step 4812/14064
Step 4813/14064
Step 4814/14064
Step 4815/14064
Step 4816/14064
Step 4817/14064
Step 4818/14064
Step 4819/14064
Step 4820/14064
Step 4821/14064
Step 4822/14064
Step 4823/14064
Step 4824/14064
Step 4825/14064
Step 4826/14064
Step 4827/14064
Step 4828/14064
Step 4829/14064
Step 4830/14064
Step 4831/14064
Step 4832/14064
Step 4833/14064
Step 4834/14064
Step 4835/14064
Step 4836/14064
Step 4837/14064
Step 4838/14064
Step 4839/14064
Step 4840/14064
Step 4841/14064
Step 4842/14064
Step 4843/14064
Step 4844/14064
Step 4845/14064
Step 4846/14064
Step 4847/14064
Step 4848/14064
Step 4849/14064
Step 4850/14064
Step 4851/14064
Step 4852/14064
Step 4853/14064
Step 4854/14064
Step 4855/14064
Step 4856/14064
Step 4857/14064
Step 4858/14064
Step 4859/14064
Step 4860/14064
Step 4861/14064
Step 4862/14064
Step 4863/14064
Step 4864/14064
Step 4865/14064
Step 4866/14064
Step 4867/14064
Step 4868/14064
Step 4869/14064
Step 4870/14064
Step 4871/14064
Step 4872/14064
Step 4873/14064
Step 4874/14064
Step 4875/14064
Step 4876/14064
Step 4877/14064
Step 4878/14064
Step 4879/14064
Step 4880/14064
Step 4881/14064
Step 4882/14064
Step 4883/14064
Step 4884/14064
Step 4885/14064
Step 4886/14064
Step 4887/14064
Step 4888/14064
Step 4889/14064
Step 4890/14064
Step 4891/14064
Step 4892/14064
Step 4893/14064
Step 4894/14064
Step 4895/14064
Step 4896/14064
Step 4897/14064
Step 4898/14064
Step 4899/14064
Step 4900/14064
Step 4901/14064
Step 4902/14064
Step 4903/14064
Step 4904/14064
Step 4905/14064
Step 4906/14064
Step 4907/14064
Step 4908/14064
Step 4909/14064
Step 4910/14064
Step 4911/14064
Step 4912/14064
Step 4913/14064
Step 4914/14064
Step 4915/14064
Step 4916/14064
Step 4917/14064
Step 4918/14064
Step 4919/14064
Step 4920/14064
Step 4921/14064
Step 4922/14064
Step 4923/14064
Step 4924/14064
Step 4925/14064
Step 4926/14064
Step 4927/14064
Step 4928/14064
Step 4929/14064
Step 4930/14064
Step 4931/14064
Step 4932/14064
Step 4933/14064
Step 4934/14064
Step 4935/14064
Step 4936/14064
Step 4937/14064
Step 4938/14064
Step 4939/14064
Step 4940/14064
Step 4941/14064
Step 4942/14064
Step 4943/14064
Step 4944/14064
Step 4945/14064
Step 4946/14064
Step 4947/14064
Step 4948/14064
Step 4949/14064
Step 4950/14064
Step 4951/14064
Step 4952/14064
Step 4953/14064
Step 4954/14064
Step 4955/14064
Step 4956/14064
Step 4957/14064
Step 4958/14064
Step 4959/14064
Step 4960/14064
Step 4961/14064
Step 4962/14064
Step 4963/14064
Step 4964/14064
Step 4965/14064
Step 4966/14064
Step 4967/14064
Step 4968/14064
Step 4969/14064
Step 4970/14064
Step 4971/14064
Step 4972/14064
Step 4973/14064
Step 4974/14064
Step 4975/14064
Step 4976/14064
Step 4977/14064
Step 4978/14064
Step 4979/14064
Step 4980/14064
Step 4981/14064
Step 4982/14064
Step 4983/14064
Step 4984/14064
Step 4985/14064
Step 4986/14064
Step 4987/14064
Step 4988/14064
Step 4989/14064
Step 4990/14064
Step 4991/14064
Step 4992/14064
Step 4993/14064
Step 4994/14064
Step 4995/14064
Step 4996/14064
Step 4997/14064
Step 4998/14064
Step 4999/14064
Step 5000/14064
Step 5001/14064
Step 5002/14064
Step 5003/14064
Step 5004/14064
Step 5005/14064
Step 5006/14064
Step 5007/14064
Step 5008/14064
Step 5009/14064
Step 5010/14064
Step 5011/14064
Step 5012/14064
Step 5013/14064
Step 5014/14064
Step 5015/14064
Step 5016/14064
Step 5017/14064
Step 5018/14064
Step 5019/14064
Step 5020/14064
Step 5021/14064
Step 5022/14064
Step 5023/14064
Step 5024/14064
Step 5025/14064
Step 5026/14064
Step 5027/14064
Step 5028/14064
Step 5029/14064
Step 5030/14064
Step 5031/14064
Step 5032/14064
Step 5033/14064
Step 5034/14064
Step 5035/14064
Step 5036/14064
Step 5037/14064
Step 5038/14064
Step 5039/14064
Step 5040/14064
Step 5041/14064
Step 5042/14064
Step 5043/14064
Step 5044/14064
Step 5045/14064
Step 5046/14064
Step 5047/14064
Step 5048/14064
Step 5049/14064
Step 5050/14064
Step 5051/14064
Step 5052/14064
Step 5053/14064
Step 5054/14064
Step 5055/14064
Step 5056/14064
Step 5057/14064
Step 5058/14064
Step 5059/14064
Step 5060/14064
Step 5061/14064
Step 5062/14064
Step 5063/14064
Step 5064/14064
Step 5065/14064
Step 5066/14064
Step 5067/14064
Step 5068/14064
Step 5069/14064
Step 5070/14064
Step 5071/14064
Step 5072/14064
Step 5073/14064
Step 5074/14064
Step 5075/14064
Step 5076/14064
Step 5077/14064
Step 5078/14064
Step 5079/14064
Step 5080/14064
Step 5081/14064
Step 5082/14064
Step 5083/14064
Step 5084/14064
Step 5085/14064
Step 5086/14064
Step 5087/14064
Step 5088/14064
Step 5089/14064
Step 5090/14064
Step 5091/14064
Step 5092/14064
Step 5093/14064
Step 5094/14064
Step 5095/14064
Step 5096/14064
Step 5097/14064
Step 5098/14064
Step 5099/14064
Step 5100/14064
Step 5101/14064
Step 5102/14064
Step 5103/14064
Step 5104/14064
Step 5105/14064
Step 5106/14064
Step 5107/14064
Step 5108/14064
Step 5109/14064
Step 5110/14064
Step 5111/14064
Step 5112/14064
Step 5113/14064
Step 5114/14064
Step 5115/14064
Step 5116/14064
Step 5117/14064
Step 5118/14064
Step 5119/14064
Step 5120/14064
Step 5121/14064
Step 5122/14064
Step 5123/14064
Step 5124/14064
Step 5125/14064
Step 5126/14064
Step 5127/14064
Step 5128/14064
Step 5129/14064
Step 5130/14064
Step 5131/14064
Step 5132/14064
Step 5133/14064
Step 5134/14064
Step 5135/14064
Step 5136/14064
Step 5137/14064
Step 5138/14064
Step 5139/14064
Step 5140/14064
Step 5141/14064
Step 5142/14064
Step 5143/14064
Step 5144/14064
Step 5145/14064
Step 5146/14064
Step 5147/14064
Step 5148/14064
Step 5149/14064
Step 5150/14064
Step 5151/14064
Step 5152/14064
Step 5153/14064
Step 5154/14064
Step 5155/14064
Step 5156/14064
Step 5157/14064
Step 5158/14064
Step 5159/14064
Step 5160/14064
Step 5161/14064
Step 5162/14064
Step 5163/14064
Step 5164/14064
Step 5165/14064
Step 5166/14064
Step 5167/14064
Step 5168/14064
Step 5169/14064
Step 5170/14064
Step 5171/14064
Step 5172/14064
Step 5173/14064
Step 5174/14064
Step 5175/14064
Step 5176/14064
Step 5177/14064
Step 5178/14064
Step 5179/14064
Step 5180/14064
Step 5181/14064
Step 5182/14064
Step 5183/14064
Step 5184/14064
Step 5185/14064
Step 5186/14064
Step 5187/14064
Step 5188/14064
Step 5189/14064
Step 5190/14064
Step 5191/14064
Step 5192/14064
Step 5193/14064
Step 5194/14064
Step 5195/14064
Step 5196/14064
Step 5197/14064
Step 5198/14064
Step 5199/14064
Step 5200/14064
Step 5201/14064
Step 5202/14064
Step 5203/14064
Step 5204/14064
Step 5205/14064
Step 5206/14064
Step 5207/14064
Step 5208/14064
Step 5209/14064
Step 5210/14064
Step 5211/14064
Step 5212/14064
Step 5213/14064
Step 5214/14064
Step 5215/14064
Step 5216/14064
Step 5217/14064
Step 5218/14064
Step 5219/14064
Step 5220/14064
Step 5221/14064
Step 5222/14064
Step 5223/14064
Step 5224/14064
Step 5225/14064
Step 5226/14064
Step 5227/14064
Step 5228/14064
Step 5229/14064
Step 5230/14064
Step 5231/14064
Step 5232/14064
Step 5233/14064
Step 5234/14064
Step 5235/14064
Step 5236/14064
Step 5237/14064
Step 5238/14064
Step 5239/14064
Step 5240/14064
Step 5241/14064
Step 5242/14064
Step 5243/14064
Step 5244/14064
Step 5245/14064
Step 5246/14064
Step 5247/14064
Step 5248/14064
Step 5249/14064
Step 5250/14064
Step 5251/14064
Step 5252/14064
Step 5253/14064
Step 5254/14064
Step 5255/14064
Step 5256/14064
Step 5257/14064
Step 5258/14064
Step 5259/14064
Step 5260/14064
Step 5261/14064
Step 5262/14064
Step 5263/14064
Step 5264/14064
Step 5265/14064
Step 5266/14064
Step 5267/14064
Step 5268/14064
Step 5269/14064
Step 5270/14064
Step 5271/14064
Step 5272/14064
Step 5273/14064
Step 5274/14064
Step 5275/14064
Step 5276/14064
Step 5277/14064
Step 5278/14064
Step 5279/14064
Step 5280/14064
Step 5281/14064
Step 5282/14064
Step 5283/14064
Step 5284/14064
Step 5285/14064
Step 5286/14064
Step 5287/14064
Step 5288/14064
Step 5289/14064
Step 5290/14064
Step 5291/14064
Step 5292/14064
Step 5293/14064
Step 5294/14064
Step 5295/14064
Step 5296/14064
Step 5297/14064
Step 5298/14064
Step 5299/14064
Step 5300/14064
Step 5301/14064
Step 5302/14064
Step 5303/14064
Step 5304/14064
Step 5305/14064
Step 5306/14064
Step 5307/14064
Step 5308/14064
Step 5309/14064
Step 5310/14064
Step 5311/14064
Step 5312/14064
Step 5313/14064
Step 5314/14064
Step 5315/14064
Step 5316/14064
Step 5317/14064
Step 5318/14064
Step 5319/14064
Step 5320/14064
Step 5321/14064
Step 5322/14064
Step 5323/14064
Step 5324/14064
Step 5325/14064
Step 5326/14064
Step 5327/14064
Step 5328/14064
Step 5329/14064
Step 5330/14064
Step 5331/14064
Step 5332/14064
Step 5333/14064
Step 5334/14064
Step 5335/14064
Step 5336/14064
Step 5337/14064
Step 5338/14064
Step 5339/14064
Step 5340/14064
Step 5341/14064
Step 5342/14064
Step 5343/14064
Step 5344/14064
Step 5345/14064
Step 5346/14064
Step 5347/14064
Step 5348/14064
Step 5349/14064
Step 5350/14064
Step 5351/14064
Step 5352/14064
Step 5353/14064
Step 5354/14064
Step 5355/14064
Step 5356/14064
Step 5357/14064
Step 5358/14064
Step 5359/14064
Step 5360/14064
Step 5361/14064
Step 5362/14064
Step 5363/14064
Step 5364/14064
Step 5365/14064
Step 5366/14064
Step 5367/14064
Step 5368/14064
Step 5369/14064
Step 5370/14064
Step 5371/14064
Step 5372/14064
Step 5373/14064
Step 5374/14064
Step 5375/14064
Step 5376/14064
Step 5377/14064
Step 5378/14064
Step 5379/14064
Step 5380/14064
Step 5381/14064
Step 5382/14064
Step 5383/14064
Step 5384/14064
Step 5385/14064
Step 5386/14064
Step 5387/14064
Step 5388/14064
Step 5389/14064
Step 5390/14064
Step 5391/14064
Step 5392/14064
Step 5393/14064
Step 5394/14064
Step 5395/14064
Step 5396/14064
Step 5397/14064
Step 5398/14064
Step 5399/14064
Step 5400/14064
Step 5401/14064
Step 5402/14064
Step 5403/14064
Step 5404/14064
Step 5405/14064
Step 5406/14064
Step 5407/14064
Step 5408/14064
Step 5409/14064
Step 5410/14064
Step 5411/14064
Step 5412/14064
Step 5413/14064
Step 5414/14064
Step 5415/14064
Step 5416/14064
Step 5417/14064
Step 5418/14064
Step 5419/14064
Step 5420/14064
Step 5421/14064
Step 5422/14064
Step 5423/14064
Step 5424/14064
Step 5425/14064
Step 5426/14064
Step 5427/14064
Step 5428/14064
Step 5429/14064
Step 5430/14064
Step 5431/14064
Step 5432/14064
Step 5433/14064
Step 5434/14064
Step 5435/14064
Step 5436/14064
Step 5437/14064
Step 5438/14064
Step 5439/14064
Step 5440/14064
Step 5441/14064
Step 5442/14064
Step 5443/14064
Step 5444/14064
Step 5445/14064
Step 5446/14064
Step 5447/14064
Step 5448/14064
Step 5449/14064
Step 5450/14064
Step 5451/14064
Step 5452/14064
Step 5453/14064
Step 5454/14064
Step 5455/14064
Step 5456/14064
Step 5457/14064
Step 5458/14064
Step 5459/14064
Step 5460/14064
Step 5461/14064
Step 5462/14064
Step 5463/14064
Step 5464/14064
Step 5465/14064
Step 5466/14064
Step 5467/14064
Step 5468/14064
Step 5469/14064
Step 5470/14064
Step 5471/14064
Step 5472/14064
Step 5473/14064
Step 5474/14064
Step 5475/14064
Step 5476/14064
Step 5477/14064
Step 5478/14064
Step 5479/14064
Step 5480/14064
Step 5481/14064
Step 5482/14064
Step 5483/14064
Step 5484/14064
Step 5485/14064
Step 5486/14064
Step 5487/14064
Step 5488/14064
Step 5489/14064
Step 5490/14064
Step 5491/14064
Step 5492/14064
Step 5493/14064
Step 5494/14064
Step 5495/14064
Step 5496/14064
Step 5497/14064
Step 5498/14064
Step 5499/14064
Step 5500/14064
Step 5501/14064
Step 5502/14064
Step 5503/14064
Step 5504/14064
Step 5505/14064
Step 5506/14064
Step 5507/14064
Step 5508/14064
Step 5509/14064
Step 5510/14064
Step 5511/14064
Step 5512/14064
Step 5513/14064
Step 5514/14064
Step 5515/14064
Step 5516/14064
Step 5517/14064
Step 5518/14064
Step 5519/14064
Step 5520/14064
Step 5521/14064
Step 5522/14064
Step 5523/14064
Step 5524/14064
Step 5525/14064
Step 5526/14064
Step 5527/14064
Step 5528/14064
Step 5529/14064
Step 5530/14064
Step 5531/14064
Step 5532/14064
Step 5533/14064
Step 5534/14064
Step 5535/14064
Step 5536/14064
Step 5537/14064
Step 5538/14064
Step 5539/14064
Step 5540/14064
Step 5541/14064
Step 5542/14064
Step 5543/14064
Step 5544/14064
Step 5545/14064
Step 5546/14064
Step 5547/14064
Step 5548/14064
Step 5549/14064
Step 5550/14064
Step 5551/14064
Step 5552/14064
Step 5553/14064
Step 5554/14064
Step 5555/14064
Step 5556/14064
Step 5557/14064
Step 5558/14064
Step 5559/14064
Step 5560/14064
Step 5561/14064
Step 5562/14064
Step 5563/14064
Step 5564/14064
Step 5565/14064
Step 5566/14064
Step 5567/14064
Step 5568/14064
Step 5569/14064
Step 5570/14064
Step 5571/14064
Step 5572/14064
Step 5573/14064
Step 5574/14064
Step 5575/14064
Step 5576/14064
Step 5577/14064
Step 5578/14064
Step 5579/14064
Step 5580/14064
Step 5581/14064
Step 5582/14064
Step 5583/14064
Step 5584/14064
Step 5585/14064
Step 5586/14064
Step 5587/14064
Step 5588/14064
Step 5589/14064
Step 5590/14064
Step 5591/14064
Step 5592/14064
Step 5593/14064
Step 5594/14064
Step 5595/14064
Step 5596/14064
Step 5597/14064
Step 5598/14064
Step 5599/14064
Step 5600/14064
Step 5601/14064
Step 5602/14064
Step 5603/14064
Step 5604/14064
Step 5605/14064
Step 5606/14064
Step 5607/14064
Step 5608/14064
Step 5609/14064
Step 5610/14064
Step 5611/14064
Step 5612/14064
Step 5613/14064
Step 5614/14064
Step 5615/14064
Step 5616/14064
Step 5617/14064
Step 5618/14064
Step 5619/14064
Step 5620/14064
Step 5621/14064
Step 5622/14064
Step 5623/14064
Step 5624/14064
Step 5625/14064
Step 5626/14064
Step 5627/14064
Step 5628/14064
Step 5629/14064
Step 5630/14064
Step 5631/14064
Step 5632/14064
Step 5633/14064
Step 5634/14064
Step 5635/14064
Step 5636/14064
Step 5637/14064
Step 5638/14064
Step 5639/14064
Step 5640/14064
Step 5641/14064
Step 5642/14064
Step 5643/14064
Step 5644/14064
Step 5645/14064
Step 5646/14064
Step 5647/14064
Step 5648/14064
Step 5649/14064
Step 5650/14064
Step 5651/14064
Step 5652/14064
Step 5653/14064
Step 5654/14064
Step 5655/14064
Step 5656/14064
Step 5657/14064
Step 5658/14064
Step 5659/14064
Step 5660/14064
Step 5661/14064
Step 5662/14064
Step 5663/14064
Step 5664/14064
Step 5665/14064
Step 5666/14064
Step 5667/14064
Step 5668/14064
Step 5669/14064
Step 5670/14064
Step 5671/14064
Step 5672/14064
Step 5673/14064
Step 5674/14064
Step 5675/14064
Step 5676/14064
Step 5677/14064
Step 5678/14064
Step 5679/14064
Step 5680/14064
Step 5681/14064
Step 5682/14064
Step 5683/14064
Step 5684/14064
Step 5685/14064
Step 5686/14064
Step 5687/14064
Step 5688/14064
Step 5689/14064
Step 5690/14064
Step 5691/14064
Step 5692/14064
Step 5693/14064
Step 5694/14064
Step 5695/14064
Step 5696/14064
Step 5697/14064
Step 5698/14064
Step 5699/14064
Step 5700/14064
Step 5701/14064
Step 5702/14064
Step 5703/14064
Step 5704/14064
Step 5705/14064
Step 5706/14064
Step 5707/14064
Step 5708/14064
Step 5709/14064
Step 5710/14064
Step 5711/14064
Step 5712/14064
Step 5713/14064
Step 5714/14064
Step 5715/14064
Step 5716/14064
Step 5717/14064
Step 5718/14064
Step 5719/14064
Step 5720/14064
Step 5721/14064
Step 5722/14064
Step 5723/14064
Step 5724/14064
Step 5725/14064
Step 5726/14064
Step 5727/14064
Step 5728/14064
Step 5729/14064
Step 5730/14064
Step 5731/14064
Step 5732/14064
Step 5733/14064
Step 5734/14064
Step 5735/14064
Step 5736/14064
Step 5737/14064
Step 5738/14064
Step 5739/14064
Step 5740/14064
Step 5741/14064
Step 5742/14064
Step 5743/14064
Step 5744/14064
Step 5745/14064
Step 5746/14064
Step 5747/14064
Step 5748/14064
Step 5749/14064
Step 5750/14064
Step 5751/14064
Step 5752/14064
Step 5753/14064
Step 5754/14064
Step 5755/14064
Step 5756/14064
Step 5757/14064
Step 5758/14064
Step 5759/14064
Step 5760/14064
Step 5761/14064
Step 5762/14064
Step 5763/14064
Step 5764/14064
Step 5765/14064
Step 5766/14064
Step 5767/14064
Step 5768/14064
Step 5769/14064
Step 5770/14064
Step 5771/14064
Step 5772/14064
Step 5773/14064
Step 5774/14064
Step 5775/14064
Step 5776/14064
Step 5777/14064
Step 5778/14064
Step 5779/14064
Step 5780/14064
Step 5781/14064
Step 5782/14064
Step 5783/14064
Step 5784/14064
Step 5785/14064
Step 5786/14064
Step 5787/14064
Step 5788/14064
Step 5789/14064
Step 5790/14064
Step 5791/14064
Step 5792/14064
Step 5793/14064
Step 5794/14064
Step 5795/14064
Step 5796/14064
Step 5797/14064
Step 5798/14064
Step 5799/14064
Step 5800/14064
Step 5801/14064
Step 5802/14064
Step 5803/14064
Step 5804/14064
Step 5805/14064
Step 5806/14064
Step 5807/14064
Step 5808/14064
Step 5809/14064
Step 5810/14064
Step 5811/14064
Step 5812/14064
Step 5813/14064
Step 5814/14064
Step 5815/14064
Step 5816/14064
Step 5817/14064
Step 5818/14064
Step 5819/14064
Step 5820/14064
Step 5821/14064
Step 5822/14064
Step 5823/14064
Step 5824/14064
Step 5825/14064
Step 5826/14064
Step 5827/14064
Step 5828/14064
Step 5829/14064
Step 5830/14064
Step 5831/14064
Step 5832/14064
Step 5833/14064
Step 5834/14064
Step 5835/14064
Step 5836/14064
Step 5837/14064
Step 5838/14064
Step 5839/14064
Step 5840/14064
Step 5841/14064
Step 5842/14064
Step 5843/14064
Step 5844/14064
Step 5845/14064
Step 5846/14064
Step 5847/14064
Step 5848/14064
Step 5849/14064
Step 5850/14064
Step 5851/14064
Step 5852/14064
Step 5853/14064
Step 5854/14064
Step 5855/14064
Step 5856/14064
Step 5857/14064
Step 5858/14064
Step 5859/14064
Step 5860/14064
Step 5861/14064
Step 5862/14064
Step 5863/14064
Step 5864/14064
Step 5865/14064
Step 5866/14064
Step 5867/14064
Step 5868/14064
Step 5869/14064
Step 5870/14064
Step 5871/14064
Step 5872/14064
Step 5873/14064
Step 5874/14064
Step 5875/14064
Step 5876/14064
Step 5877/14064
Step 5878/14064
Step 5879/14064
Step 5880/14064
Step 5881/14064
Step 5882/14064
Step 5883/14064
Step 5884/14064
Step 5885/14064
Step 5886/14064
Step 5887/14064
Step 5888/14064
Step 5889/14064
Step 5890/14064
Step 5891/14064
Step 5892/14064
Step 5893/14064
Step 5894/14064
Step 5895/14064
Step 5896/14064
Step 5897/14064
Step 5898/14064
Step 5899/14064
Step 5900/14064
Step 5901/14064
Step 5902/14064
Step 5903/14064
Step 5904/14064
Step 5905/14064
Step 5906/14064
Step 5907/14064
Step 5908/14064
Step 5909/14064
Step 5910/14064
Step 5911/14064
Step 5912/14064
Step 5913/14064
Step 5914/14064
Step 5915/14064
Step 5916/14064
Step 5917/14064
Step 5918/14064
Step 5919/14064
Step 5920/14064
Step 5921/14064
Step 5922/14064
Step 5923/14064
Step 5924/14064
Step 5925/14064
Step 5926/14064
Step 5927/14064
Step 5928/14064
Step 5929/14064
Step 5930/14064
Step 5931/14064
Step 5932/14064
Step 5933/14064
Step 5934/14064
Step 5935/14064
Step 5936/14064
Step 5937/14064
Step 5938/14064

***** Running Evaluation *****
  Num examples = 60000
  Batch size = 64
Saving model checkpoint to /kaggle/working/checkpoints_a/checkpoint-9376
Configuration saved in /kaggle/working/checkpoints_a/checkpoint-9376/config.json
Model weights saved in /kaggle/working/checkpoints_a/checkpoint-9376/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_a/checkpoint-9376/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_a/checkpoint-9376/special_tokens_map.json

Step 9377/14064
Step 9378/14064
Step 9379/14064
Step 9380/14064
Step 9381/14064
Step 9382/14064
Step 9383/14064
Step 9384/14064
Step 9385/14064
Step 9386/14064
Step 9387/14064
Step 9388/14064
Step 9389/14064
Step 9390/14064
Step 9391/14064
Step 9392/14064
Step 9393/14064
Step 9394/14064
Step 9395/14064
Step 9396/14064
Step 9397/14064
Step 9398/14064
Step 9399/14064
Step 9400/14064
Step 9401/14064
Step 9402/14064
Step 9403/14064
Step 9404/14064
Step 9405/14064
Step 9406/14064
Step 9407/14064
Step 9408/14064
Step 9409/14064
Step 9410/14064
Step 9411/14064
Step 9412/14064
Step 9413/14064
Step 9414/14064
Step 9415/14064
Step 9416/14064
Step 9417/14064
Step 9418/14064
Step 9419/14064
Step 9420/14064
Step 9421/14064
Step 9422/14064
Step 9423/14064
Step 9424/14064
Step 9425/14064
Step 9426/14064
Step 9427/14064
Step 9428/14064
Step 9429/14064
Step 9430/14064
Step 9431/14064
Step 9432/14064
Step 9433/14064
Step 9434/14064
Step 9435/14064
Step 9436/14064
Step 9437/14064
Step 9438/14064
Step 9439/14064
Step 9440/14064
Step 9441/14064
Step 9442/14064
Step 9443/14064
Step 9444/14064
Step 9445/14064
Step 9446/14064
Step 9447/14064
Step 9448/14064
Step 9449/14064
Step 9450/14064
Step 9451/14064
Step 9452/14064
Step 9453/14064
Step 9454/14064
Step 9455/14064
Step 9456/14064
Step 9457/14064
Step 9458/14064
Step 9459/14064
Step 9460/14064
Step 9461/14064
Step 9462/14064
Step 9463/14064
Step 9464/14064
Step 9465/14064
Step 9466/14064
Step 9467/14064
Step 9468/14064
Step 9469/14064
Step 9470/14064
Step 9471/14064
Step 9472/14064
Step 9473/14064
Step 9474/14064
Step 9475/14064
Step 9476/14064
Step 9477/14064
Step 9478/14064
Step 9479/14064
Step 9480/14064
Step 9481/14064
Step 9482/14064
Step 9483/14064
Step 9484/14064
Step 9485/14064
Step 9486/14064
Step 9487/14064
Step 9488/14064
Step 9489/14064
Step 9490/14064
Step 9491/14064
Step 9492/14064
Step 9493/14064
Step 9494/14064
Step 9495/14064
Step 9496/14064
Step 9497/14064
Step 9498/14064
Step 9499/14064
Step 9500/14064
Step 9501/14064
Step 9502/14064
Step 9503/14064
Step 9504/14064
Step 9505/14064
Step 9506/14064
Step 9507/14064
Step 9508/14064
Step 9509/14064
Step 9510/14064
Step 9511/14064
Step 9512/14064
Step 9513/14064
Step 9514/14064
Step 9515/14064
Step 9516/14064
Step 9517/14064
Step 9518/14064
Step 9519/14064
Step 9520/14064
Step 9521/14064
Step 9522/14064
Step 9523/14064
Step 9524/14064
Step 9525/14064
Step 9526/14064
Step 9527/14064
Step 9528/14064
Step 9529/14064
Step 9530/14064
Step 9531/14064
Step 9532/14064
Step 9533/14064
Step 9534/14064
Step 9535/14064
Step 9536/14064
Step 9537/14064
Step 9538/14064
Step 9539/14064
Step 9540/14064
Step 9541/14064
Step 9542/14064
Step 9543/14064
Step 9544/14064
Step 9545/14064
Step 9546/14064
Step 9547/14064
Step 9548/14064
Step 9549/14064
Step 9550/14064
Step 9551/14064
Step 9552/14064
Step 9553/14064
Step 9554/14064
Step 9555/14064
Step 9556/14064
Step 9557/14064
Step 9558/14064
Step 9559/14064
Step 9560/14064
Step 9561/14064
Step 9562/14064
Step 9563/14064
Step 9564/14064
Step 9565/14064
Step 9566/14064
Step 9567/14064
Step 9568/14064
Step 9569/14064
Step 9570/14064
Step 9571/14064
Step 9572/14064
Step 9573/14064
Step 9574/14064
Step 9575/14064
Step 9576/14064
Step 9577/14064
Step 9578/14064
Step 9579/14064
Step 9580/14064
Step 9581/14064
Step 9582/14064
Step 9583/14064
Step 9584/14064
Step 9585/14064
Step 9586/14064
Step 9587/14064
Step 9588/14064
Step 9589/14064
Step 9590/14064
Step 9591/14064
Step 9592/14064
Step 9593/14064
Step 9594/14064
Step 9595/14064
Step 9596/14064
Step 9597/14064
Step 9598/14064
Step 9599/14064
Step 9600/14064
Step 9601/14064
Step 9602/14064
Step 9603/14064
Step 9604/14064
Step 9605/14064
Step 9606/14064
Step 9607/14064
Step 9608/14064
Step 9609/14064
Step 9610/14064
Step 9611/14064
Step 9612/14064
Step 9613/14064
Step 9614/14064
Step 9615/14064
Step 9616/14064
Step 9617/14064
Step 9618/14064
Step 9619/14064
Step 9620/14064
Step 9621/14064
Step 9622/14064
Step 9623/14064
Step 9624/14064
Step 9625/14064
Step 9626/14064
Step 9627/14064
Step 9628/14064
Step 9629/14064
Step 9630/14064
Step 9631/14064
Step 9632/14064
Step 9633/14064
Step 9634/14064
Step 9635/14064
Step 9636/14064
Step 9637/14064
Step 9638/14064
Step 9639/14064
Step 9640/14064
Step 9641/14064
Step 9642/14064
Step 9643/14064
Step 9644/14064
Step 9645/14064
Step 9646/14064
Step 9647/14064
Step 9648/14064
Step 9649/14064
Step 9650/14064
Step 9651/14064
Step 9652/14064
Step 9653/14064
Step 9654/14064
Step 9655/14064
Step 9656/14064
Step 9657/14064
Step 9658/14064
Step 9659/14064
Step 9660/14064
Step 9661/14064
Step 9662/14064
Step 9663/14064
Step 9664/14064
Step 9665/14064
Step 9666/14064
Step 9667/14064
Step 9668/14064
Step 9669/14064
Step 9670/14064
Step 9671/14064
Step 9672/14064
Step 9673/14064
Step 9674/14064
Step 9675/14064
Step 9676/14064
Step 9677/14064
Step 9678/14064
Step 9679/14064
Step 9680/14064
Step 9681/14064
Step 9682/14064
Step 9683/14064
Step 9684/14064
Step 9685/14064
Step 9686/14064
Step 9687/14064
Step 9688/14064
Step 9689/14064
Step 9690/14064
Step 9691/14064
Step 9692/14064
Step 9693/14064
Step 9694/14064
Step 9695/14064
Step 9696/14064
Step 9697/14064
Step 9698/14064
Step 9699/14064
Step 9700/14064
Step 9701/14064
Step 9702/14064
Step 9703/14064
Step 9704/14064
Step 9705/14064
Step 9706/14064
Step 9707/14064
Step 9708/14064
Step 9709/14064
Step 9710/14064
Step 9711/14064
Step 9712/14064
Step 9713/14064
Step 9714/14064
Step 9715/14064
Step 9716/14064
Step 9717/14064
Step 9718/14064
Step 9719/14064
Step 9720/14064
Step 9721/14064
Step 9722/14064
Step 9723/14064
Step 9724/14064
Step 9725/14064
Step 9726/14064
Step 9727/14064
Step 9728/14064
Step 9729/14064
Step 9730/14064
Step 9731/14064
Step 9732/14064
Step 9733/14064
Step 9734/14064
Step 9735/14064
Step 9736/14064
Step 9737/14064
Step 9738/14064
Step 9739/14064
Step 9740/14064
Step 9741/14064
Step 9742/14064
Step 9743/14064
Step 9744/14064
Step 9745/14064
Step 9746/14064
Step 9747/14064
Step 9748/14064
Step 9749/14064
Step 9750/14064
Step 9751/14064
Step 9752/14064
Step 9753/14064
Step 9754/14064
Step 9755/14064
Step 9756/14064
Step 9757/14064
Step 9758/14064
Step 9759/14064
Step 9760/14064
Step 9761/14064
Step 9762/14064
Step 9763/14064
Step 9764/14064
Step 9765/14064
Step 9766/14064
Step 9767/14064
Step 9768/14064
Step 9769/14064
Step 9770/14064
Step 9771/14064
Step 9772/14064
Step 9773/14064
Step 9774/14064
Step 9775/14064
Step 9776/14064
Step 9777/14064
Step 9778/14064
Step 9779/14064
Step 9780/14064
Step 9781/14064
Step 9782/14064
Step 9783/14064
Step 9784/14064
Step 9785/14064
Step 9786/14064
Step 9787/14064
Step 9788/14064
Step 9789/14064
Step 9790/14064
Step 9791/14064
Step 9792/14064
Step 9793/14064
Step 9794/14064
Step 9795/14064
Step 9796/14064
Step 9797/14064
Step 9798/14064
Step 9799/14064
Step 9800/14064
Step 9801/14064
Step 9802/14064
Step 9803/14064
Step 9804/14064
Step 9805/14064
Step 9806/14064
Step 9807/14064
Step 9808/14064
Step 9809/14064
Step 9810/14064
Step 9811/14064
Step 9812/14064
Step 9813/14064
Step 9814/14064
Step 9815/14064
Step 9816/14064
Step 9817/14064
Step 9818/14064
Step 9819/14064
Step 9820/14064
Step 9821/14064
Step 9822/14064
Step 9823/14064
Step 9824/14064
Step 9825/14064
Step 9826/14064
Step 9827/14064
Step 9828/14064
Step 9829/14064
Step 9830/14064
Step 9831/14064
Step 9832/14064
Step 9833/14064
Step 9834/14064
Step 9835/14064
Step 9836/14064
Step 9837/14064
Step 9838/14064
Step 9839/14064
Step 9840/14064
Step 9841/14064
Step 9842/14064
Step 9843/14064
Step 9844/14064
Step 9845/14064
Step 9846/14064
Step 9847/14064
Step 9848/14064
Step 9849/14064
Step 9850/14064
Step 9851/14064
Step 9852/14064
Step 9853/14064
Step 9854/14064
Step 9855/14064
Step 9856/14064
Step 9857/14064
Step 9858/14064
Step 9859/14064
Step 9860/14064
Step 9861/14064
Step 9862/14064
Step 9863/14064
Step 9864/14064
Step 9865/14064
Step 9866/14064
Step 9867/14064
Step 9868/14064
Step 9869/14064
Step 9870/14064
Step 9871/14064
Step 9872/14064
Step 9873/14064
Step 9874/14064
Step 9875/14064
Step 9876/14064
Step 9877/14064
Step 9878/14064
Step 9879/14064
Step 9880/14064
Step 9881/14064
Step 9882/14064
Step 9883/14064
Step 9884/14064
Step 9885/14064
Step 9886/14064
Step 9887/14064
Step 9888/14064
Step 9889/14064
Step 9890/14064
Step 9891/14064
Step 9892/14064
Step 9893/14064
Step 9894/14064
Step 9895/14064
Step 9896/14064
Step 9897/14064
Step 9898/14064
Step 9899/14064
Step 9900/14064
Step 9901/14064
Step 9902/14064
Step 9903/14064
Step 9904/14064
Step 9905/14064
Step 9906/14064
Step 9907/14064
Step 9908/14064
Step 9909/14064
Step 9910/14064
Step 9911/14064
Step 9912/14064
Step 9913/14064
Step 9914/14064
Step 9915/14064
Step 9916/14064
Step 9917/14064
Step 9918/14064
Step 9919/14064
Step 9920/14064
Step 9921/14064
Step 9922/14064
Step 9923/14064
Step 9924/14064
Step 9925/14064
Step 9926/14064
Step 9927/14064
Step 9928/14064
Step 9929/14064
Step 9930/14064
Step 9931/14064
Step 9932/14064
Step 9933/14064
Step 9934/14064
Step 9935/14064
Step 9936/14064
Step 9937/14064
Step 9938/14064
Step 9939/14064
Step 9940/14064
Step 9941/14064
Step 9942/14064
Step 9943/14064
Step 9944/14064
Step 9945/14064
Step 9946/14064
Step 9947/14064
Step 9948/14064
Step 9949/14064
Step 9950/14064
Step 9951/14064
Step 9952/14064
Step 9953/14064
Step 9954/14064
Step 9955/14064
Step 9956/14064
Step 9957/14064
Step 9958/14064
Step 9959/14064
Step 9960/14064
Step 9961/14064
Step 9962/14064
Step 9963/14064
Step 9964/14064
Step 9965/14064
Step 9966/14064
Step 9967/14064
Step 9968/14064
Step 9969/14064
Step 9970/14064
Step 9971/14064
Step 9972/14064
Step 9973/14064
Step 9974/14064
Step 9975/14064
Step 9976/14064
Step 9977/14064
Step 9978/14064
Step 9979/14064
Step 9980/14064
Step 9981/14064
Step 9982/14064
Step 9983/14064
Step 9984/14064
Step 9985/14064
Step 9986/14064
Step 9987/14064
Step 9988/14064
Step 9989/14064
Step 9990/14064
Step 9991/14064
Step 9992/14064
Step 9993/14064
Step 9994/14064
Step 9995/14064
Step 9996/14064
Step 9997/14064
Step 9998/14064
Step 9999/14064
Step 10000/14064
Step 10001/14064
Step 10002/14064
Step 10003/14064
Step 10004/14064
Step 10005/14064
Step 10006/14064
Step 10007/14064
Step 10008/14064
Step 10009/14064
Step 10010/14064
Step 10011/14064
Step 10012/14064
Step 10013/14064
Step 10014/14064
Step 10015/14064
Step 10016/14064
Step 10017/14064
Step 10018/14064
Step 10019/14064
Step 10020/14064
Step 10021/14064
Step 10022/14064
Step 10023/14064
Step 10024/14064
Step 10025/14064
Step 10026/14064
Step 10027/14064
Step 10028/14064
Step 10029/14064
Step 10030/14064
Step 10031/14064
Step 10032/14064
Step 10033/14064
Step 10034/14064
Step 10035/14064
Step 10036/14064
Step 10037/14064
Step 10038/14064
Step 10039/14064
Step 10040/14064
Step 10041/14064
Step 10042/14064
Step 10043/14064
Step 10044/14064
Step 10045/14064
Step 10046/14064
Step 10047/14064
Step 10048/14064
Step 10049/14064
Step 10050/14064
Step 10051/14064
Step 10052/14064
Step 10053/14064
Step 10054/14064
Step 10055/14064
Step 10056/14064
Step 10057/14064
Step 10058/14064
Step 10059/14064
Step 10060/14064
Step 10061/14064
Step 10062/14064
Step 10063/14064
Step 10064/14064
Step 10065/14064
Step 10066/14064
Step 10067/14064
Step 10068/14064
Step 10069/14064
Step 10070/14064
Step 10071/14064
Step 10072/14064
Step 10073/14064
Step 10074/14064
Step 10075/14064
Step 10076/14064
Step 10077/14064
Step 10078/14064
Step 10079/14064
Step 10080/14064
Step 10081/14064
Step 10082/14064
Step 10083/14064
Step 10084/14064
Step 10085/14064
Step 10086/14064
Step 10087/14064
Step 10088/14064
Step 10089/14064
Step 10090/14064
Step 10091/14064
Step 10092/14064
Step 10093/14064
Step 10094/14064
Step 10095/14064
Step 10096/14064
Step 10097/14064
Step 10098/14064
Step 10099/14064
Step 10100/14064
Step 10101/14064
Step 10102/14064
Step 10103/14064
Step 10104/14064
Step 10105/14064
Step 10106/14064
Step 10107/14064
Step 10108/14064
Step 10109/14064
Step 10110/14064
Step 10111/14064
Step 10112/14064
Step 10113/14064
Step 10114/14064
Step 10115/14064
Step 10116/14064
Step 10117/14064
Step 10118/14064
Step 10119/14064
Step 10120/14064
Step 10121/14064
Step 10122/14064
Step 10123/14064
Step 10124/14064
Step 10125/14064
Step 10126/14064
Step 10127/14064
Step 10128/14064
Step 10129/14064
Step 10130/14064
Step 10131/14064
Step 10132/14064
Step 10133/14064
Step 10134/14064
Step 10135/14064
Step 10136/14064
Step 10137/14064
Step 10138/14064
Step 10139/14064
Step 10140/14064
Step 10141/14064
Step 10142/14064
Step 10143/14064
Step 10144/14064
Step 10145/14064
Step 10146/14064
Step 10147/14064
Step 10148/14064
Step 10149/14064
Step 10150/14064
Step 10151/14064
Step 10152/14064
Step 10153/14064
Step 10154/14064
Step 10155/14064
Step 10156/14064
Step 10157/14064
Step 10158/14064
Step 10159/14064
Step 10160/14064
Step 10161/14064
Step 10162/14064
Step 10163/14064
Step 10164/14064
Step 10165/14064
Step 10166/14064
Step 10167/14064
Step 10168/14064
Step 10169/14064
Step 10170/14064
Step 10171/14064
Step 10172/14064
Step 10173/14064
Step 10174/14064
Step 10175/14064
Step 10176/14064
Step 10177/14064
Step 10178/14064
Step 10179/14064
Step 10180/14064
Step 10181/14064
Step 10182/14064
Step 10183/14064
Step 10184/14064
Step 10185/14064
Step 10186/14064
Step 10187/14064
Step 10188/14064
Step 10189/14064
Step 10190/14064
Step 10191/14064
Step 10192/14064
Step 10193/14064
Step 10194/14064
Step 10195/14064
Step 10196/14064
Step 10197/14064
Step 10198/14064
Step 10199/14064
Step 10200/14064
Step 10201/14064
Step 10202/14064
Step 10203/14064
Step 10204/14064
Step 10205/14064
Step 10206/14064
Step 10207/14064
Step 10208/14064
Step 10209/14064
Step 10210/14064
Step 10211/14064
Step 10212/14064
Step 10213/14064
Step 10214/14064
Step 10215/14064
Step 10216/14064
Step 10217/14064
Step 10218/14064
Step 10219/14064
Step 10220/14064
Step 10221/14064
Step 10222/14064
Step 10223/14064
Step 10224/14064
Step 10225/14064
Step 10226/14064
Step 10227/14064
Step 10228/14064
Step 10229/14064
Step 10230/14064
Step 10231/14064
Step 10232/14064
Step 10233/14064
Step 10234/14064
Step 10235/14064
Step 10236/14064
Step 10237/14064
Step 10238/14064
Step 10239/14064
Step 10240/14064
Step 10241/14064
Step 10242/14064
Step 10243/14064
Step 10244/14064
Step 10245/14064
Step 10246/14064
Step 10247/14064
Step 10248/14064
Step 10249/14064
Step 10250/14064
Step 10251/14064
Step 10252/14064
Step 10253/14064
Step 10254/14064
Step 10255/14064
Step 10256/14064
Step 10257/14064
Step 10258/14064
Step 10259/14064
Step 10260/14064
Step 10261/14064
Step 10262/14064
Step 10263/14064
Step 10264/14064
Step 10265/14064
Step 10266/14064
Step 10267/14064
Step 10268/14064
Step 10269/14064
Step 10270/14064
Step 10271/14064
Step 10272/14064
Step 10273/14064
Step 10274/14064
Step 10275/14064
Step 10276/14064
Step 10277/14064
Step 10278/14064
Step 10279/14064
Step 10280/14064
Step 10281/14064
Step 10282/14064
Step 10283/14064
Step 10284/14064
Step 10285/14064
Step 10286/14064
Step 10287/14064
Step 10288/14064
Step 10289/14064
Step 10290/14064
Step 10291/14064
Step 10292/14064
Step 10293/14064
Step 10294/14064
Step 10295/14064
Step 10296/14064
Step 10297/14064
Step 10298/14064
Step 10299/14064
Step 10300/14064
Step 10301/14064
Step 10302/14064
Step 10303/14064
Step 10304/14064
Step 10305/14064
Step 10306/14064
Step 10307/14064
Step 10308/14064
Step 10309/14064
Step 10310/14064
Step 10311/14064
Step 10312/14064
Step 10313/14064
Step 10314/14064
Step 10315/14064
Step 10316/14064
Step 10317/14064
Step 10318/14064
Step 10319/14064
Step 10320/14064
Step 10321/14064
Step 10322/14064
Step 10323/14064
Step 10324/14064
Step 10325/14064
Step 10326/14064
Step 10327/14064
Step 10328/14064
Step 10329/14064
Step 10330/14064
Step 10331/14064
Step 10332/14064
Step 10333/14064
Step 10334/14064
Step 10335/14064
Step 10336/14064
Step 10337/14064
Step 10338/14064
Step 10339/14064
Step 10340/14064
Step 10341/14064
Step 10342/14064
Step 10343/14064
Step 10344/14064
Step 10345/14064
Step 10346/14064
Step 10347/14064
Step 10348/14064
Step 10349/14064
Step 10350/14064
Step 10351/14064
Step 10352/14064
Step 10353/14064
Step 10354/14064
Step 10355/14064
Step 10356/14064
Step 10357/14064
Step 10358/14064
Step 10359/14064
Step 10360/14064
Step 10361/14064
Step 10362/14064
Step 10363/14064
Step 10364/14064
Step 10365/14064
Step 10366/14064
Step 10367/14064
Step 10368/14064
Step 10369/14064
Step 10370/14064
Step 10371/14064
Step 10372/14064
Step 10373/14064
Step 10374/14064
Step 10375/14064
Step 10376/14064
Step 10377/14064
Step 10378/14064
Step 10379/14064
Step 10380/14064
Step 10381/14064
Step 10382/14064
Step 10383/14064
Step 10384/14064
Step 10385/14064
Step 10386/14064
Step 10387/14064
Step 10388/14064
Step 10389/14064
Step 10390/14064
Step 10391/14064
Step 10392/14064
Step 10393/14064
Step 10394/14064
Step 10395/14064
Step 10396/14064
Step 10397/14064
Step 10398/14064
Step 10399/14064
Step 10400/14064
Step 10401/14064
Step 10402/14064
Step 10403/14064
Step 10404/14064
Step 10405/14064
Step 10406/14064
Step 10407/14064
Step 10408/14064
Step 10409/14064
Step 10410/14064
Step 10411/14064
Step 10412/14064
Step 10413/14064
Step 10414/14064
Step 10415/14064
Step 10416/14064
Step 10417/14064
Step 10418/14064
Step 10419/14064
Step 10420/14064
Step 10421/14064
Step 10422/14064
Step 10423/14064
Step 10424/14064
Step 10425/14064
Step 10426/14064
Step 10427/14064
Step 10428/14064
Step 10429/14064
Step 10430/14064
Step 10431/14064
Step 10432/14064
Step 10433/14064
Step 10434/14064
Step 10435/14064
Step 10436/14064
Step 10437/14064
Step 10438/14064
Step 10439/14064
Step 10440/14064
Step 10441/14064
Step 10442/14064
Step 10443/14064
Step 10444/14064
Step 10445/14064
Step 10446/14064
Step 10447/14064
Step 10448/14064
Step 10449/14064
Step 10450/14064
Step 10451/14064
Step 10452/14064
Step 10453/14064
Step 10454/14064
Step 10455/14064
Step 10456/14064
Step 10457/14064
Step 10458/14064
Step 10459/14064
Step 10460/14064
Step 10461/14064
Step 10462/14064
Step 10463/14064
Step 10464/14064
Step 10465/14064
Step 10466/14064
Step 10467/14064
Step 10468/14064
Step 10469/14064
Step 10470/14064
Step 10471/14064
Step 10472/14064
Step 10473/14064
Step 10474/14064
Step 10475/14064
Step 10476/14064
Step 10477/14064
Step 10478/14064
Step 10479/14064
Step 10480/14064
Step 10481/14064
Step 10482/14064
Step 10483/14064
Step 10484/14064
Step 10485/14064
Step 10486/14064
Step 10487/14064
Step 10488/14064
Step 10489/14064
Step 10490/14064
Step 10491/14064
Step 10492/14064
Step 10493/14064
Step 10494/14064
Step 10495/14064
Step 10496/14064
Step 10497/14064
Step 10498/14064
Step 10499/14064
Step 10500/14064
Step 10501/14064
Step 10502/14064
Step 10503/14064
Step 10504/14064
Step 10505/14064
Step 10506/14064
Step 10507/14064
Step 10508/14064
Step 10509/14064
Step 10510/14064
Step 10511/14064
Step 10512/14064
Step 10513/14064
Step 10514/14064
Step 10515/14064
Step 10516/14064
Step 10517/14064
Step 10518/14064
Step 10519/14064
Step 10520/14064
Step 10521/14064
Step 10522/14064
Step 10523/14064
Step 10524/14064
Step 10525/14064
Step 10526/14064
Step 10527/14064
Step 10528/14064
Step 10529/14064
Step 10530/14064
Step 10531/14064
Step 10532/14064
Step 10533/14064
Step 10534/14064
Step 10535/14064
Step 10536/14064
Step 10537/14064
Step 10538/14064
Step 10539/14064
Step 10540/14064
Step 10541/14064
Step 10542/14064
Step 10543/14064
Step 10544/14064
Step 10545/14064
Step 10546/14064
Step 10547/14064
Step 10548/14064
Step 10549/14064
Step 10550/14064
Step 10551/14064
Step 10552/14064
Step 10553/14064
Step 10554/14064
Step 10555/14064
Step 10556/14064
Step 10557/14064
Step 10558/14064
Step 10559/14064
Step 10560/14064
Step 10561/14064
Step 10562/14064
Step 10563/14064
Step 10564/14064
Step 10565/14064
Step 10566/14064
Step 10567/14064
Step 10568/14064
Step 10569/14064
Step 10570/14064
Step 10571/14064
Step 10572/14064
Step 10573/14064
Step 10574/14064
Step 10575/14064
Step 10576/14064
Step 10577/14064
Step 10578/14064
Step 10579/14064
Step 10580/14064
Step 10581/14064
Step 10582/14064
Step 10583/14064
Step 10584/14064
Step 10585/14064
Step 10586/14064
Step 10587/14064
Step 10588/14064
Step 10589/14064

***** Running Evaluation *****
  Num examples = 60000
  Batch size = 64
Saving model checkpoint to /kaggle/working/checkpoints_a/checkpoint-14064
Configuration saved in /kaggle/working/checkpoints_a/checkpoint-14064/config.json
Model weights saved in /kaggle/working/checkpoints_a/checkpoint-14064/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_a/checkpoint-14064/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_a/checkpoint-14064/special_tokens_map.json
Deleting older checkpoint [/kaggle/working/checkpoints_a/checkpoint-4688] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from /kaggle/working/checkpoints_a/checkpoint-9376 (score: 0.9238775430633805).

TrainOutput(global_step=14064, training_loss=0.08522341904718857, metrics={'train_runtime': 8866.0854, 'train_samples_per_second': 101.51, 'train_steps_per_second': 1.586, 'total_flos': 8.8799981184e+16, 'train_loss': 0.08522341904718857, 'epoch': 3.0})

In [30]:
with open("taska_training_results.pkl", "wb") as f:
    pickle.dump(binary_trainer.state.log_history, f)

In [31]:
llm_training_df = training_df[training_df.generator != "Human"].copy()
llm_validation_df = validation_df[validation_df.generator != "Human"].copy()
llm_test_df = test_df[test_df.generator != "Human"].copy()

In [32]:
for df in (llm_training_df, llm_validation_df, llm_test_df):
    for col in ["label", "labels", "binary_label"]:
        if col in df.columns:
            df.drop(columns=[col], inplace=True)

In [38]:
LLM_FAMILIES = [
    "deepseek",
    "qwen",
    "01-ai",
    "bigcode",
    "gemma",
    "phi",
    "meta-llama",
    "ibm-granite",
    "mistral",
    "openai",
]

In [39]:
FAMILY_KEYWORDS = {
    "deepseek": ["deepseek"],
    "qwen": ["qwen"],
    "01-ai": ["01-ai", "yi-coder", "yi coder"],
    "bigcode": ["bigcode", "starcoder"],
    "gemma": ["gemma", "codegemma"],
    "phi": ["phi"],
    "meta-llama": ["llama", "meta-llama"],
    "ibm-granite": ["granite"],
    "mistral": ["mistral", "mixtral", "devstral"],
    "openai": ["gpt", "openai"],
}

In [40]:
def map_to_family(generator_name: str) -> str:
    if not isinstance(generator_name, str):
        return None
    
    name = generator_name.lower()
    
    for family, keywords in FAMILY_KEYWORDS.items():
        for keyword in keywords:
            if keyword in name:
                return family
    
    raise ValueError(f"Unmapped generator: {generator_name}")

In [43]:
for df in (llm_training_df, llm_validation_df, llm_test_df):
    df["llm_family"] = df["generator"].apply(map_to_family)

In [44]:
label2id = {label: i for i, label in enumerate(LLM_FAMILIES)}
id2label = {i: label for label, i in label2id.items()}
num_labels = len(label2id)

In [47]:
for df in (llm_training_df, llm_validation_df, llm_test_df):
    df["labels"] = df["llm_family"].map(label2id).astype("int64")

In [50]:
columns_to_remove = ["generator", "language", "code", "llm_family", "__index_level_0__"]

llm_training_dataset = Dataset.from_pandas(llm_training_df, preserve_index=False)
llm_validation_dataset = Dataset.from_pandas(llm_validation_df, preserve_index=False)
llm_test_dataset = Dataset.from_pandas(llm_test_df, preserve_index=False)

llm_training_tokenized_set = llm_training_dataset.map(preprocess_function, batched=True)
llm_validation_tokenized_set = llm_validation_dataset.map(preprocess_function, batched=True)
llm_test_tokenized_set = llm_test_dataset.map(preprocess_function, batched=True)

for ds in (llm_training_tokenized_set, llm_validation_tokenized_set, llm_test_tokenized_set):
    ds = ds.remove_columns([c for c in columns_to_remove if c in ds.column_names])


llm_training_tokenized_set.set_format("torch")
llm_validation_tokenized_set.set_format("torch")
llm_test_tokenized_set.set_format("torch")

Map:   0%|          | 0/34742 [00:00<?, ? examples/s]

Map:   0%|          | 0/6906 [00:00<?, ? examples/s]

Map:   0%|          | 0/526 [00:00<?, ? examples/s]

In [51]:
llm_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

llm_model.to(device)

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--microsoft--unixcoder-base/snapshots/5604afdc964f6c53782a6813140ade5216b99006/config.json
Model config RobertaConfig {
  "architectures": [
    "RobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "deepseek",
    "1": "qwen",
    "2": "01-ai",
    "3": "bigcode",
    "4": "gemma",
    "5": "phi",
    "6": "meta-llama",
    "7": "ibm-granite",
    "8": "mistral",
    "9": "openai"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "01-ai": 2,
    "bigcode": 3,
    "deepseek": 0,
    "gemma": 4,
    "ibm-granite": 7,
    "meta-llama": 6,
    "mistral": 8,
    "openai": 9,
    "phi": 5,
    "qwen": 1
  },
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 1026,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 10,
  "use_cache": true,
  "vocab_size": 51416
}

loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--microsoft--unixcoder-base/snapshots/5604afdc964f6c53782a6813140ade5216b99006/pytorch_model.bin
Attempting to create safetensors variant
Some weights of the model checkpoint at microsoft/unixcoder-base were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at microsoft/unixcoder-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(51416, 768, padding_idx=1)
      (position_embeddings): Embedding(1026, 768, padding_idx=1)
      (token_type_embeddings): Embedding(10, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=10, bias=True)
  )
)

Safetensors PR exists

In [53]:
counts = torch.tensor(
    llm_training_df["labels"].value_counts().sort_index().values,
    dtype=torch.float
)

class_weights = (1.0 / counts).sqrt()
class_weights = class_weights / class_weights.sum()

In [54]:
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")

        outputs = model(**inputs)
        logits = outputs.logits

        loss_function = torch.nn.CrossEntropyLoss(
            weight=class_weights.to(logits.device)
        )

        loss = loss_function(logits, labels)

        return (loss, outputs) if return_outputs else loss

(OBS) In the TrainingArguments parameters, you have to set the following:
- output_dir="/kaggle/working/checkpoints" (this is the Kaggle notebook folder that stores the output files; you will need to have persistent data, to achieve that the checkpoints must be saved in this folder);
- num_train_epochs=3;
- load_best_model_at_end=True (for best results);
- eval_strategy="epoch";
- save_strategy="epoch";
- save_total_limit=2 (or 3, you set here the last number of checkpoints that remain saved);
- logging_dir="/kaggle/working/logs" (optional, stores log information);
- logging_steps=3000 (optional, add only if you put logging_dir too);

In [55]:
llm_training_args = TrainingArguments(
    output_dir="/kaggle/working/checkpoints_b",
    seed=42,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    weight_decay=0.01,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=4,
    num_train_epochs=5,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    logging_dir="/kaggle/working/logs",
    logging_steps=3000,
    fp16=True,
    disable_tqdm=False,
    ddp_find_unused_parameters=False,
    dataloader_num_workers=0,
    no_cuda=False,
    report_to=[]
)

PyTorch: setting up devices

In [56]:
llm_trainer = WeightedTrainer(
    model=llm_model,
    args=llm_training_args,
    train_dataset=llm_training_tokenized_set,
    eval_dataset=llm_validation_tokenized_set,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(
                   early_stopping_patience=1,
                   early_stopping_threshold=0.001
               ),
               TrainingProgressCallback()]
)

Using auto half precision backend

(OBS) The first execution will have just trainer.train(), because initially you won't have any checkpoints, you start from 0 with the training. After that, you need to replace this instruction with trainer.train(resume_from_checkpoint=True), such that it resumes the training from the last checkpoint.

In [57]:
llm_trainer.train()

The following columns in the Training set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: llm_family, language, code, generator. If llm_family, language, code, generator are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 34,742
  Num Epochs = 5
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 4
  Total optimization steps = 2,715
  Number of trainable parameters = 125,937,418

Step 1/2715

Step 2/2715
Step 3/2715
Step 4/2715
Step 5/2715
Step 6/2715
Step 7/2715
Step 8/2715
Step 9/2715
Step 10/2715
Step 11/2715
Step 12/2715
Step 13/2715
Step 14/2715
Step 15/2715
Step 16/2715
Step 17/2715
Step 18/2715
Step 19/2715
Step 20/2715
Step 21/2715
Step 22/2715
Step 23/2715
Step 24/2715
Step 25/2715
Step 26/2715
Step 27/2715
Step 28/2715
Step 29/2715
Step 30/2715
Step 31/2715
Step 32/2715
Step 33/2715
Step 34/2715
Step 35/2715
Step 36/2715
Step 37/2715
Step 38/2715
Step 39/2715
Step 40/2715
Step 41/2715
Step 42/2715
Step 43/2715
Step 44/2715
Step 45/2715
Step 46/2715
Step 47/2715
Step 48/2715
Step 49/2715
Step 50/2715
Step 51/2715
Step 52/2715
Step 53/2715
Step 54/2715
Step 55/2715
Step 56/2715
Step 57/2715
Step 58/2715
Step 59/2715
Step 60/2715
Step 61/2715
Step 62/2715
Step 63/2715
Step 64/2715
Step 65/2715
Step 66/2715
Step 67/2715
Step 68/2715
Step 69/2715
Step 70/2715
Step 71/2715
Step 72/2715
Step 73/2715
Step 74/2715
Step 75/2715
Step 76/2715
Step 77/2715
Step 78/2715
Step 79/2715
Step 80/2715
Step 81/2715
Step 82/2715
Step 83/2715
Step 84/2715
Step 85/2715
Step 86/2715
Step 87/2715
Step 88/2715
Step 89/2715
Step 90/2715
Step 91/2715
Step 92/2715
Step 93/2715
Step 94/2715
Step 95/2715
Step 96/2715
Step 97/2715
Step 98/2715
Step 99/2715
Step 100/2715
Step 101/2715
Step 102/2715
Step 103/2715
Step 104/2715
Step 105/2715
Step 106/2715
Step 107/2715
Step 108/2715
Step 109/2715
Step 110/2715
Step 111/2715
Step 112/2715
Step 113/2715
Step 114/2715
Step 115/2715
Step 116/2715
Step 117/2715
Step 118/2715
Step 119/2715
Step 120/2715
Step 121/2715
Step 122/2715
Step 123/2715
Step 124/2715
Step 125/2715
Step 126/2715
Step 127/2715
Step 128/2715
Step 129/2715
Step 130/2715
Step 131/2715
Step 132/2715
Step 133/2715
Step 134/2715
Step 135/2715
Step 136/2715
Step 137/2715
Step 138/2715
Step 139/2715
Step 140/2715
Step 141/2715
Step 142/2715
Step 143/2715
Step 144/2715
Step 145/2715
Step 146/2715
Step 147/2715
Step 148/2715
Step 149/2715
Step 150/2715
Step 151/2715
Step 152/2715
Step 153/2715
Step 154/2715
Step 155/2715
Step 156/2715
Step 157/2715
Step 158/2715
Step 159/2715
Step 160/2715
Step 161/2715
Step 162/2715
Step 163/2715
Step 164/2715
Step 165/2715
Step 166/2715
Step 167/2715
Step 168/2715
Step 169/2715
Step 170/2715
Step 171/2715
Step 172/2715
Step 173/2715
Step 174/2715
Step 175/2715
Step 176/2715
Step 177/2715
Step 178/2715
Step 179/2715
Step 180/2715
Step 181/2715
Step 182/2715
Step 183/2715
Step 184/2715
Step 185/2715
Step 186/2715
Step 187/2715
Step 188/2715
Step 189/2715
Step 190/2715
Step 191/2715
Step 192/2715
Step 193/2715
Step 194/2715
Step 195/2715
Step 196/2715
Step 197/2715
Step 198/2715
Step 199/2715
Step 200/2715
Step 201/2715
Step 202/2715
Step 203/2715
Step 204/2715
Step 205/2715
Step 206/2715
Step 207/2715
Step 208/2715
Step 209/2715
Step 210/2715
Step 211/2715
Step 212/2715
Step 213/2715
Step 214/2715
Step 215/2715
Step 216/2715
Step 217/2715
Step 218/2715
Step 219/2715
Step 220/2715
Step 221/2715
Step 222/2715
Step 223/2715
Step 224/2715
Step 225/2715
Step 226/2715
Step 227/2715
Step 228/2715
Step 229/2715
Step 230/2715
Step 231/2715
Step 232/2715
Step 233/2715
Step 234/2715
Step 235/2715
Step 236/2715
Step 237/2715
Step 238/2715
Step 239/2715
Step 240/2715
Step 241/2715
Step 242/2715
Step 243/2715
Step 244/2715
Step 245/2715
Step 246/2715
Step 247/2715
Step 248/2715
Step 249/2715
Step 250/2715
Step 251/2715
Step 252/2715
Step 253/2715
Step 254/2715
Step 255/2715
Step 256/2715
Step 257/2715
Step 258/2715
Step 259/2715
Step 260/2715
Step 261/2715
Step 262/2715
Step 263/2715
Step 264/2715
Step 265/2715
Step 266/2715
Step 267/2715
Step 268/2715
Step 269/2715
Step 270/2715
Step 271/2715
Step 272/2715
Step 273/2715
Step 274/2715
Step 275/2715
Step 276/2715
Step 277/2715
Step 278/2715
Step 279/2715
Step 280/2715
Step 281/2715
Step 282/2715
Step 283/2715
Step 284/2715
Step 285/2715
Step 286/2715
Step 287/2715
Step 288/2715
Step 289/2715
Step 290/2715
Step 291/2715
Step 292/2715
Step 293/2715
Step 294/2715
Step 295/2715
Step 296/2715
Step 297/2715
Step 298/2715
Step 299/2715
Step 300/2715
Step 301/2715
Step 302/2715
Step 303/2715
Step 304/2715
Step 305/2715
Step 306/2715
Step 307/2715
Step 308/2715
Step 309/2715
Step 310/2715
Step 311/2715
Step 312/2715
Step 313/2715
Step 314/2715
Step 315/2715
Step 316/2715
Step 317/2715
Step 318/2715
Step 319/2715
Step 320/2715
Step 321/2715
Step 322/2715
Step 323/2715
Step 324/2715
Step 325/2715
Step 326/2715
Step 327/2715
Step 328/2715
Step 329/2715
Step 330/2715
Step 331/2715
Step 332/2715
Step 333/2715
Step 334/2715
Step 335/2715
Step 336/2715
Step 337/2715
Step 338/2715
Step 339/2715
Step 340/2715
Step 341/2715
Step 342/2715
Step 343/2715
Step 344/2715
Step 345/2715
Step 346/2715
Step 347/2715
Step 348/2715
Step 349/2715
Step 350/2715
Step 351/2715
Step 352/2715
Step 353/2715
Step 354/2715
Step 355/2715
Step 356/2715
Step 357/2715
Step 358/2715
Step 359/2715
Step 360/2715
Step 361/2715
Step 362/2715
Step 363/2715
Step 364/2715
Step 365/2715
Step 366/2715
Step 367/2715
Step 368/2715
Step 369/2715
Step 370/2715
Step 371/2715
Step 372/2715
Step 373/2715
Step 374/2715
Step 375/2715
Step 376/2715
Step 377/2715
Step 378/2715
Step 379/2715
Step 380/2715
Step 381/2715
Step 382/2715
Step 383/2715
Step 384/2715
Step 385/2715
Step 386/2715
Step 387/2715
Step 388/2715
Step 389/2715
Step 390/2715
Step 391/2715
Step 392/2715
Step 393/2715
Step 394/2715
Step 395/2715
Step 396/2715
Step 397/2715
Step 398/2715
Step 399/2715
Step 400/2715
Step 401/2715
Step 402/2715
Step 403/2715
Step 404/2715
Step 405/2715
Step 406/2715
Step 407/2715
Step 408/2715
Step 409/2715
Step 410/2715
Step 411/2715
Step 412/2715
Step 413/2715
Step 414/2715
Step 415/2715
Step 416/2715
Step 417/2715
Step 418/2715
Step 419/2715
Step 420/2715
Step 421/2715
Step 422/2715
Step 423/2715
Step 424/2715
Step 425/2715
Step 426/2715
Step 427/2715
Step 428/2715
Step 429/2715
Step 430/2715
Step 431/2715
Step 432/2715
Step 433/2715
Step 434/2715
Step 435/2715
Step 436/2715
Step 437/2715
Step 438/2715
Step 439/2715
Step 440/2715
Step 441/2715
Step 442/2715
Step 443/2715
Step 444/2715
Step 445/2715
Step 446/2715
Step 447/2715
Step 448/2715
Step 449/2715
Step 450/2715
Step 451/2715
Step 452/2715
Step 453/2715
Step 454/2715
Step 455/2715
Step 456/2715
Step 457/2715
Step 458/2715
Step 459/2715
Step 460/2715
Step 461/2715
Step 462/2715
Step 463/2715
Step 464/2715
Step 465/2715
Step 466/2715
Step 467/2715
Step 468/2715
Step 469/2715
Step 470/2715
Step 471/2715
Step 472/2715
Step 473/2715
Step 474/2715
Step 475/2715
Step 476/2715
Step 477/2715
Step 478/2715
Step 479/2715
Step 480/2715
Step 481/2715
Step 482/2715
Step 483/2715
Step 484/2715
Step 485/2715
Step 486/2715
Step 487/2715
Step 488/2715
Step 489/2715
Step 490/2715
Step 491/2715
Step 492/2715
Step 493/2715
Step 494/2715
Step 495/2715
Step 496/2715
Step 497/2715
Step 498/2715
Step 499/2715
Step 500/2715
Step 501/2715
Step 502/2715
Step 503/2715
Step 504/2715
Step 505/2715
Step 506/2715
Step 507/2715
Step 508/2715
Step 509/2715
Step 510/2715
Step 511/2715
Step 512/2715
Step 513/2715
Step 514/2715
Step 515/2715
Step 516/2715
Step 517/2715
Step 518/2715
Step 519/2715
Step 520/2715
Step 521/2715
Step 522/2715
Step 523/2715
Step 524/2715
Step 525/2715
Step 526/2715
Step 527/2715
Step 528/2715
Step 529/2715
Step 530/2715
Step 531/2715
Step 532/2715
Step 533/2715
Step 534/2715
Step 535/2715
Step 536/2715
Step 537/2715
Step 538/2715
Step 539/2715
Step 540/2715
Step 541/2715
Step 542/2715
Step 543/2715

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: llm_family, language, code, generator. If llm_family, language, code, generator are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 6906
  Batch size = 32
Saving model checkpoint to /kaggle/working/checkpoints_b/checkpoint-543
Configuration saved in /kaggle/working/checkpoints_b/checkpoint-543/config.json
Model weights saved in /kaggle/working/checkpoints_b/checkpoint-543/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_b/checkpoint-543/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_b/checkpoint-543/special_tokens_map.json

Step 544/2715
Step 545/2715
Step 546/2715
Step 547/2715
Step 548/2715
Step 549/2715
Step 550/2715
Step 551/2715
Step 552/2715
Step 553/2715
Step 554/2715
Step 555/2715
Step 556/2715
Step 557/2715
Step 558/2715
Step 559/2715
Step 560/2715
Step 561/2715
Step 562/2715
Step 563/2715
Step 564/2715
Step 565/2715
Step 566/2715
Step 567/2715
Step 568/2715
Step 569/2715
Step 570/2715
Step 571/2715
Step 572/2715
Step 573/2715
Step 574/2715
Step 575/2715
Step 576/2715
Step 577/2715
Step 578/2715
Step 579/2715
Step 580/2715
Step 581/2715
Step 582/2715
Step 583/2715
Step 584/2715
Step 585/2715
Step 586/2715
Step 587/2715
Step 588/2715
Step 589/2715
Step 590/2715
Step 591/2715
Step 592/2715
Step 593/2715
Step 594/2715
Step 595/2715
Step 596/2715
Step 597/2715
Step 598/2715
Step 599/2715
Step 600/2715
Step 601/2715
Step 602/2715
Step 603/2715
Step 604/2715
Step 605/2715
Step 606/2715
Step 607/2715
Step 608/2715
Step 609/2715
Step 610/2715
Step 611/2715
Step 612/2715
Step 613/2715
Step 614/2715
Step 615/2715
Step 616/2715
Step 617/2715
Step 618/2715
Step 619/2715
Step 620/2715
Step 621/2715
Step 622/2715
Step 623/2715
Step 624/2715
Step 625/2715
Step 626/2715
Step 627/2715
Step 628/2715
Step 629/2715
Step 630/2715
Step 631/2715
Step 632/2715
Step 633/2715
Step 634/2715
Step 635/2715
Step 636/2715
Step 637/2715
Step 638/2715
Step 639/2715
Step 640/2715
Step 641/2715
Step 642/2715
Step 643/2715
Step 644/2715
Step 645/2715
Step 646/2715
Step 647/2715
Step 648/2715
Step 649/2715
Step 650/2715
Step 651/2715
Step 652/2715
Step 653/2715
Step 654/2715
Step 655/2715
Step 656/2715
Step 657/2715
Step 658/2715
Step 659/2715
Step 660/2715
Step 661/2715
Step 662/2715
Step 663/2715
Step 664/2715
Step 665/2715
Step 666/2715
Step 667/2715
Step 668/2715
Step 669/2715
Step 670/2715
Step 671/2715
Step 672/2715
Step 673/2715
Step 674/2715
Step 675/2715
Step 676/2715
Step 677/2715
Step 678/2715
Step 679/2715
Step 680/2715
Step 681/2715
Step 682/2715
Step 683/2715
Step 684/2715
Step 685/2715
Step 686/2715
Step 687/2715
Step 688/2715
Step 689/2715
Step 690/2715
Step 691/2715
Step 692/2715
Step 693/2715
Step 694/2715
Step 695/2715
Step 696/2715
Step 697/2715
Step 698/2715
Step 699/2715
Step 700/2715
Step 701/2715
Step 702/2715
Step 703/2715
Step 704/2715
Step 705/2715
Step 706/2715
Step 707/2715
Step 708/2715
Step 709/2715
Step 710/2715
Step 711/2715
Step 712/2715
Step 713/2715
Step 714/2715
Step 715/2715
Step 716/2715
Step 717/2715
Step 718/2715
Step 719/2715
Step 720/2715
Step 721/2715
Step 722/2715
Step 723/2715
Step 724/2715
Step 725/2715
Step 726/2715
Step 727/2715
Step 728/2715
Step 729/2715
Step 730/2715
Step 731/2715
Step 732/2715
Step 733/2715
Step 734/2715
Step 735/2715
Step 736/2715
Step 737/2715
Step 738/2715
Step 739/2715
Step 740/2715
Step 741/2715
Step 742/2715
Step 743/2715
Step 744/2715
Step 745/2715
Step 746/2715
Step 747/2715
Step 748/2715
Step 749/2715
Step 750/2715
Step 751/2715
Step 752/2715
Step 753/2715
Step 754/2715
Step 755/2715
Step 756/2715
Step 757/2715
Step 758/2715
Step 759/2715
Step 760/2715
Step 761/2715
Step 762/2715
Step 763/2715
Step 764/2715
Step 765/2715
Step 766/2715
Step 767/2715
Step 768/2715
Step 769/2715
Step 770/2715
Step 771/2715
Step 772/2715
Step 773/2715
Step 774/2715
Step 775/2715
Step 776/2715
Step 777/2715
Step 778/2715
Step 779/2715
Step 780/2715
Step 781/2715
Step 782/2715
Step 783/2715
Step 784/2715
Step 785/2715
Step 786/2715
Step 787/2715
Step 788/2715
Step 789/2715
Step 790/2715
Step 791/2715
Step 792/2715
Step 793/2715
Step 794/2715
Step 795/2715
Step 796/2715
Step 797/2715
Step 798/2715
Step 799/2715
Step 800/2715
Step 801/2715
Step 802/2715
Step 803/2715
Step 804/2715
Step 805/2715
Step 806/2715
Step 807/2715
Step 808/2715
Step 809/2715
Step 810/2715
Step 811/2715
Step 812/2715
Step 813/2715
Step 814/2715
Step 815/2715
Step 816/2715
Step 817/2715
Step 818/2715
Step 819/2715
Step 820/2715
Step 821/2715
Step 822/2715
Step 823/2715
Step 824/2715
Step 825/2715
Step 826/2715
Step 827/2715
Step 828/2715
Step 829/2715
Step 830/2715
Step 831/2715
Step 832/2715
Step 833/2715
Step 834/2715
Step 835/2715
Step 836/2715
Step 837/2715
Step 838/2715
Step 839/2715
Step 840/2715
Step 841/2715
Step 842/2715
Step 843/2715
Step 844/2715
Step 845/2715
Step 846/2715
Step 847/2715
Step 848/2715
Step 849/2715
Step 850/2715
Step 851/2715
Step 852/2715
Step 853/2715
Step 854/2715
Step 855/2715
Step 856/2715
Step 857/2715
Step 858/2715
Step 859/2715
Step 860/2715
Step 861/2715
Step 862/2715
Step 863/2715
Step 864/2715
Step 865/2715
Step 866/2715
Step 867/2715
Step 868/2715
Step 869/2715
Step 870/2715
Step 871/2715
Step 872/2715
Step 873/2715
Step 874/2715
Step 875/2715
Step 876/2715
Step 877/2715
Step 878/2715
Step 879/2715
Step 880/2715
Step 881/2715
Step 882/2715
Step 883/2715
Step 884/2715
Step 885/2715
Step 886/2715
Step 887/2715
Step 888/2715
Step 889/2715
Step 890/2715
Step 891/2715
Step 892/2715
Step 893/2715
Step 894/2715
Step 895/2715
Step 896/2715
Step 897/2715
Step 898/2715
Step 899/2715
Step 900/2715
Step 901/2715
Step 902/2715
Step 903/2715
Step 904/2715
Step 905/2715
Step 906/2715
Step 907/2715
Step 908/2715
Step 909/2715
Step 910/2715
Step 911/2715
Step 912/2715
Step 913/2715
Step 914/2715
Step 915/2715
Step 916/2715
Step 917/2715
Step 918/2715
Step 919/2715
Step 920/2715
Step 921/2715
Step 922/2715
Step 923/2715
Step 924/2715
Step 925/2715
Step 926/2715
Step 927/2715
Step 928/2715
Step 929/2715
Step 930/2715
Step 931/2715
Step 932/2715
Step 933/2715
Step 934/2715
Step 935/2715
Step 936/2715
Step 937/2715
Step 938/2715
Step 939/2715
Step 940/2715
Step 941/2715
Step 942/2715
Step 943/2715
Step 944/2715
Step 945/2715
Step 946/2715
Step 947/2715
Step 948/2715
Step 949/2715
Step 950/2715
Step 951/2715
Step 952/2715
Step 953/2715
Step 954/2715
Step 955/2715
Step 956/2715
Step 957/2715
Step 958/2715
Step 959/2715
Step 960/2715
Step 961/2715
Step 962/2715
Step 963/2715
Step 964/2715
Step 965/2715
Step 966/2715
Step 967/2715
Step 968/2715
Step 969/2715
Step 970/2715
Step 971/2715
Step 972/2715
Step 973/2715
Step 974/2715
Step 975/2715
Step 976/2715
Step 977/2715
Step 978/2715
Step 979/2715
Step 980/2715
Step 981/2715
Step 982/2715
Step 983/2715
Step 984/2715
Step 985/2715
Step 986/2715
Step 987/2715
Step 988/2715
Step 989/2715
Step 990/2715
Step 991/2715
Step 992/2715
Step 993/2715
Step 994/2715
Step 995/2715
Step 996/2715
Step 997/2715
Step 998/2715
Step 999/2715
Step 1000/2715
Step 1001/2715
Step 1002/2715
Step 1003/2715
Step 1004/2715
Step 1005/2715
Step 1006/2715
Step 1007/2715
Step 1008/2715
Step 1009/2715
Step 1010/2715
Step 1011/2715
Step 1012/2715
Step 1013/2715
Step 1014/2715
Step 1015/2715
Step 1016/2715
Step 1017/2715
Step 1018/2715
Step 1019/2715
Step 1020/2715
Step 1021/2715
Step 1022/2715
Step 1023/2715
Step 1024/2715
Step 1025/2715
Step 1026/2715
Step 1027/2715
Step 1028/2715
Step 1029/2715
Step 1030/2715
Step 1031/2715
Step 1032/2715
Step 1033/2715
Step 1034/2715
Step 1035/2715
Step 1036/2715
Step 1037/2715
Step 1038/2715
Step 1039/2715
Step 1040/2715
Step 1041/2715
Step 1042/2715
Step 1043/2715
Step 1044/2715
Step 1045/2715
Step 1046/2715
Step 1047/2715
Step 1048/2715
Step 1049/2715
Step 1050/2715
Step 1051/2715
Step 1052/2715
Step 1053/2715
Step 1054/2715
Step 1055/2715
Step 1056/2715
Step 1057/2715
Step 1058/2715
Step 1059/2715
Step 1060/2715
Step 1061/2715
Step 1062/2715
Step 1063/2715
Step 1064/2715
Step 1065/2715
Step 1066/2715
Step 1067/2715
Step 1068/2715
Step 1069/2715
Step 1070/2715
Step 1071/2715
Step 1072/2715
Step 1073/2715
Step 1074/2715
Step 1075/2715
Step 1076/2715
Step 1077/2715
Step 1078/2715
Step 1079/2715
Step 1080/2715
Step 1081/2715
Step 1082/2715
Step 1083/2715
Step 1084/2715
Step 1085/2715
Step 1086/2715

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: llm_family, language, code, generator. If llm_family, language, code, generator are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 6906
  Batch size = 32
Saving model checkpoint to /kaggle/working/checkpoints_b/checkpoint-1086
Configuration saved in /kaggle/working/checkpoints_b/checkpoint-1086/config.json
Model weights saved in /kaggle/working/checkpoints_b/checkpoint-1086/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_b/checkpoint-1086/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_b/checkpoint-1086/special_tokens_map.json

Step 1087/2715
Step 1088/2715
Step 1089/2715
Step 1090/2715
Step 1091/2715
Step 1092/2715
Step 1093/2715
Step 1094/2715
Step 1095/2715
Step 1096/2715
Step 1097/2715
Step 1098/2715
Step 1099/2715
Step 1100/2715
Step 1101/2715
Step 1102/2715
Step 1103/2715
Step 1104/2715
Step 1105/2715
Step 1106/2715
Step 1107/2715
Step 1108/2715
Step 1109/2715
Step 1110/2715
Step 1111/2715
Step 1112/2715
Step 1113/2715
Step 1114/2715
Step 1115/2715
Step 1116/2715
Step 1117/2715
Step 1118/2715
Step 1119/2715
Step 1120/2715
Step 1121/2715
Step 1122/2715
Step 1123/2715
Step 1124/2715
Step 1125/2715
Step 1126/2715
Step 1127/2715
Step 1128/2715
Step 1129/2715
Step 1130/2715
Step 1131/2715
Step 1132/2715
Step 1133/2715
Step 1134/2715
Step 1135/2715
Step 1136/2715
Step 1137/2715
Step 1138/2715
Step 1139/2715
Step 1140/2715
Step 1141/2715
Step 1142/2715
Step 1143/2715
Step 1144/2715
Step 1145/2715
Step 1146/2715
Step 1147/2715
Step 1148/2715
Step 1149/2715
Step 1150/2715
Step 1151/2715
Step 1152/2715
Step 1153/2715
Step 1154/2715
Step 1155/2715
Step 1156/2715
Step 1157/2715
Step 1158/2715
Step 1159/2715
Step 1160/2715
Step 1161/2715
Step 1162/2715
Step 1163/2715
Step 1164/2715
Step 1165/2715
Step 1166/2715
Step 1167/2715
Step 1168/2715
Step 1169/2715
Step 1170/2715
Step 1171/2715
Step 1172/2715
Step 1173/2715
Step 1174/2715
Step 1175/2715
Step 1176/2715
Step 1177/2715
Step 1178/2715
Step 1179/2715
Step 1180/2715
Step 1181/2715
Step 1182/2715
Step 1183/2715
Step 1184/2715
Step 1185/2715
Step 1186/2715
Step 1187/2715
Step 1188/2715
Step 1189/2715
Step 1190/2715
Step 1191/2715
Step 1192/2715
Step 1193/2715
Step 1194/2715
Step 1195/2715
Step 1196/2715
Step 1197/2715
Step 1198/2715
Step 1199/2715
Step 1200/2715
Step 1201/2715
Step 1202/2715
Step 1203/2715
Step 1204/2715
Step 1205/2715
Step 1206/2715
Step 1207/2715
Step 1208/2715
Step 1209/2715
Step 1210/2715
Step 1211/2715
Step 1212/2715
Step 1213/2715
Step 1214/2715
Step 1215/2715
Step 1216/2715
Step 1217/2715
Step 1218/2715
Step 1219/2715
Step 1220/2715
Step 1221/2715
Step 1222/2715
Step 1223/2715
Step 1224/2715
Step 1225/2715
Step 1226/2715
Step 1227/2715
Step 1228/2715
Step 1229/2715
Step 1230/2715
Step 1231/2715
Step 1232/2715
Step 1233/2715
Step 1234/2715
Step 1235/2715
Step 1236/2715
Step 1237/2715
Step 1238/2715
Step 1239/2715
Step 1240/2715
Step 1241/2715
Step 1242/2715
Step 1243/2715
Step 1244/2715
Step 1245/2715
Step 1246/2715
Step 1247/2715
Step 1248/2715
Step 1249/2715
Step 1250/2715
Step 1251/2715
Step 1252/2715
Step 1253/2715
Step 1254/2715
Step 1255/2715
Step 1256/2715
Step 1257/2715
Step 1258/2715
Step 1259/2715
Step 1260/2715
Step 1261/2715
Step 1262/2715
Step 1263/2715
Step 1264/2715
Step 1265/2715
Step 1266/2715
Step 1267/2715
Step 1268/2715
Step 1269/2715
Step 1270/2715
Step 1271/2715
Step 1272/2715
Step 1273/2715
Step 1274/2715
Step 1275/2715
Step 1276/2715
Step 1277/2715
Step 1278/2715
Step 1279/2715
Step 1280/2715
Step 1281/2715
Step 1282/2715
Step 1283/2715
Step 1284/2715
Step 1285/2715
Step 1286/2715
Step 1287/2715
Step 1288/2715
Step 1289/2715
Step 1290/2715
Step 1291/2715
Step 1292/2715
Step 1293/2715
Step 1294/2715
Step 1295/2715
Step 1296/2715
Step 1297/2715
Step 1298/2715
Step 1299/2715
Step 1300/2715
Step 1301/2715
Step 1302/2715
Step 1303/2715
Step 1304/2715
Step 1305/2715
Step 1306/2715
Step 1307/2715
Step 1308/2715
Step 1309/2715
Step 1310/2715
Step 1311/2715
Step 1312/2715
Step 1313/2715
Step 1314/2715
Step 1315/2715
Step 1316/2715
Step 1317/2715
Step 1318/2715
Step 1319/2715
Step 1320/2715
Step 1321/2715
Step 1322/2715
Step 1323/2715
Step 1324/2715
Step 1325/2715
Step 1326/2715
Step 1327/2715
Step 1328/2715
Step 1329/2715
Step 1330/2715
Step 1331/2715
Step 1332/2715
Step 1333/2715
Step 1334/2715
Step 1335/2715
Step 1336/2715
Step 1337/2715
Step 1338/2715
Step 1339/2715
Step 1340/2715
Step 1341/2715
Step 1342/2715
Step 1343/2715
Step 1344/2715
Step 1345/2715
Step 1346/2715
Step 1347/2715
Step 1348/2715
Step 1349/2715
Step 1350/2715
Step 1351/2715
Step 1352/2715
Step 1353/2715
Step 1354/2715
Step 1355/2715
Step 1356/2715
Step 1357/2715
Step 1358/2715
Step 1359/2715
Step 1360/2715
Step 1361/2715
Step 1362/2715
Step 1363/2715
Step 1364/2715
Step 1365/2715
Step 1366/2715
Step 1367/2715
Step 1368/2715
Step 1369/2715
Step 1370/2715
Step 1371/2715
Step 1372/2715
Step 1373/2715
Step 1374/2715
Step 1375/2715
Step 1376/2715
Step 1377/2715
Step 1378/2715
Step 1379/2715
Step 1380/2715
Step 1381/2715
Step 1382/2715
Step 1383/2715
Step 1384/2715
Step 1385/2715
Step 1386/2715
Step 1387/2715
Step 1388/2715
Step 1389/2715
Step 1390/2715
Step 1391/2715
Step 1392/2715
Step 1393/2715
Step 1394/2715
Step 1395/2715
Step 1396/2715
Step 1397/2715
Step 1398/2715
Step 1399/2715
Step 1400/2715
Step 1401/2715
Step 1402/2715
Step 1403/2715
Step 1404/2715
Step 1405/2715
Step 1406/2715
Step 1407/2715
Step 1408/2715
Step 1409/2715
Step 1410/2715
Step 1411/2715
Step 1412/2715
Step 1413/2715
Step 1414/2715
Step 1415/2715
Step 1416/2715
Step 1417/2715
Step 1418/2715
Step 1419/2715
Step 1420/2715
Step 1421/2715
Step 1422/2715
Step 1423/2715
Step 1424/2715
Step 1425/2715
Step 1426/2715
Step 1427/2715
Step 1428/2715
Step 1429/2715
Step 1430/2715
Step 1431/2715
Step 1432/2715
Step 1433/2715
Step 1434/2715
Step 1435/2715
Step 1436/2715
Step 1437/2715
Step 1438/2715
Step 1439/2715
Step 1440/2715
Step 1441/2715
Step 1442/2715
Step 1443/2715
Step 1444/2715
Step 1445/2715
Step 1446/2715
Step 1447/2715
Step 1448/2715
Step 1449/2715
Step 1450/2715
Step 1451/2715
Step 1452/2715
Step 1453/2715
Step 1454/2715
Step 1455/2715
Step 1456/2715
Step 1457/2715
Step 1458/2715
Step 1459/2715
Step 1460/2715
Step 1461/2715
Step 1462/2715
Step 1463/2715
Step 1464/2715
Step 1465/2715
Step 1466/2715
Step 1467/2715
Step 1468/2715
Step 1469/2715
Step 1470/2715
Step 1471/2715
Step 1472/2715
Step 1473/2715
Step 1474/2715
Step 1475/2715
Step 1476/2715
Step 1477/2715
Step 1478/2715
Step 1479/2715
Step 1480/2715
Step 1481/2715
Step 1482/2715
Step 1483/2715
Step 1484/2715
Step 1485/2715
Step 1486/2715
Step 1487/2715
Step 1488/2715
Step 1489/2715
Step 1490/2715
Step 1491/2715
Step 1492/2715
Step 1493/2715
Step 1494/2715
Step 1495/2715
Step 1496/2715
Step 1497/2715
Step 1498/2715
Step 1499/2715
Step 1500/2715
Step 1501/2715
Step 1502/2715
Step 1503/2715
Step 1504/2715
Step 1505/2715
Step 1506/2715
Step 1507/2715
Step 1508/2715
Step 1509/2715
Step 1510/2715
Step 1511/2715
Step 1512/2715
Step 1513/2715
Step 1514/2715
Step 1515/2715
Step 1516/2715
Step 1517/2715
Step 1518/2715
Step 1519/2715
Step 1520/2715
Step 1521/2715
Step 1522/2715
Step 1523/2715
Step 1524/2715
Step 1525/2715
Step 1526/2715
Step 1527/2715
Step 1528/2715
Step 1529/2715
Step 1530/2715
Step 1531/2715
Step 1532/2715
Step 1533/2715
Step 1534/2715
Step 1535/2715
Step 1536/2715
Step 1537/2715
Step 1538/2715
Step 1539/2715
Step 1540/2715
Step 1541/2715
Step 1542/2715
Step 1543/2715
Step 1544/2715
Step 1545/2715
Step 1546/2715
Step 1547/2715
Step 1548/2715
Step 1549/2715
Step 1550/2715
Step 1551/2715
Step 1552/2715
Step 1553/2715
Step 1554/2715
Step 1555/2715
Step 1556/2715
Step 1557/2715
Step 1558/2715
Step 1559/2715
Step 1560/2715
Step 1561/2715
Step 1562/2715
Step 1563/2715
Step 1564/2715
Step 1565/2715
Step 1566/2715
Step 1567/2715
Step 1568/2715
Step 1569/2715
Step 1570/2715
Step 1571/2715
Step 1572/2715
Step 1573/2715
Step 1574/2715
Step 1575/2715
Step 1576/2715
Step 1577/2715
Step 1578/2715
Step 1579/2715
Step 1580/2715
Step 1581/2715
Step 1582/2715
Step 1583/2715
Step 1584/2715
Step 1585/2715
Step 1586/2715
Step 1587/2715
Step 1588/2715
Step 1589/2715
Step 1590/2715
Step 1591/2715
Step 1592/2715
Step 1593/2715
Step 1594/2715
Step 1595/2715
Step 1596/2715
Step 1597/2715
Step 1598/2715
Step 1599/2715
Step 1600/2715
Step 1601/2715
Step 1602/2715
Step 1603/2715
Step 1604/2715
Step 1605/2715
Step 1606/2715
Step 1607/2715
Step 1608/2715
Step 1609/2715
Step 1610/2715
Step 1611/2715
Step 1612/2715
Step 1613/2715
Step 1614/2715
Step 1615/2715
Step 1616/2715
Step 1617/2715
Step 1618/2715
Step 1619/2715
Step 1620/2715
Step 1621/2715
Step 1622/2715
Step 1623/2715
Step 1624/2715
Step 1625/2715
Step 1626/2715
Step 1627/2715
Step 1628/2715
Step 1629/2715

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: llm_family, language, code, generator. If llm_family, language, code, generator are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 6906
  Batch size = 32
Saving model checkpoint to /kaggle/working/checkpoints_b/checkpoint-1629
Configuration saved in /kaggle/working/checkpoints_b/checkpoint-1629/config.json
Model weights saved in /kaggle/working/checkpoints_b/checkpoint-1629/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_b/checkpoint-1629/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_b/checkpoint-1629/special_tokens_map.json
Deleting older checkpoint [/kaggle/working/checkpoints_b/checkpoint-543] due to args.save_total_limit

Step 1630/2715
Step 1631/2715
Step 1632/2715
Step 1633/2715
Step 1634/2715
Step 1635/2715
Step 1636/2715
Step 1637/2715
Step 1638/2715
Step 1639/2715
Step 1640/2715
Step 1641/2715
Step 1642/2715
Step 1643/2715
Step 1644/2715
Step 1645/2715
Step 1646/2715
Step 1647/2715
Step 1648/2715
Step 1649/2715
Step 1650/2715
Step 1651/2715
Step 1652/2715
Step 1653/2715
Step 1654/2715
Step 1655/2715
Step 1656/2715
Step 1657/2715
Step 1658/2715
Step 1659/2715
Step 1660/2715
Step 1661/2715
Step 1662/2715
Step 1663/2715
Step 1664/2715
Step 1665/2715
Step 1666/2715
Step 1667/2715
Step 1668/2715
Step 1669/2715
Step 1670/2715
Step 1671/2715
Step 1672/2715
Step 1673/2715
Step 1674/2715
Step 1675/2715
Step 1676/2715
Step 1677/2715
Step 1678/2715
Step 1679/2715
Step 1680/2715
Step 1681/2715
Step 1682/2715
Step 1683/2715
Step 1684/2715
Step 1685/2715
Step 1686/2715
Step 1687/2715
Step 1688/2715
Step 1689/2715
Step 1690/2715
Step 1691/2715
Step 1692/2715
Step 1693/2715
Step 1694/2715
Step 1695/2715
Step 1696/2715
Step 1697/2715
Step 1698/2715
Step 1699/2715
Step 1700/2715
Step 1701/2715
Step 1702/2715
Step 1703/2715
Step 1704/2715
Step 1705/2715
Step 1706/2715
Step 1707/2715
Step 1708/2715
Step 1709/2715
Step 1710/2715
Step 1711/2715
Step 1712/2715
Step 1713/2715
Step 1714/2715
Step 1715/2715
Step 1716/2715
Step 1717/2715
Step 1718/2715
Step 1719/2715
Step 1720/2715
Step 1721/2715
Step 1722/2715
Step 1723/2715
Step 1724/2715
Step 1725/2715
Step 1726/2715
Step 1727/2715
Step 1728/2715
Step 1729/2715
Step 1730/2715
Step 1731/2715
Step 1732/2715
Step 1733/2715
Step 1734/2715
Step 1735/2715
Step 1736/2715
Step 1737/2715
Step 1738/2715
Step 1739/2715
Step 1740/2715
Step 1741/2715
Step 1742/2715
Step 1743/2715
Step 1744/2715
Step 1745/2715
Step 1746/2715
Step 1747/2715
Step 1748/2715
Step 1749/2715
Step 1750/2715
Step 1751/2715
Step 1752/2715
Step 1753/2715
Step 1754/2715
Step 1755/2715
Step 1756/2715
Step 1757/2715
Step 1758/2715
Step 1759/2715
Step 1760/2715
Step 1761/2715
Step 1762/2715
Step 1763/2715
Step 1764/2715
Step 1765/2715
Step 1766/2715
Step 1767/2715
Step 1768/2715
Step 1769/2715
Step 1770/2715
Step 1771/2715
Step 1772/2715
Step 1773/2715
Step 1774/2715
Step 1775/2715
Step 1776/2715
Step 1777/2715
Step 1778/2715
Step 1779/2715
Step 1780/2715
Step 1781/2715
Step 1782/2715
Step 1783/2715
Step 1784/2715
Step 1785/2715
Step 1786/2715
Step 1787/2715
Step 1788/2715
Step 1789/2715
Step 1790/2715
Step 1791/2715
Step 1792/2715
Step 1793/2715
Step 1794/2715
Step 1795/2715
Step 1796/2715
Step 1797/2715
Step 1798/2715
Step 1799/2715
Step 1800/2715
Step 1801/2715
Step 1802/2715
Step 1803/2715
Step 1804/2715
Step 1805/2715
Step 1806/2715
Step 1807/2715
Step 1808/2715
Step 1809/2715
Step 1810/2715
Step 1811/2715
Step 1812/2715
Step 1813/2715
Step 1814/2715
Step 1815/2715
Step 1816/2715
Step 1817/2715
Step 1818/2715
Step 1819/2715
Step 1820/2715
Step 1821/2715
Step 1822/2715
Step 1823/2715
Step 1824/2715
Step 1825/2715
Step 1826/2715
Step 1827/2715
Step 1828/2715
Step 1829/2715
Step 1830/2715
Step 1831/2715
Step 1832/2715
Step 1833/2715
Step 1834/2715
Step 1835/2715
Step 1836/2715
Step 1837/2715
Step 1838/2715
Step 1839/2715
Step 1840/2715
Step 1841/2715
Step 1842/2715
Step 1843/2715
Step 1844/2715
Step 1845/2715
Step 1846/2715
Step 1847/2715
Step 1848/2715
Step 1849/2715
Step 1850/2715
Step 1851/2715
Step 1852/2715
Step 1853/2715
Step 1854/2715
Step 1855/2715
Step 1856/2715
Step 1857/2715
Step 1858/2715
Step 1859/2715
Step 1860/2715
Step 1861/2715
Step 1862/2715
Step 1863/2715
Step 1864/2715
Step 1865/2715
Step 1866/2715
Step 1867/2715
Step 1868/2715
Step 1869/2715
Step 1870/2715
Step 1871/2715
Step 1872/2715
Step 1873/2715
Step 1874/2715
Step 1875/2715
Step 1876/2715
Step 1877/2715
Step 1878/2715
Step 1879/2715
Step 1880/2715
Step 1881/2715
Step 1882/2715
Step 1883/2715
Step 1884/2715
Step 1885/2715
Step 1886/2715
Step 1887/2715
Step 1888/2715
Step 1889/2715
Step 1890/2715
Step 1891/2715
Step 1892/2715
Step 1893/2715
Step 1894/2715
Step 1895/2715
Step 1896/2715
Step 1897/2715
Step 1898/2715
Step 1899/2715
Step 1900/2715
Step 1901/2715
Step 1902/2715
Step 1903/2715
Step 1904/2715
Step 1905/2715
Step 1906/2715
Step 1907/2715
Step 1908/2715
Step 1909/2715
Step 1910/2715
Step 1911/2715
Step 1912/2715
Step 1913/2715
Step 1914/2715
Step 1915/2715
Step 1916/2715
Step 1917/2715
Step 1918/2715
Step 1919/2715
Step 1920/2715
Step 1921/2715
Step 1922/2715
Step 1923/2715
Step 1924/2715
Step 1925/2715
Step 1926/2715
Step 1927/2715
Step 1928/2715
Step 1929/2715
Step 1930/2715
Step 1931/2715
Step 1932/2715
Step 1933/2715
Step 1934/2715
Step 1935/2715
Step 1936/2715
Step 1937/2715
Step 1938/2715
Step 1939/2715
Step 1940/2715
Step 1941/2715
Step 1942/2715
Step 1943/2715
Step 1944/2715
Step 1945/2715
Step 1946/2715
Step 1947/2715
Step 1948/2715
Step 1949/2715
Step 1950/2715
Step 1951/2715
Step 1952/2715
Step 1953/2715
Step 1954/2715
Step 1955/2715
Step 1956/2715
Step 1957/2715
Step 1958/2715
Step 1959/2715
Step 1960/2715
Step 1961/2715
Step 1962/2715
Step 1963/2715
Step 1964/2715
Step 1965/2715
Step 1966/2715
Step 1967/2715
Step 1968/2715
Step 1969/2715
Step 1970/2715
Step 1971/2715
Step 1972/2715
Step 1973/2715
Step 1974/2715
Step 1975/2715
Step 1976/2715
Step 1977/2715
Step 1978/2715
Step 1979/2715
Step 1980/2715
Step 1981/2715
Step 1982/2715
Step 1983/2715
Step 1984/2715
Step 1985/2715
Step 1986/2715
Step 1987/2715
Step 1988/2715
Step 1989/2715
Step 1990/2715
Step 1991/2715
Step 1992/2715
Step 1993/2715
Step 1994/2715
Step 1995/2715
Step 1996/2715
Step 1997/2715
Step 1998/2715
Step 1999/2715
Step 2000/2715
Step 2001/2715
Step 2002/2715
Step 2003/2715
Step 2004/2715
Step 2005/2715
Step 2006/2715
Step 2007/2715
Step 2008/2715
Step 2009/2715
Step 2010/2715
Step 2011/2715
Step 2012/2715
Step 2013/2715
Step 2014/2715
Step 2015/2715
Step 2016/2715
Step 2017/2715
Step 2018/2715
Step 2019/2715
Step 2020/2715
Step 2021/2715
Step 2022/2715
Step 2023/2715
Step 2024/2715
Step 2025/2715
Step 2026/2715
Step 2027/2715
Step 2028/2715
Step 2029/2715
Step 2030/2715
Step 2031/2715
Step 2032/2715
Step 2033/2715
Step 2034/2715
Step 2035/2715
Step 2036/2715
Step 2037/2715
Step 2038/2715
Step 2039/2715
Step 2040/2715
Step 2041/2715
Step 2042/2715
Step 2043/2715
Step 2044/2715
Step 2045/2715
Step 2046/2715
Step 2047/2715
Step 2048/2715
Step 2049/2715
Step 2050/2715
Step 2051/2715
Step 2052/2715
Step 2053/2715
Step 2054/2715
Step 2055/2715
Step 2056/2715
Step 2057/2715
Step 2058/2715
Step 2059/2715
Step 2060/2715
Step 2061/2715
Step 2062/2715
Step 2063/2715
Step 2064/2715
Step 2065/2715
Step 2066/2715
Step 2067/2715
Step 2068/2715
Step 2069/2715
Step 2070/2715
Step 2071/2715
Step 2072/2715
Step 2073/2715
Step 2074/2715
Step 2075/2715
Step 2076/2715
Step 2077/2715
Step 2078/2715
Step 2079/2715
Step 2080/2715
Step 2081/2715
Step 2082/2715
Step 2083/2715
Step 2084/2715
Step 2085/2715
Step 2086/2715
Step 2087/2715
Step 2088/2715
Step 2089/2715
Step 2090/2715
Step 2091/2715
Step 2092/2715
Step 2093/2715
Step 2094/2715
Step 2095/2715
Step 2096/2715
Step 2097/2715
Step 2098/2715
Step 2099/2715
Step 2100/2715
Step 2101/2715
Step 2102/2715
Step 2103/2715
Step 2104/2715
Step 2105/2715
Step 2106/2715
Step 2107/2715
Step 2108/2715
Step 2109/2715
Step 2110/2715
Step 2111/2715
Step 2112/2715
Step 2113/2715
Step 2114/2715
Step 2115/2715
Step 2116/2715
Step 2117/2715
Step 2118/2715
Step 2119/2715
Step 2120/2715
Step 2121/2715
Step 2122/2715
Step 2123/2715
Step 2124/2715
Step 2125/2715
Step 2126/2715
Step 2127/2715
Step 2128/2715
Step 2129/2715
Step 2130/2715
Step 2131/2715
Step 2132/2715
Step 2133/2715
Step 2134/2715
Step 2135/2715
Step 2136/2715
Step 2137/2715
Step 2138/2715
Step 2139/2715
Step 2140/2715
Step 2141/2715
Step 2142/2715
Step 2143/2715
Step 2144/2715
Step 2145/2715
Step 2146/2715
Step 2147/2715
Step 2148/2715
Step 2149/2715
Step 2150/2715
Step 2151/2715
Step 2152/2715
Step 2153/2715
Step 2154/2715
Step 2155/2715
Step 2156/2715
Step 2157/2715
Step 2158/2715
Step 2159/2715
Step 2160/2715
Step 2161/2715
Step 2162/2715
Step 2163/2715
Step 2164/2715
Step 2165/2715
Step 2166/2715
Step 2167/2715
Step 2168/2715
Step 2169/2715
Step 2170/2715
Step 2171/2715
Step 2172/2715

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: llm_family, language, code, generator. If llm_family, language, code, generator are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 6906
  Batch size = 32
Saving model checkpoint to /kaggle/working/checkpoints_b/checkpoint-2172
Configuration saved in /kaggle/working/checkpoints_b/checkpoint-2172/config.json
Model weights saved in /kaggle/working/checkpoints_b/checkpoint-2172/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_b/checkpoint-2172/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_b/checkpoint-2172/special_tokens_map.json
Deleting older checkpoint [/kaggle/working/checkpoints_b/checkpoint-1086] due to args.save_total_limit

Step 2173/2715
Step 2174/2715
Step 2175/2715
Step 2176/2715
Step 2177/2715
Step 2178/2715
Step 2179/2715
Step 2180/2715
Step 2181/2715
Step 2182/2715
Step 2183/2715
Step 2184/2715
Step 2185/2715
Step 2186/2715
Step 2187/2715
Step 2188/2715
Step 2189/2715
Step 2190/2715
Step 2191/2715
Step 2192/2715
Step 2193/2715
Step 2194/2715
Step 2195/2715
Step 2196/2715
Step 2197/2715
Step 2198/2715
Step 2199/2715
Step 2200/2715
Step 2201/2715
Step 2202/2715
Step 2203/2715
Step 2204/2715
Step 2205/2715
Step 2206/2715
Step 2207/2715
Step 2208/2715
Step 2209/2715
Step 2210/2715
Step 2211/2715
Step 2212/2715
Step 2213/2715
Step 2214/2715
Step 2215/2715
Step 2216/2715
Step 2217/2715
Step 2218/2715
Step 2219/2715
Step 2220/2715
Step 2221/2715
Step 2222/2715
Step 2223/2715
Step 2224/2715
Step 2225/2715
Step 2226/2715
Step 2227/2715
Step 2228/2715
Step 2229/2715
Step 2230/2715
Step 2231/2715
Step 2232/2715
Step 2233/2715
Step 2234/2715
Step 2235/2715
Step 2236/2715
Step 2237/2715
Step 2238/2715
Step 2239/2715
Step 2240/2715
Step 2241/2715
Step 2242/2715
Step 2243/2715
Step 2244/2715
Step 2245/2715
Step 2246/2715
Step 2247/2715
Step 2248/2715
Step 2249/2715
Step 2250/2715
Step 2251/2715
Step 2252/2715
Step 2253/2715
Step 2254/2715
Step 2255/2715
Step 2256/2715
Step 2257/2715
Step 2258/2715
Step 2259/2715
Step 2260/2715
Step 2261/2715
Step 2262/2715
Step 2263/2715
Step 2264/2715
Step 2265/2715
Step 2266/2715
Step 2267/2715
Step 2268/2715
Step 2269/2715
Step 2270/2715
Step 2271/2715
Step 2272/2715
Step 2273/2715
Step 2274/2715
Step 2275/2715
Step 2276/2715
Step 2277/2715
Step 2278/2715
Step 2279/2715
Step 2280/2715
Step 2281/2715
Step 2282/2715
Step 2283/2715
Step 2284/2715
Step 2285/2715
Step 2286/2715
Step 2287/2715
Step 2288/2715
Step 2289/2715
Step 2290/2715
Step 2291/2715
Step 2292/2715
Step 2293/2715
Step 2294/2715
Step 2295/2715
Step 2296/2715
Step 2297/2715
Step 2298/2715
Step 2299/2715
Step 2300/2715
Step 2301/2715
Step 2302/2715
Step 2303/2715
Step 2304/2715
Step 2305/2715
Step 2306/2715
Step 2307/2715
Step 2308/2715
Step 2309/2715
Step 2310/2715
Step 2311/2715
Step 2312/2715
Step 2313/2715
Step 2314/2715
Step 2315/2715
Step 2316/2715
Step 2317/2715
Step 2318/2715
Step 2319/2715
Step 2320/2715
Step 2321/2715
Step 2322/2715
Step 2323/2715
Step 2324/2715
Step 2325/2715
Step 2326/2715
Step 2327/2715
Step 2328/2715
Step 2329/2715
Step 2330/2715
Step 2331/2715
Step 2332/2715
Step 2333/2715
Step 2334/2715
Step 2335/2715
Step 2336/2715
Step 2337/2715
Step 2338/2715
Step 2339/2715
Step 2340/2715
Step 2341/2715
Step 2342/2715
Step 2343/2715
Step 2344/2715
Step 2345/2715
Step 2346/2715
Step 2347/2715
Step 2348/2715
Step 2349/2715
Step 2350/2715
Step 2351/2715
Step 2352/2715
Step 2353/2715
Step 2354/2715
Step 2355/2715
Step 2356/2715
Step 2357/2715
Step 2358/2715
Step 2359/2715
Step 2360/2715
Step 2361/2715
Step 2362/2715
Step 2363/2715
Step 2364/2715
Step 2365/2715
Step 2366/2715
Step 2367/2715
Step 2368/2715
Step 2369/2715
Step 2370/2715
Step 2371/2715
Step 2372/2715
Step 2373/2715
Step 2374/2715
Step 2375/2715
Step 2376/2715
Step 2377/2715
Step 2378/2715
Step 2379/2715
Step 2380/2715
Step 2381/2715
Step 2382/2715
Step 2383/2715
Step 2384/2715
Step 2385/2715
Step 2386/2715
Step 2387/2715
Step 2388/2715
Step 2389/2715
Step 2390/2715
Step 2391/2715
Step 2392/2715
Step 2393/2715
Step 2394/2715
Step 2395/2715
Step 2396/2715
Step 2397/2715
Step 2398/2715
Step 2399/2715
Step 2400/2715
Step 2401/2715
Step 2402/2715
Step 2403/2715
Step 2404/2715
Step 2405/2715
Step 2406/2715
Step 2407/2715
Step 2408/2715
Step 2409/2715
Step 2410/2715
Step 2411/2715
Step 2412/2715
Step 2413/2715
Step 2414/2715
Step 2415/2715
Step 2416/2715
Step 2417/2715
Step 2418/2715
Step 2419/2715
Step 2420/2715
Step 2421/2715
Step 2422/2715
Step 2423/2715
Step 2424/2715
Step 2425/2715
Step 2426/2715
Step 2427/2715
Step 2428/2715
Step 2429/2715
Step 2430/2715
Step 2431/2715
Step 2432/2715
Step 2433/2715
Step 2434/2715
Step 2435/2715
Step 2436/2715
Step 2437/2715
Step 2438/2715
Step 2439/2715
Step 2440/2715
Step 2441/2715
Step 2442/2715
Step 2443/2715
Step 2444/2715
Step 2445/2715
Step 2446/2715
Step 2447/2715
Step 2448/2715
Step 2449/2715
Step 2450/2715
Step 2451/2715
Step 2452/2715
Step 2453/2715
Step 2454/2715
Step 2455/2715
Step 2456/2715
Step 2457/2715
Step 2458/2715
Step 2459/2715
Step 2460/2715
Step 2461/2715
Step 2462/2715
Step 2463/2715
Step 2464/2715
Step 2465/2715
Step 2466/2715
Step 2467/2715
Step 2468/2715
Step 2469/2715
Step 2470/2715
Step 2471/2715
Step 2472/2715
Step 2473/2715
Step 2474/2715
Step 2475/2715
Step 2476/2715
Step 2477/2715
Step 2478/2715
Step 2479/2715
Step 2480/2715
Step 2481/2715
Step 2482/2715
Step 2483/2715
Step 2484/2715
Step 2485/2715
Step 2486/2715
Step 2487/2715
Step 2488/2715
Step 2489/2715
Step 2490/2715
Step 2491/2715
Step 2492/2715
Step 2493/2715
Step 2494/2715
Step 2495/2715
Step 2496/2715
Step 2497/2715
Step 2498/2715
Step 2499/2715
Step 2500/2715
Step 2501/2715
Step 2502/2715
Step 2503/2715
Step 2504/2715
Step 2505/2715
Step 2506/2715
Step 2507/2715
Step 2508/2715
Step 2509/2715
Step 2510/2715
Step 2511/2715
Step 2512/2715
Step 2513/2715
Step 2514/2715
Step 2515/2715
Step 2516/2715
Step 2517/2715
Step 2518/2715
Step 2519/2715
Step 2520/2715
Step 2521/2715
Step 2522/2715
Step 2523/2715
Step 2524/2715
Step 2525/2715
Step 2526/2715
Step 2527/2715
Step 2528/2715
Step 2529/2715
Step 2530/2715
Step 2531/2715
Step 2532/2715
Step 2533/2715
Step 2534/2715
Step 2535/2715
Step 2536/2715
Step 2537/2715
Step 2538/2715
Step 2539/2715
Step 2540/2715
Step 2541/2715
Step 2542/2715
Step 2543/2715
Step 2544/2715
Step 2545/2715
Step 2546/2715
Step 2547/2715
Step 2548/2715
Step 2549/2715
Step 2550/2715
Step 2551/2715
Step 2552/2715
Step 2553/2715
Step 2554/2715
Step 2555/2715
Step 2556/2715
Step 2557/2715
Step 2558/2715
Step 2559/2715
Step 2560/2715
Step 2561/2715
Step 2562/2715
Step 2563/2715
Step 2564/2715
Step 2565/2715
Step 2566/2715
Step 2567/2715
Step 2568/2715
Step 2569/2715
Step 2570/2715
Step 2571/2715
Step 2572/2715
Step 2573/2715
Step 2574/2715
Step 2575/2715
Step 2576/2715
Step 2577/2715
Step 2578/2715
Step 2579/2715
Step 2580/2715
Step 2581/2715
Step 2582/2715
Step 2583/2715
Step 2584/2715
Step 2585/2715
Step 2586/2715
Step 2587/2715
Step 2588/2715
Step 2589/2715
Step 2590/2715
Step 2591/2715
Step 2592/2715
Step 2593/2715
Step 2594/2715
Step 2595/2715
Step 2596/2715
Step 2597/2715
Step 2598/2715
Step 2599/2715
Step 2600/2715
Step 2601/2715
Step 2602/2715
Step 2603/2715
Step 2604/2715
Step 2605/2715
Step 2606/2715
Step 2607/2715
Step 2608/2715
Step 2609/2715
Step 2610/2715
Step 2611/2715
Step 2612/2715
Step 2613/2715
Step 2614/2715
Step 2615/2715
Step 2616/2715
Step 2617/2715
Step 2618/2715
Step 2619/2715
Step 2620/2715
Step 2621/2715
Step 2622/2715
Step 2623/2715
Step 2624/2715
Step 2625/2715
Step 2626/2715
Step 2627/2715
Step 2628/2715
Step 2629/2715
Step 2630/2715
Step 2631/2715
Step 2632/2715
Step 2633/2715
Step 2634/2715
Step 2635/2715
Step 2636/2715
Step 2637/2715
Step 2638/2715
Step 2639/2715
Step 2640/2715
Step 2641/2715
Step 2642/2715
Step 2643/2715
Step 2644/2715
Step 2645/2715
Step 2646/2715
Step 2647/2715
Step 2648/2715
Step 2649/2715
Step 2650/2715
Step 2651/2715
Step 2652/2715
Step 2653/2715
Step 2654/2715
Step 2655/2715
Step 2656/2715
Step 2657/2715
Step 2658/2715
Step 2659/2715
Step 2660/2715
Step 2661/2715
Step 2662/2715
Step 2663/2715
Step 2664/2715
Step 2665/2715
Step 2666/2715
Step 2667/2715
Step 2668/2715
Step 2669/2715
Step 2670/2715
Step 2671/2715
Step 2672/2715
Step 2673/2715
Step 2674/2715
Step 2675/2715
Step 2676/2715
Step 2677/2715
Step 2678/2715
Step 2679/2715
Step 2680/2715
Step 2681/2715
Step 2682/2715
Step 2683/2715
Step 2684/2715
Step 2685/2715
Step 2686/2715
Step 2687/2715
Step 2688/2715
Step 2689/2715
Step 2690/2715
Step 2691/2715
Step 2692/2715
Step 2693/2715
Step 2694/2715
Step 2695/2715
Step 2696/2715
Step 2697/2715
Step 2698/2715
Step 2699/2715
Step 2700/2715
Step 2701/2715
Step 2702/2715
Step 2703/2715
Step 2704/2715
Step 2705/2715
Step 2706/2715
Step 2707/2715
Step 2708/2715
Step 2709/2715
Step 2710/2715
Step 2711/2715
Step 2712/2715
Step 2713/2715
Step 2714/2715
Step 2715/2715

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: llm_family, language, code, generator. If llm_family, language, code, generator are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 6906
  Batch size = 32
Saving model checkpoint to /kaggle/working/checkpoints_b/checkpoint-2715
Configuration saved in /kaggle/working/checkpoints_b/checkpoint-2715/config.json
Model weights saved in /kaggle/working/checkpoints_b/checkpoint-2715/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_b/checkpoint-2715/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_b/checkpoint-2715/special_tokens_map.json
Deleting older checkpoint [/kaggle/working/checkpoints_b/checkpoint-1629] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from /kaggle/working/checkpoints_b/checkpoint-2172 (score: 0.3797908745003944).

TrainOutput(global_step=2715, training_loss=1.3447720634783609, metrics={'train_runtime': 1963.275, 'train_samples_per_second': 88.48, 'train_steps_per_second': 1.383, 'total_flos': 1.714061413580544e+16, 'train_loss': 1.3447720634783609, 'epoch': 5.0})

In [58]:
with open("taskb_training_results.pkl", "wb") as f:
    pickle.dump(llm_trainer.state.log_history, f)

In [82]:
binary_trainer.save_model("/kaggle/working/final_binary_model")
llm_trainer.save_model("/kaggle/working/final_llm_model")
tokenizer.save_pretrained("/kaggle/working/final_tokenizer")

Saving model checkpoint to /kaggle/working/final_binary_model
Configuration saved in /kaggle/working/final_binary_model/config.json
Model weights saved in /kaggle/working/final_binary_model/model.safetensors
tokenizer config file saved in /kaggle/working/final_binary_model/tokenizer_config.json
Special tokens file saved in /kaggle/working/final_binary_model/special_tokens_map.json
Saving model checkpoint to /kaggle/working/final_llm_model
Configuration saved in /kaggle/working/final_llm_model/config.json
Model weights saved in /kaggle/working/final_llm_model/model.safetensors
tokenizer config file saved in /kaggle/working/final_llm_model/tokenizer_config.json
Special tokens file saved in /kaggle/working/final_llm_model/special_tokens_map.json
tokenizer config file saved in /kaggle/working/final_tokenizer/tokenizer_config.json
Special tokens file saved in /kaggle/working/final_tokenizer/special_tokens_map.json

('/kaggle/working/final_tokenizer/tokenizer_config.json',
 '/kaggle/working/final_tokenizer/special_tokens_map.json',
 '/kaggle/working/final_tokenizer/vocab.json',
 '/kaggle/working/final_tokenizer/merges.txt',
 '/kaggle/working/final_tokenizer/added_tokens.json',
 '/kaggle/working/final_tokenizer/tokenizer.json')

In [75]:
def tokenize_test_set(examples: pd.DataFrame):
    tokenizer(
        text_target=examples["code"],
        truncation=True,
        max_length=MAX_LENGTH
    )

In [80]:
test_full_dataset = Dataset.from_pandas(test_full_df, preserve_index=False)

test_full_tokenized_set = test_full_dataset.map(tokenize_test_set, batched=True)

test_full_tokenized_set.set_format(
    type="torch",
    columns=["input_ids", "attention_mask"]
)

Map:   0%|          | 0/500000 [00:00<?, ? examples/s]

ValueError: Columns ['input_ids', 'attention_mask'] not in the dataset. Current columns in the dataset: ['ID', 'code']

In [81]:
binary_evaluation = binary_trainer.evaluate(test_full_tokenized_set)
print("Evaluation for task A: ", binary_evaluation)

binary_preds = np.argmax(
    binary_trainer.predict(test_full_tokenized_set).predictions, axis=1
)

llm_evaluation = llm_trainer.evaluate(test_full_tokenized_set)
print("Evaluation for task B: ", llm_evaluation)

llm_preds = np.argmax(
    llm_trainer.predict(test_full_tokenized_set).predictions, axis=1
)

final_preds = []
llm_index = 0
for p in binary_preds:
    if p == 0:
        final_preds.append("Human")
    else:
        final_preds.append(id2label[llm_preds[llm_index]])
        llm_index += 1

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: ID, code. If ID, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

ValueError: No columns in the dataset match the model's forward method signature: (input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict, labels, label, label_ids). The following columns have been ignored: [ID, code]. Please check the dataset and model. You may need to set `remove_unused_columns=False` in `TrainingArguments`.

In [63]:
pd.DataFrame({
    "ID": test_df["ID"],
    "label": binary_preds
}).to_csv("taskA_predictions.csv", index=False)

pd.DataFrame({
    "ID": test_df["ID"],
    "label": final_preds
}).to_csv("taskB_predictions.csv", index=False)