In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
print("start")

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [1]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("Visible GPUs:", torch.cuda.device_count())
print("GPU name:", torch.cuda.get_device_name(0))

CUDA available: True
Visible GPUs: 2
GPU name: Tesla T4

In [3]:
!pip uninstall -y protobuf
!pip install protobuf==3.20.3

Found existing installation: protobuf 5.29.5
Uninstalling protobuf-5.29.5:
  Successfully uninstalled protobuf-5.29.5
Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-py2.py3-none-any.whl.metadata (720 bytes)
Downloading protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 4.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: protobuf
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.26.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
grain 0.2.15 requires protobuf>=5.28.3, but you have protobuf 3.20.3 which is incompatible.
onnx 1.20.0 requires protobuf>=4.25.1, but you have protobuf 3.20.3 which is incompatible.
ray 2.52.1 requires click!=8.3.*,>=7.0, but you have click 8.3.1 which is incompatible.
opentelemetry-proto 1.37.0 requires protobuf<7.0,>=5.0, but you have protobuf 3.20.3 which is incompatible.
tensorflow-metadata 1.17.2 requires protobuf>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.3 which is incompatible.
ydf 0.13.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 3.20.3 which is incompatible.
bigframes 2.26.0 requires rich<14,>=12.4.4, but you have rich 14.2.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 3.20.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.10.0 which is incompatible.
Successfully installed protobuf-3.20.3

In [2]:
import os
import numpy as np
import pandas as pd
import torch
import transformers

from datasets import Dataset
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    EarlyStoppingCallback,
    TrainingArguments,
    Trainer,
    logging
)

path = "/kaggle/working/state.db"
if os.path.exists(path):
    os.remove(path)
    print("state.db deleted")
else:
    print("state.db not found")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    macro_f1 = f1_score(labels, predictions, average="binary")
    accuracy = accuracy_score(labels, predictions)
    precision = precision_score(labels, predictions, average="binary")
    recall = recall_score(labels, predictions, average="binary")

    return {
        "macro_f1": macro_f1,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall
    }

base_path = "/kaggle/input/sem-eval-2026-task-13-subtask-a/Task_A"

training_path = base_path + "/train.parquet"
validation_path = base_path + "/validation.parquet"
test_sample_path = base_path + "/test_sample.parquet"
test_path = base_path + "/test.parquet"
sample_sub_path = base_path + "/sample_submission.csv"

training_df = pd.read_parquet(training_path)
validation_df = pd.read_parquet(validation_path)
test_sample_df = pd.read_parquet(test_sample_path)
test_df = pd.read_parquet(test_path)
sample_sub_df = pd.read_csv(sample_sub_path)

for df in [training_df, validation_df, test_sample_df, test_df]:
    if "__index_level_0__" in df.columns:
        df.drop(columns=["__index_level_0__"], inplace=True)

print("Loaded shapes:")
print("train:", training_df.shape)
print("val:", validation_df.shape)
print("test:", test_df.shape)
print("test_sample:", test_sample_df.shape)
print("sample_submission:", sample_sub_df.shape)

test_sample_merged = pd.merge(test_df, test_sample_df, on="code", how="inner")
print("test_sample_merged:", test_sample_merged.shape)

pretrained_model = "microsoft/unixcoder-base"
tokenizer = AutoTokenizer.from_pretrained(pretrained_model)

def preprocess_function(examples):
    return tokenizer(examples["code"], truncation=True, max_length=256)

training_dataset = Dataset.from_pandas(training_df)
validation_dataset = Dataset.from_pandas(validation_df)
test_dataset = Dataset.from_pandas(test_df)
test_sample_merged_dataset = Dataset.from_pandas(test_sample_merged)

training_tokenized_set = training_dataset.map(preprocess_function, batched=True)
validation_tokenized_set = validation_dataset.map(preprocess_function, batched=True)
test_tokenized_set = test_dataset.map(preprocess_function, batched=True)
test_sample_merged_tokenized_set = test_sample_merged_dataset.map(preprocess_function, batched=True)

training_tokenized_set.set_format("torch")
validation_tokenized_set.set_format("torch")
test_tokenized_set.set_format("torch")
test_sample_merged_tokenized_set.set_format("torch")

model = AutoModelForSequenceClassification.from_pretrained(
    pretrained_model,
    num_labels=2
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
print("\nRunning on device:", device)

logging.set_verbosity_info()

class TrainingProgressCallback(transformers.TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        if state.is_local_process_zero:
            print(f"Step {state.global_step}/{state.max_steps}")

OUTPUT_DIR = "/kaggle/working/checkpoints_task_a"
LOG_DIR = "/kaggle/working/logs_task_a"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    seed=42,
    learning_rate=3e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    num_train_epochs=3,
    weight_decay=0.01,
    warmup_ratio=0.1,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    metric_for_best_model="macro_f1",
    load_best_model_at_end=True,
    logging_dir=LOG_DIR,
    logging_steps=3000,
    fp16=True,
    disable_tqdm=False,
    ddp_find_unused_parameters=False,
    dataloader_num_workers=0,
    no_cuda=False,
    report_to=[]
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=training_tokenized_set,
    eval_dataset=validation_tokenized_set,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2),
               TrainingProgressCallback()]
)

resume = False
if os.path.isdir(OUTPUT_DIR):
    from transformers.trainer_utils import get_last_checkpoint
    last_ckpt = get_last_checkpoint(OUTPUT_DIR)
    if last_ckpt is not None:
        resume = True
        print("Found checkpoint:", last_ckpt)

if resume:
    trainer.train(resume_from_checkpoint=last_ckpt)
else:
    trainer.train()

print("Eval on validation:", trainer.evaluate(validation_tokenized_set))
print("Eval on test_sample_merged (labeled subset):", trainer.evaluate(test_sample_merged_tokenized_set))

predictions = trainer.predict(test_tokenized_set)
logits = predictions.predictions
predicted_labels = np.argmax(logits, axis=1).astype(int)

pred_df = pd.DataFrame({
    "ID": test_df["ID"].values,
    "label": predicted_labels
})

submission_df = sample_sub_df[["ID"]].merge(pred_df, on="ID", how="left")
missing = submission_df["label"].isna().sum()
print("Missing labels after merge:", missing)
submission_df["label"] = submission_df["label"].fillna(0).astype(int)

out_path = "/kaggle/working/submission.csv"
submission_df.to_csv(out_path, index=False)
print("Saved:", out_path)
submission_df.head()

2026-01-04 00:35:22.978910: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1767486923.452550      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1767486923.592038      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1767486924.835958      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1767486924.836006      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1767486924.836009      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1767486924.836011      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

state.db not found
Loaded shapes:
train: (500000, 4)
val: (100000, 4)
test: (1000, 2)
test_sample: (1000, 4)
sample_submission: (1000, 2)
test_sample_merged: (1000, 5)

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Map:   0%|          | 0/500000 [00:00<?, ? examples/s]

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/691 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/504M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at microsoft/unixcoder-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/504M [00:00<?, ?B/s]

PyTorch: setting up devices
Using auto half precision backend
Loading model from /kaggle/working/checkpoints_task_a/checkpoint-31250.

Running on device: cuda
Found checkpoint: /kaggle/working/checkpoints_task_a/checkpoint-31250

The following columns in the Training set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: language, generator, code. If language, generator, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 500,000
  Num Epochs = 3
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 2
  Total optimization steps = 93,750
  Number of trainable parameters = 125,931,266
Warning: The following arguments do not match the ones in the `trainer_state.json` within the checkpoint directory:
	per_device_train_batch_size: 8 (from args) != 4 (from trainer_state.json)
  Continuing training from checkpoint, will skip to saved global_step
  Continuing training from epoch 1
  Continuing training from global step 31250
  Will skip the first 1 epochs then the first 0 batches in the first epoch.
/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

Step 31251/93750

Step 31252/93750
Step 31253/93750
Step 31254/93750
Step 31255/93750
Step 31256/93750
Step 31257/93750
Step 31258/93750
Step 31259/93750
Step 31260/93750
Step 31261/93750
Step 31262/93750
Step 31263/93750
Step 31264/93750
Step 31265/93750
Step 31266/93750
Step 31267/93750
Step 31268/93750
Step 31269/93750
Step 31270/93750
Step 31271/93750
Step 31272/93750
Step 31273/93750
Step 31274/93750
Step 31275/93750
Step 31276/93750
Step 31277/93750
Step 31278/93750
Step 31279/93750
Step 31280/93750
Step 31281/93750
Step 31282/93750
Step 31283/93750
Step 31284/93750
Step 31285/93750
Step 31286/93750
Step 31287/93750
Step 31288/93750
Step 31289/93750
Step 31290/93750
Step 31291/93750
Step 31292/93750
Step 31293/93750
Step 31294/93750
Step 31295/93750
Step 31296/93750
Step 31297/93750
Step 31298/93750
Step 31299/93750
Step 31300/93750
Step 31301/93750
Step 31302/93750
Step 31303/93750
Step 31304/93750
Step 31305/93750
Step 31306/93750
Step 31307/93750
Step 31308/93750
Step 31309/93750
Step 31310/93750
Step 31311/93750
Step 31312/93750
Step 31313/93750
Step 31314/93750
Step 31315/93750
Step 31316/93750
Step 31317/93750
Step 31318/93750
Step 31319/93750
Step 31320/93750
Step 31321/93750
Step 31322/93750
Step 31323/93750
Step 31324/93750
Step 31325/93750
Step 31326/93750
Step 31327/93750
Step 31328/93750
Step 31329/93750
Step 31330/93750
Step 31331/93750
Step 31332/93750
Step 31333/93750
Step 31334/93750
Step 31335/93750
Step 31336/93750
Step 31337/93750
Step 31338/93750
Step 31339/93750
Step 31340/93750
Step 31341/93750
Step 31342/93750
Step 31343/93750
Step 31344/93750
Step 31345/93750
Step 31346/93750
Step 31347/93750
Step 31348/93750
Step 31349/93750
Step 31350/93750
Step 31351/93750
Step 31352/93750
Step 31353/93750
Step 31354/93750
Step 31355/93750
Step 31356/93750
Step 31357/93750
Step 31358/93750
Step 31359/93750
Step 31360/93750
Step 31361/93750
Step 31362/93750
Step 31363/93750
Step 31364/93750
Step 31365/93750
Step 31366/93750
Step 31367/93750
Step 31368/93750
Step 31369/93750
Step 31370/93750
Step 31371/93750
Step 31372/93750
Step 31373/93750
Step 31374/93750
Step 31375/93750
Step 31376/93750
Step 31377/93750
Step 31378/93750
Step 31379/93750
Step 31380/93750
Step 31381/93750
Step 31382/93750
Step 31383/93750
Step 31384/93750
Step 31385/93750
Step 31386/93750
Step 31387/93750
Step 31388/93750
Step 31389/93750
Step 31390/93750
Step 31391/93750
Step 31392/93750
Step 31393/93750
Step 31394/93750
Step 31395/93750
Step 31396/93750
Step 31397/93750
Step 31398/93750
Step 31399/93750
Step 31400/93750
Step 31401/93750
Step 31402/93750
Step 31403/93750
Step 31404/93750
Step 31405/93750
Step 31406/93750
Step 31407/93750
Step 31408/93750
Step 31409/93750
Step 31410/93750
Step 31411/93750
Step 31412/93750
Step 31413/93750
Step 31414/93750
Step 31415/93750
Step 31416/93750
Step 31417/93750
Step 31418/93750
Step 31419/93750
Step 31420/93750
Step 31421/93750
Step 31422/93750
Step 31423/93750
Step 31424/93750
Step 31425/93750
Step 31426/93750
Step 31427/93750
Step 31428/93750
Step 31429/93750
Step 31430/93750
Step 31431/93750
Step 31432/93750
Step 31433/93750
Step 31434/93750
Step 31435/93750
Step 31436/93750
Step 31437/93750
Step 31438/93750
Step 31439/93750
Step 31440/93750
Step 31441/93750
Step 31442/93750
Step 31443/93750
Step 31444/93750
Step 31445/93750
Step 31446/93750
Step 31447/93750
Step 31448/93750
Step 31449/93750
Step 31450/93750
Step 31451/93750
Step 31452/93750
Step 31453/93750
Step 31454/93750
Step 31455/93750
Step 31456/93750
Step 31457/93750
Step 31458/93750
Step 31459/93750
Step 31460/93750
Step 31461/93750
Step 31462/93750
Step 31463/93750
Step 31464/93750
Step 31465/93750
Step 31466/93750
Step 31467/93750
Step 31468/93750
Step 31469/93750
Step 31470/93750
Step 31471/93750
Step 31472/93750
Step 31473/93750
Step 31474/93750
Step 31475/93750
Step 31476/93750
Step 31477/93750
Step 31478/93750
Step 31479/93750
Step 31480/93750
Step 31481/93750
Step 31482/93750
Step 31483/93750
Step 31484/93750
Step 31485/93750
Step 31486/93750
Step 31487/93750
Step 31488/93750
Step 31489/93750
Step 31490/93750
Step 31491/93750
Step 31492/93750
Step 31493/93750
Step 31494/93750
Step 31495/93750
Step 31496/93750
Step 31497/93750
Step 31498/93750
Step 31499/93750
Step 31500/93750
Step 31501/93750
Step 31502/93750
Step 31503/93750
Step 31504/93750
Step 31505/93750
Step 31506/93750
Step 31507/93750
Step 31508/93750
Step 31509/93750
Step 31510/93750
Step 31511/93750
Step 31512/93750
Step 31513/93750
Step 31514/93750
Step 31515/93750
Step 31516/93750
Step 31517/93750
Step 31518/93750
Step 31519/93750
Step 31520/93750
Step 31521/93750
Step 31522/93750
Step 31523/93750
Step 31524/93750
Step 31525/93750
Step 31526/93750
Step 31527/93750
Step 31528/93750
Step 31529/93750
Step 31530/93750
Step 31531/93750
Step 31532/93750
Step 31533/93750
Step 31534/93750
Step 31535/93750
Step 31536/93750
Step 31537/93750
Step 31538/93750
Step 31539/93750
Step 31540/93750
Step 31541/93750
Step 31542/93750
Step 31543/93750
Step 31544/93750
Step 31545/93750
Step 31546/93750
Step 31547/93750
Step 31548/93750
Step 31549/93750
Step 31550/93750
Step 31551/93750
Step 31552/93750
Step 31553/93750
Step 31554/93750
Step 31555/93750
Step 31556/93750
Step 31557/93750
Step 31558/93750
Step 31559/93750
Step 31560/93750
Step 31561/93750
Step 31562/93750
Step 31563/93750
Step 31564/93750
Step 31565/93750
Step 31566/93750
Step 31567/93750
Step 31568/93750
Step 31569/93750
Step 31570/93750
Step 31571/93750
Step 31572/93750
Step 31573/93750
Step 31574/93750
Step 31575/93750
Step 31576/93750
Step 31577/93750
Step 31578/93750
Step 31579/93750
Step 31580/93750
Step 31581/93750
Step 31582/93750
Step 31583/93750
Step 31584/93750
Step 31585/93750
Step 31586/93750
Step 31587/93750
Step 31588/93750
Step 31589/93750
Step 31590/93750
Step 31591/93750
Step 31592/93750
Step 31593/93750
Step 31594/93750
Step 31595/93750
Step 31596/93750
Step 31597/93750
Step 31598/93750
Step 31599/93750
Step 31600/93750
Step 31601/93750
Step 31602/93750
Step 31603/93750
Step 31604/93750
Step 31605/93750
Step 31606/93750
Step 31607/93750
Step 31608/93750
Step 31609/93750
Step 31610/93750
Step 31611/93750
Step 31612/93750
Step 31613/93750
Step 31614/93750
Step 31615/93750
Step 31616/93750
Step 31617/93750
Step 31618/93750
Step 31619/93750
Step 31620/93750
Step 31621/93750
Step 31622/93750
Step 31623/93750
Step 31624/93750
Step 31625/93750
Step 31626/93750
Step 31627/93750
Step 31628/93750
Step 31629/93750
Step 31630/93750
Step 31631/93750
Step 31632/93750
Step 31633/93750
Step 31634/93750
Step 31635/93750
Step 31636/93750
Step 31637/93750
Step 31638/93750
Step 31639/93750
Step 31640/93750
Step 31641/93750
Step 31642/93750
Step 31643/93750
Step 31644/93750
Step 31645/93750
Step 31646/93750
Step 31647/93750
Step 31648/93750
Step 31649/93750
Step 31650/93750
Step 31651/93750
Step 31652/93750
Step 31653/93750
Step 31654/93750
Step 31655/93750
Step 31656/93750
Step 31657/93750
Step 31658/93750
Step 31659/93750
Step 31660/93750
Step 31661/93750
Step 31662/93750
Step 31663/93750
Step 31664/93750
Step 31665/93750
Step 31666/93750
Step 31667/93750
Step 31668/93750
Step 31669/93750
Step 31670/93750
Step 31671/93750
Step 31672/93750
Step 31673/93750
Step 31674/93750
Step 31675/93750
Step 31676/93750
Step 31677/93750
Step 31678/93750
Step 31679/93750
Step 31680/93750
Step 31681/93750
Step 31682/93750
Step 31683/93750
Step 31684/93750
Step 31685/93750
Step 31686/93750
Step 31687/93750
Step 31688/93750
Step 31689/93750
Step 31690/93750
Step 31691/93750
Step 31692/93750
Step 31693/93750
Step 31694/93750
Step 31695/93750
Step 31696/93750
Step 31697/93750
Step 31698/93750
Step 31699/93750
Step 31700/93750
Step 31701/93750
Step 31702/93750
Step 31703/93750
Step 31704/93750
Step 31705/93750
Step 31706/93750
Step 31707/93750
Step 31708/93750
Step 31709/93750
Step 31710/93750
Step 31711/93750
Step 31712/93750
Step 31713/93750
Step 31714/93750
Step 31715/93750
Step 31716/93750
Step 31717/93750
Step 31718/93750
Step 31719/93750
Step 31720/93750
Step 31721/93750
Step 31722/93750
Step 31723/93750
Step 31724/93750
Step 31725/93750
Step 31726/93750
Step 31727/93750
Step 31728/93750
Step 31729/93750
Step 31730/93750
Step 31731/93750
Step 31732/93750
Step 31733/93750
Step 31734/93750
Step 31735/93750
Step 31736/93750
Step 31737/93750
Step 31738/93750
Step 31739/93750
Step 31740/93750
Step 31741/93750
Step 31742/93750
Step 31743/93750
Step 31744/93750
Step 31745/93750
Step 31746/93750
Step 31747/93750
Step 31748/93750
Step 31749/93750
Step 31750/93750
Step 31751/93750
Step 31752/93750
Step 31753/93750
Step 31754/93750
Step 31755/93750
Step 31756/93750
Step 31757/93750
Step 31758/93750
Step 31759/93750
Step 31760/93750
Step 31761/93750
Step 31762/93750
Step 31763/93750
Step 31764/93750
Step 31765/93750
Step 31766/93750
Step 31767/93750
Step 31768/93750
Step 31769/93750
Step 31770/93750
Step 31771/93750
Step 31772/93750
Step 31773/93750
Step 31774/93750
Step 31775/93750
Step 31776/93750
Step 31777/93750
Step 31778/93750
Step 31779/93750
Step 31780/93750
Step 31781/93750
Step 31782/93750
Step 31783/93750
Step 31784/93750
Step 31785/93750
Step 31786/93750
Step 31787/93750
Step 31788/93750
Step 31789/93750
Step 31790/93750
Step 31791/93750
Step 31792/93750
Step 31793/93750
Step 31794/93750
Step 31795/93750
Step 31796/93750
Step 31797/93750
Step 31798/93750
Step 31799/93750
Step 31800/93750
Step 31801/93750
Step 31802/93750
Step 31803/93750
Step 31804/93750
Step 31805/93750
Step 31806/93750
Step 31807/93750
Step 31808/93750
Step 31809/93750
Step 31810/93750
Step 31811/93750
Step 31812/93750
Step 31813/93750
Step 31814/93750
Step 31815/93750
Step 31816/93750
Step 31817/93750
Step 31818/93750
Step 31819/93750
Step 31820/93750
Step 31821/93750
Step 31822/93750
Step 31823/93750
Step 31824/93750
Step 31825/93750
Step 31826/93750
Step 31827/93750
Step 31828/93750
Step 31829/93750
Step 31830/93750
Step 31831/93750
Step 31832/93750
Step 31833/93750
Step 31834/93750
Step 31835/93750
Step 31836/93750
Step 31837/93750
Step 31838/93750
Step 31839/93750
Step 31840/93750
Step 31841/93750
Step 31842/93750
Step 31843/93750
Step 31844/93750
Step 31845/93750
Step 31846/93750
Step 31847/93750
Step 31848/93750
Step 31849/93750
Step 31850/93750
Step 31851/93750
Step 31852/93750
Step 31853/93750
Step 31854/93750
Step 31855/93750
Step 31856/93750
Step 31857/93750
Step 31858/93750
Step 31859/93750
Step 31860/93750
Step 31861/93750
Step 31862/93750
Step 31863/93750
Step 31864/93750
Step 31865/93750
Step 31866/93750
Step 31867/93750
Step 31868/93750
Step 31869/93750
Step 31870/93750
Step 31871/93750
Step 31872/93750
Step 31873/93750
Step 31874/93750
Step 31875/93750
Step 31876/93750
Step 31877/93750
Step 31878/93750
Step 31879/93750
Step 31880/93750
Step 31881/93750
Step 31882/93750
Step 31883/93750
Step 31884/93750
Step 31885/93750
Step 31886/93750
Step 31887/93750
Step 31888/93750
Step 31889/93750
Step 31890/93750
Step 31891/93750
Step 31892/93750
Step 31893/93750
Step 31894/93750
Step 31895/93750
Step 31896/93750
Step 31897/93750
Step 31898/93750
Step 31899/93750
Step 31900/93750
Step 31901/93750
Step 31902/93750
Step 31903/93750
Step 31904/93750
Step 31905/93750
Step 31906/93750
Step 31907/93750
Step 31908/93750
Step 31909/93750
Step 31910/93750
Step 31911/93750
Step 31912/93750
Step 31913/93750
Step 31914/93750
Step 31915/93750
Step 31916/93750
Step 31917/93750
Step 31918/93750
Step 31919/93750
Step 31920/93750
Step 31921/93750
Step 31922/93750
Step 31923/93750
Step 31924/93750
Step 31925/93750
Step 31926/93750
Step 31927/93750
Step 31928/93750
Step 31929/93750
Step 31930/93750
Step 31931/93750
Step 31932/93750
Step 31933/93750
Step 31934/93750
Step 31935/93750
Step 31936/93750
Step 31937/93750
Step 31938/93750
Step 31939/93750
Step 31940/93750
Step 31941/93750
Step 31942/93750
Step 31943/93750
Step 31944/93750
Step 31945/93750
Step 31946/93750
Step 31947/93750
Step 31948/93750
Step 31949/93750
Step 31950/93750
Step 31951/93750
Step 31952/93750
Step 31953/93750
Step 31954/93750
Step 31955/93750
Step 31956/93750
Step 31957/93750
Step 31958/93750
Step 31959/93750
Step 31960/93750
Step 31961/93750
Step 31962/93750
Step 31963/93750
Step 31964/93750
Step 31965/93750
Step 31966/93750
Step 31967/93750
Step 31968/93750
Step 31969/93750
Step 31970/93750
Step 31971/93750
Step 31972/93750
Step 31973/93750
Step 31974/93750
Step 31975/93750
Step 31976/93750
Step 31977/93750
Step 31978/93750
Step 31979/93750
Step 31980/93750
Step 31981/93750
Step 31982/93750
Step 31983/93750
Step 31984/93750
Step 31985/93750
Step 31986/93750
Step 31987/93750
Step 31988/93750
Step 31989/93750
Step 31990/93750
Step 31991/93750
Step 31992/93750
Step 31993/93750
Step 31994/93750
Step 31995/93750
Step 31996/93750
Step 31997/93750
Step 31998/93750
Step 31999/93750
Step 32000/93750
Step 32001/93750
Step 32002/93750
Step 32003/93750
Step 32004/93750
Step 32005/93750
Step 32006/93750
Step 32007/93750
Step 32008/93750
Step 32009/93750
Step 32010/93750
Step 32011/93750
Step 32012/93750
Step 32013/93750
Step 32014/93750
Step 32015/93750
Step 32016/93750
Step 32017/93750
Step 32018/93750
Step 32019/93750
Step 32020/93750
Step 32021/93750
Step 32022/93750
Step 32023/93750
Step 32024/93750
Step 32025/93750
Step 32026/93750
Step 32027/93750
Step 32028/93750
Step 32029/93750
Step 32030/93750
Step 32031/93750
Step 32032/93750
Step 32033/93750
Step 32034/93750
Step 32035/93750
Step 32036/93750
Step 32037/93750
Step 32038/93750
Step 32039/93750
Step 32040/93750
Step 32041/93750
Step 32042/93750
Step 32043/93750
Step 32044/93750
Step 32045/93750
Step 32046/93750
Step 32047/93750
Step 32048/93750
Step 32049/93750
Step 32050/93750
Step 32051/93750
Step 32052/93750
Step 32053/93750
Step 32054/93750
Step 32055/93750
Step 32056/93750
Step 32057/93750
Step 32058/93750
Step 32059/93750
Step 32060/93750
Step 32061/93750
Step 32062/93750
Step 32063/93750
Step 32064/93750
Step 32065/93750
Step 32066/93750
Step 32067/93750
Step 32068/93750
Step 32069/93750
Step 32070/93750
Step 32071/93750
Step 32072/93750
Step 32073/93750
Step 32074/93750
Step 32075/93750
Step 32076/93750
Step 32077/93750
Step 32078/93750
Step 32079/93750
Step 32080/93750
Step 32081/93750
Step 32082/93750
Step 32083/93750
Step 32084/93750
Step 32085/93750
Step 32086/93750
Step 32087/93750
Step 32088/93750
Step 32089/93750
Step 32090/93750
Step 32091/93750
Step 32092/93750
Step 32093/93750
Step 32094/93750
Step 32095/93750
Step 32096/93750
Step 32097/93750
Step 32098/93750
Step 32099/93750
Step 32100/93750
Step 32101/93750
Step 32102/93750
Step 32103/93750
Step 32104/93750
Step 32105/93750
Step 32106/93750
Step 32107/93750
Step 32108/93750
Step 32109/93750
Step 32110/93750
Step 32111/93750
Step 32112/93750
Step 32113/93750
Step 32114/93750
Step 32115/93750
Step 32116/93750
Step 32117/93750
Step 32118/93750
Step 32119/93750
Step 32120/93750
Step 32121/93750
Step 32122/93750
Step 32123/93750
Step 32124/93750
Step 32125/93750
Step 32126/93750
Step 32127/93750
Step 32128/93750
Step 32129/93750
Step 32130/93750
Step 32131/93750
Step 32132/93750
Step 32133/93750
Step 32134/93750
Step 32135/93750
Step 32136/93750
Step 32137/93750
Step 32138/93750
Step 32139/93750
Step 32140/93750
Step 32141/93750
Step 32142/93750
Step 32143/93750
Step 32144/93750
Step 32145/93750
Step 32146/93750
Step 32147/93750
Step 32148/93750
Step 32149/93750
Step 32150/93750
Step 32151/93750
Step 32152/93750
Step 32153/93750
Step 32154/93750
Step 32155/93750
Step 32156/93750
Step 32157/93750
Step 32158/93750
Step 32159/93750
Step 32160/93750
Step 32161/93750
Step 32162/93750
Step 32163/93750
Step 32164/93750
Step 32165/93750
Step 32166/93750
Step 32167/93750
Step 32168/93750
Step 32169/93750
Step 32170/93750
Step 32171/93750
Step 32172/93750
Step 32173/93750
Step 32174/93750
Step 32175/93750
Step 32176/93750
Step 32177/93750
Step 32178/93750
Step 32179/93750
Step 32180/93750
Step 32181/93750
Step 32182/93750
Step 32183/93750
Step 32184/93750
Step 32185/93750
Step 32186/93750
Step 32187/93750
Step 32188/93750
Step 32189/93750
Step 32190/93750
Step 32191/93750
Step 32192/93750
Step 32193/93750
Step 32194/93750
Step 32195/93750
Step 32196/93750
Step 32197/93750
Step 32198/93750
Step 32199/93750
Step 32200/93750
Step 32201/93750
Step 32202/93750
Step 32203/93750
Step 32204/93750
Step 32205/93750
Step 32206/93750
Step 32207/93750
Step 32208/93750
Step 32209/93750
Step 32210/93750
Step 32211/93750
Step 32212/93750
Step 32213/93750
Step 32214/93750
Step 32215/93750
Step 32216/93750
Step 32217/93750
Step 32218/93750
Step 32219/93750
Step 32220/93750
Step 32221/93750
Step 32222/93750
Step 32223/93750
Step 32224/93750
Step 32225/93750
Step 32226/93750
Step 32227/93750
Step 32228/93750
Step 32229/93750
Step 32230/93750
Step 32231/93750
Step 32232/93750
Step 32233/93750
Step 32234/93750
Step 32235/93750
Step 32236/93750
Step 32237/93750
Step 32238/93750
Step 32239/93750
Step 32240/93750
Step 32241/93750
Step 32242/93750
Step 32243/93750
Step 32244/93750
Step 32245/93750
Step 32246/93750
Step 32247/93750
Step 32248/93750
Step 32249/93750
Step 32250/93750
Step 32251/93750
Step 32252/93750
Step 32253/93750
Step 32254/93750
Step 32255/93750
Step 32256/93750
Step 32257/93750
Step 32258/93750
Step 32259/93750
Step 32260/93750
Step 32261/93750
Step 32262/93750
Step 32263/93750
Step 32264/93750
Step 32265/93750
Step 32266/93750
Step 32267/93750
Step 32268/93750
Step 32269/93750
Step 32270/93750
Step 32271/93750
Step 32272/93750
Step 32273/93750
Step 32274/93750
Step 32275/93750
Step 32276/93750
Step 32277/93750
Step 32278/93750
Step 32279/93750
Step 32280/93750
Step 32281/93750
Step 32282/93750
Step 32283/93750
Step 32284/93750
Step 32285/93750
Step 32286/93750
Step 32287/93750
Step 32288/93750
Step 32289/93750
Step 32290/93750
Step 32291/93750
Step 32292/93750
Step 32293/93750
Step 32294/93750
Step 32295/93750
Step 32296/93750
Step 32297/93750
Step 32298/93750
Step 32299/93750
Step 32300/93750
Step 32301/93750
Step 32302/93750
Step 32303/93750
Step 32304/93750
Step 32305/93750
Step 32306/93750
Step 32307/93750
Step 32308/93750
Step 32309/93750
Step 32310/93750
Step 32311/93750
Step 32312/93750
Step 32313/93750
Step 32314/93750
Step 32315/93750
Step 32316/93750
Step 32317/93750
Step 32318/93750
Step 32319/93750
Step 32320/93750
Step 32321/93750
Step 32322/93750
Step 32323/93750
Step 32324/93750
Step 32325/93750
Step 32326/93750
Step 32327/93750
Step 32328/93750
Step 32329/93750
Step 32330/93750
Step 32331/93750
Step 32332/93750
Step 32333/93750
Step 32334/93750
Step 32335/93750
Step 32336/93750
Step 32337/93750
Step 32338/93750
Step 32339/93750
Step 32340/93750
Step 32341/93750
Step 32342/93750
Step 32343/93750
Step 32344/93750
Step 32345/93750
Step 32346/93750
Step 32347/93750
Step 32348/93750
Step 32349/93750
Step 32350/93750
Step 32351/93750
Step 32352/93750
Step 32353/93750
Step 32354/93750
Step 32355/93750
Step 32356/93750
Step 32357/93750
Step 32358/93750
Step 32359/93750
Step 32360/93750
Step 32361/93750
Step 32362/93750
Step 32363/93750
Step 32364/93750
Step 32365/93750
Step 32366/93750
Step 32367/93750
Step 32368/93750
Step 32369/93750
Step 32370/93750
Step 32371/93750
Step 32372/93750
Step 32373/93750
Step 32374/93750
Step 32375/93750
Step 32376/93750
Step 32377/93750
Step 32378/93750
Step 32379/93750
Step 32380/93750
Step 32381/93750
Step 32382/93750
Step 32383/93750
Step 32384/93750
Step 32385/93750
Step 32386/93750
Step 32387/93750
Step 32388/93750
Step 32389/93750
Step 32390/93750
Step 32391/93750
Step 32392/93750
Step 32393/93750
Step 32394/93750
Step 32395/93750
Step 32396/93750
Step 32397/93750
Step 32398/93750
Step 32399/93750
Step 32400/93750
Step 32401/93750
Step 32402/93750
Step 32403/93750
Step 32404/93750
Step 32405/93750
Step 32406/93750
Step 32407/93750
Step 32408/93750
Step 32409/93750
Step 32410/93750
Step 32411/93750
Step 32412/93750
Step 32413/93750
Step 32414/93750
Step 32415/93750
Step 32416/93750
Step 32417/93750
Step 32418/93750
Step 32419/93750
Step 32420/93750
Step 32421/93750
Step 32422/93750
Step 32423/93750
Step 32424/93750
Step 32425/93750
Step 32426/93750
Step 32427/93750

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: language, generator, code. If language, generator, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 100000
  Batch size = 16
Saving model checkpoint to /kaggle/working/checkpoints_task_a/checkpoint-62500
Configuration saved in /kaggle/working/checkpoints_task_a/checkpoint-62500/config.json
Model weights saved in /kaggle/working/checkpoints_task_a/checkpoint-62500/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_task_a/checkpoint-62500/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_task_a/checkpoint-62500/special_tokens_map.json
/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

Step 62501/93750
Step 62502/93750
Step 62503/93750
Step 62504/93750
Step 62505/93750
Step 62506/93750
Step 62507/93750
Step 62508/93750
Step 62509/93750
Step 62510/93750
Step 62511/93750
Step 62512/93750
Step 62513/93750
Step 62514/93750
Step 62515/93750
Step 62516/93750
Step 62517/93750
Step 62518/93750
Step 62519/93750
Step 62520/93750
Step 62521/93750
Step 62522/93750
Step 62523/93750
Step 62524/93750
Step 62525/93750
Step 62526/93750
Step 62527/93750
Step 62528/93750
Step 62529/93750
Step 62530/93750
Step 62531/93750
Step 62532/93750
Step 62533/93750
Step 62534/93750
Step 62535/93750
Step 62536/93750
Step 62537/93750
Step 62538/93750
Step 62539/93750
Step 62540/93750
Step 62541/93750
Step 62542/93750
Step 62543/93750
Step 62544/93750
Step 62545/93750
Step 62546/93750
Step 62547/93750
Step 62548/93750
Step 62549/93750
Step 62550/93750
Step 62551/93750
Step 62552/93750
Step 62553/93750
Step 62554/93750
Step 62555/93750
Step 62556/93750
Step 62557/93750
Step 62558/93750
Step 62559/93750
Step 62560/93750
Step 62561/93750
Step 62562/93750
Step 62563/93750
Step 62564/93750
Step 62565/93750
Step 62566/93750
Step 62567/93750
Step 62568/93750
Step 62569/93750
Step 62570/93750
Step 62571/93750
Step 62572/93750
Step 62573/93750
Step 62574/93750
Step 62575/93750
Step 62576/93750
Step 62577/93750
Step 62578/93750
Step 62579/93750
Step 62580/93750
Step 62581/93750
Step 62582/93750
Step 62583/93750
Step 62584/93750
Step 62585/93750
Step 62586/93750
Step 62587/93750
Step 62588/93750
Step 62589/93750
Step 62590/93750
Step 62591/93750
Step 62592/93750
Step 62593/93750
Step 62594/93750
Step 62595/93750
Step 62596/93750
Step 62597/93750
Step 62598/93750
Step 62599/93750
Step 62600/93750
Step 62601/93750
Step 62602/93750
Step 62603/93750
Step 62604/93750
Step 62605/93750
Step 62606/93750
Step 62607/93750
Step 62608/93750
Step 62609/93750
Step 62610/93750
Step 62611/93750
Step 62612/93750
Step 62613/93750
Step 62614/93750
Step 62615/93750
Step 62616/93750
Step 62617/93750
Step 62618/93750
Step 62619/93750
Step 62620/93750
Step 62621/93750
Step 62622/93750
Step 62623/93750
Step 62624/93750
Step 62625/93750
Step 62626/93750
Step 62627/93750
Step 62628/93750
Step 62629/93750
Step 62630/93750
Step 62631/93750
Step 62632/93750
Step 62633/93750
Step 62634/93750
Step 62635/93750
Step 62636/93750
Step 62637/93750
Step 62638/93750
Step 62639/93750
Step 62640/93750
Step 62641/93750
Step 62642/93750
Step 62643/93750
Step 62644/93750
Step 62645/93750
Step 62646/93750
Step 62647/93750
Step 62648/93750
Step 62649/93750
Step 62650/93750
Step 62651/93750
Step 62652/93750
Step 62653/93750
Step 62654/93750
Step 62655/93750
Step 62656/93750
Step 62657/93750
Step 62658/93750
Step 62659/93750
Step 62660/93750
Step 62661/93750
Step 62662/93750
Step 62663/93750
Step 62664/93750
Step 62665/93750
Step 62666/93750
Step 62667/93750
Step 62668/93750
Step 62669/93750
Step 62670/93750
Step 62671/93750
Step 62672/93750
Step 62673/93750
Step 62674/93750
Step 62675/93750
Step 62676/93750
Step 62677/93750
Step 62678/93750
Step 62679/93750
Step 62680/93750
Step 62681/93750
Step 62682/93750
Step 62683/93750
Step 62684/93750
Step 62685/93750
Step 62686/93750
Step 62687/93750
Step 62688/93750
Step 62689/93750
Step 62690/93750
Step 62691/93750
Step 62692/93750
Step 62693/93750
Step 62694/93750
Step 62695/93750
Step 62696/93750
Step 62697/93750
Step 62698/93750
Step 62699/93750
Step 62700/93750
Step 62701/93750
Step 62702/93750
Step 62703/93750
Step 62704/93750
Step 62705/93750
Step 62706/93750
Step 62707/93750
Step 62708/93750
Step 62709/93750
Step 62710/93750
Step 62711/93750
Step 62712/93750
Step 62713/93750
Step 62714/93750
Step 62715/93750
Step 62716/93750
Step 62717/93750
Step 62718/93750
Step 62719/93750
Step 62720/93750
Step 62721/93750
Step 62722/93750
Step 62723/93750
Step 62724/93750
Step 62725/93750
Step 62726/93750
Step 62727/93750
Step 62728/93750
Step 62729/93750
Step 62730/93750
Step 62731/93750
Step 62732/93750
Step 62733/93750
Step 62734/93750
Step 62735/93750
Step 62736/93750
Step 62737/93750
Step 62738/93750
Step 62739/93750
Step 62740/93750
Step 62741/93750
Step 62742/93750
Step 62743/93750
Step 62744/93750
Step 62745/93750
Step 62746/93750
Step 62747/93750
Step 62748/93750
Step 62749/93750
Step 62750/93750
Step 62751/93750
Step 62752/93750
Step 62753/93750
Step 62754/93750
Step 62755/93750
Step 62756/93750
Step 62757/93750
Step 62758/93750
Step 62759/93750
Step 62760/93750
Step 62761/93750
Step 62762/93750
Step 62763/93750
Step 62764/93750
Step 62765/93750
Step 62766/93750
Step 62767/93750
Step 62768/93750
Step 62769/93750
Step 62770/93750
Step 62771/93750
Step 62772/93750
Step 62773/93750
Step 62774/93750
Step 62775/93750
Step 62776/93750
Step 62777/93750
Step 62778/93750
Step 62779/93750
Step 62780/93750
Step 62781/93750
Step 62782/93750
Step 62783/93750
Step 62784/93750
Step 62785/93750
Step 62786/93750
Step 62787/93750
Step 62788/93750
Step 62789/93750
Step 62790/93750
Step 62791/93750
Step 62792/93750
Step 62793/93750
Step 62794/93750
Step 62795/93750
Step 62796/93750
Step 62797/93750
Step 62798/93750
Step 62799/93750
Step 62800/93750
Step 62801/93750
Step 62802/93750
Step 62803/93750
Step 62804/93750
Step 62805/93750
Step 62806/93750
Step 62807/93750
Step 62808/93750
Step 62809/93750
Step 62810/93750
Step 62811/93750
Step 62812/93750
Step 62813/93750
Step 62814/93750
Step 62815/93750
Step 62816/93750
Step 62817/93750
Step 62818/93750
Step 62819/93750
Step 62820/93750
Step 62821/93750
Step 62822/93750
Step 62823/93750
Step 62824/93750
Step 62825/93750
Step 62826/93750
Step 62827/93750
Step 62828/93750
Step 62829/93750
Step 62830/93750
Step 62831/93750
Step 62832/93750
Step 62833/93750
Step 62834/93750
Step 62835/93750
Step 62836/93750
Step 62837/93750
Step 62838/93750
Step 62839/93750
Step 62840/93750
Step 62841/93750
Step 62842/93750
Step 62843/93750
Step 62844/93750
Step 62845/93750
Step 62846/93750
Step 62847/93750
Step 62848/93750
Step 62849/93750
Step 62850/93750
Step 62851/93750
Step 62852/93750
Step 62853/93750
Step 62854/93750
Step 62855/93750
Step 62856/93750
Step 62857/93750
Step 62858/93750
Step 62859/93750
Step 62860/93750
Step 62861/93750
Step 62862/93750
Step 62863/93750
Step 62864/93750
Step 62865/93750
Step 62866/93750
Step 62867/93750
Step 62868/93750
Step 62869/93750
Step 62870/93750
Step 62871/93750
Step 62872/93750
Step 62873/93750
Step 62874/93750
Step 62875/93750
Step 62876/93750
Step 62877/93750
Step 62878/93750
Step 62879/93750
Step 62880/93750
Step 62881/93750
Step 62882/93750
Step 62883/93750
Step 62884/93750
Step 62885/93750
Step 62886/93750
Step 62887/93750
Step 62888/93750
Step 62889/93750
Step 62890/93750
Step 62891/93750
Step 62892/93750
Step 62893/93750
Step 62894/93750
Step 62895/93750
Step 62896/93750
Step 62897/93750
Step 62898/93750
Step 62899/93750
Step 62900/93750
Step 62901/93750
Step 62902/93750
Step 62903/93750
Step 62904/93750
Step 62905/93750
Step 62906/93750
Step 62907/93750
Step 62908/93750
Step 62909/93750
Step 62910/93750
Step 62911/93750
Step 62912/93750
Step 62913/93750
Step 62914/93750
Step 62915/93750
Step 62916/93750
Step 62917/93750
Step 62918/93750
Step 62919/93750
Step 62920/93750
Step 62921/93750
Step 62922/93750
Step 62923/93750
Step 62924/93750
Step 62925/93750
Step 62926/93750
Step 62927/93750
Step 62928/93750
Step 62929/93750
Step 62930/93750
Step 62931/93750
Step 62932/93750
Step 62933/93750
Step 62934/93750
Step 62935/93750
Step 62936/93750
Step 62937/93750
Step 62938/93750
Step 62939/93750
Step 62940/93750
Step 62941/93750
Step 62942/93750
Step 62943/93750
Step 62944/93750
Step 62945/93750
Step 62946/93750
Step 62947/93750
Step 62948/93750
Step 62949/93750
Step 62950/93750
Step 62951/93750
Step 62952/93750
Step 62953/93750
Step 62954/93750
Step 62955/93750
Step 62956/93750
Step 62957/93750
Step 62958/93750
Step 62959/93750
Step 62960/93750
Step 62961/93750
Step 62962/93750
Step 62963/93750
Step 62964/93750
Step 62965/93750
Step 62966/93750
Step 62967/93750
Step 62968/93750
Step 62969/93750
Step 62970/93750
Step 62971/93750
Step 62972/93750
Step 62973/93750
Step 62974/93750
Step 62975/93750
Step 62976/93750
Step 62977/93750
Step 62978/93750
Step 62979/93750
Step 62980/93750
Step 62981/93750
Step 62982/93750
Step 62983/93750
Step 62984/93750
Step 62985/93750
Step 62986/93750
Step 62987/93750
Step 62988/93750
Step 62989/93750
Step 62990/93750
Step 62991/93750
Step 62992/93750
Step 62993/93750
Step 62994/93750
Step 62995/93750
Step 62996/93750
Step 62997/93750
Step 62998/93750
Step 62999/93750
Step 63000/93750
Step 63001/93750
Step 63002/93750
Step 63003/93750
Step 63004/93750
Step 63005/93750
Step 63006/93750
Step 63007/93750
Step 63008/93750
Step 63009/93750
Step 63010/93750
Step 63011/93750
Step 63012/93750
Step 63013/93750
Step 63014/93750
Step 63015/93750
Step 63016/93750
Step 63017/93750
Step 63018/93750
Step 63019/93750
Step 63020/93750
Step 63021/93750
Step 63022/93750
Step 63023/93750
Step 63024/93750
Step 63025/93750
Step 63026/93750
Step 63027/93750
Step 63028/93750
Step 63029/93750
Step 63030/93750
Step 63031/93750
Step 63032/93750
Step 63033/93750
Step 63034/93750
Step 63035/93750
Step 63036/93750
Step 63037/93750
Step 63038/93750
Step 63039/93750
Step 63040/93750
Step 63041/93750
Step 63042/93750
Step 63043/93750
Step 63044/93750
Step 63045/93750
Step 63046/93750
Step 63047/93750
Step 63048/93750
Step 63049/93750
Step 63050/93750
Step 63051/93750
Step 63052/93750
Step 63053/93750
Step 63054/93750
Step 63055/93750
Step 63056/93750
Step 63057/93750
Step 63058/93750
Step 63059/93750
Step 63060/93750
Step 63061/93750
Step 63062/93750
Step 63063/93750
Step 63064/93750
Step 63065/93750
Step 63066/93750
Step 63067/93750
Step 63068/93750
Step 63069/93750
Step 63070/93750
Step 63071/93750
Step 63072/93750
Step 63073/93750
Step 63074/93750
Step 63075/93750
Step 63076/93750
Step 63077/93750
Step 63078/93750
Step 63079/93750
Step 63080/93750
Step 63081/93750
Step 63082/93750
Step 63083/93750
Step 63084/93750
Step 63085/93750
Step 63086/93750
Step 63087/93750
Step 63088/93750
Step 63089/93750
Step 63090/93750
Step 63091/93750
Step 63092/93750
Step 63093/93750
Step 63094/93750
Step 63095/93750
Step 63096/93750
Step 63097/93750
Step 63098/93750
Step 63099/93750
Step 63100/93750
Step 63101/93750
Step 63102/93750
Step 63103/93750
Step 63104/93750
Step 63105/93750
Step 63106/93750
Step 63107/93750
Step 63108/93750
Step 63109/93750
Step 63110/93750
Step 63111/93750
Step 63112/93750
Step 63113/93750
Step 63114/93750
Step 63115/93750
Step 63116/93750
Step 63117/93750
Step 63118/93750
Step 63119/93750
Step 63120/93750
Step 63121/93750
Step 63122/93750
Step 63123/93750
Step 63124/93750
Step 63125/93750
Step 63126/93750
Step 63127/93750
Step 63128/93750
Step 63129/93750
Step 63130/93750
Step 63131/93750
Step 63132/93750
Step 63133/93750
Step 63134/93750
Step 63135/93750
Step 63136/93750
Step 63137/93750
Step 63138/93750
Step 63139/93750
Step 63140/93750
Step 63141/93750
Step 63142/93750
Step 63143/93750
Step 63144/93750
Step 63145/93750
Step 63146/93750
Step 63147/93750
Step 63148/93750
Step 63149/93750
Step 63150/93750
Step 63151/93750
Step 63152/93750
Step 63153/93750
Step 63154/93750
Step 63155/93750
Step 63156/93750
Step 63157/93750
Step 63158/93750
Step 63159/93750
Step 63160/93750
Step 63161/93750
Step 63162/93750
Step 63163/93750
Step 63164/93750
Step 63165/93750
Step 63166/93750
Step 63167/93750
Step 63168/93750
Step 63169/93750
Step 63170/93750
Step 63171/93750
Step 63172/93750
Step 63173/93750
Step 63174/93750
Step 63175/93750
Step 63176/93750
Step 63177/93750
Step 63178/93750
Step 63179/93750
Step 63180/93750
Step 63181/93750
Step 63182/93750
Step 63183/93750
Step 63184/93750
Step 63185/93750
Step 63186/93750
Step 63187/93750
Step 63188/93750
Step 63189/93750
Step 63190/93750
Step 63191/93750
Step 63192/93750
Step 63193/93750
Step 63194/93750
Step 63195/93750
Step 63196/93750
Step 63197/93750
Step 63198/93750
Step 63199/93750
Step 63200/93750
Step 63201/93750
Step 63202/93750
Step 63203/93750
Step 63204/93750
Step 63205/93750
Step 63206/93750
Step 63207/93750
Step 63208/93750
Step 63209/93750
Step 63210/93750
Step 63211/93750
Step 63212/93750
Step 63213/93750
Step 63214/93750
Step 63215/93750
Step 63216/93750
Step 63217/93750
Step 63218/93750
Step 63219/93750
Step 63220/93750
Step 63221/93750
Step 63222/93750
Step 63223/93750
Step 63224/93750
Step 63225/93750
Step 63226/93750
Step 63227/93750
Step 63228/93750
Step 63229/93750
Step 63230/93750
Step 63231/93750
Step 63232/93750
Step 63233/93750
Step 63234/93750
Step 63235/93750
Step 63236/93750
Step 63237/93750
Step 63238/93750
Step 63239/93750
Step 63240/93750
Step 63241/93750
Step 63242/93750
Step 63243/93750
Step 63244/93750
Step 63245/93750
Step 63246/93750
Step 63247/93750
Step 63248/93750
Step 63249/93750
Step 63250/93750
Step 63251/93750
Step 63252/93750
Step 63253/93750
Step 63254/93750
Step 63255/93750
Step 63256/93750
Step 63257/93750
Step 63258/93750
Step 63259/93750
Step 63260/93750
Step 63261/93750
Step 63262/93750
Step 63263/93750
Step 63264/93750
Step 63265/93750
Step 63266/93750
Step 63267/93750
Step 63268/93750
Step 63269/93750
Step 63270/93750
Step 63271/93750
Step 63272/93750
Step 63273/93750
Step 63274/93750
Step 63275/93750
Step 63276/93750
Step 63277/93750
Step 63278/93750
Step 63279/93750
Step 63280/93750
Step 63281/93750
Step 63282/93750
Step 63283/93750
Step 63284/93750
Step 63285/93750
Step 63286/93750
Step 63287/93750
Step 63288/93750
Step 63289/93750
Step 63290/93750
Step 63291/93750
Step 63292/93750
Step 63293/93750
Step 63294/93750
Step 63295/93750
Step 63296/93750
Step 63297/93750
Step 63298/93750
Step 63299/93750
Step 63300/93750
Step 63301/93750
Step 63302/93750
Step 63303/93750
Step 63304/93750
Step 63305/93750
Step 63306/93750
Step 63307/93750
Step 63308/93750
Step 63309/93750
Step 63310/93750
Step 63311/93750
Step 63312/93750
Step 63313/93750
Step 63314/93750
Step 63315/93750
Step 63316/93750
Step 63317/93750
Step 63318/93750
Step 63319/93750
Step 63320/93750
Step 63321/93750
Step 63322/93750
Step 63323/93750
Step 63324/93750
Step 63325/93750
Step 63326/93750
Step 63327/93750
Step 63328/93750
Step 63329/93750
Step 63330/93750
Step 63331/93750
Step 63332/93750
Step 63333/93750
Step 63334/93750
Step 63335/93750
Step 63336/93750
Step 63337/93750
Step 63338/93750
Step 63339/93750
Step 63340/93750
Step 63341/93750
Step 63342/93750
Step 63343/93750
Step 63344/93750
Step 63345/93750
Step 63346/93750
Step 63347/93750
Step 63348/93750
Step 63349/93750
Step 63350/93750
Step 63351/93750
Step 63352/93750
Step 63353/93750
Step 63354/93750
Step 63355/93750
Step 63356/93750
Step 63357/93750
Step 63358/93750
Step 63359/93750
Step 63360/93750
Step 63361/93750
Step 63362/93750
Step 63363/93750
Step 63364/93750
Step 63365/93750
Step 63366/93750
Step 63367/93750
Step 63368/93750
Step 63369/93750
Step 63370/93750
Step 63371/93750
Step 63372/93750
Step 63373/93750
Step 63374/93750
Step 63375/93750
Step 63376/93750
Step 63377/93750
Step 63378/93750
Step 63379/93750
Step 63380/93750
Step 63381/93750
Step 63382/93750
Step 63383/93750
Step 63384/93750
Step 63385/93750
Step 63386/93750
Step 63387/93750
Step 63388/93750
Step 63389/93750
Step 63390/93750
Step 63391/93750
Step 63392/93750
Step 63393/93750
Step 63394/93750
Step 63395/93750
Step 63396/93750
Step 63397/93750
Step 63398/93750
Step 63399/93750
Step 63400/93750
Step 63401/93750
Step 63402/93750
Step 63403/93750
Step 63404/93750
Step 63405/93750
Step 63406/93750
Step 63407/93750
Step 63408/93750
Step 63409/93750
Step 63410/93750
Step 63411/93750
Step 63412/93750
Step 63413/93750
Step 63414/93750
Step 63415/93750
Step 63416/93750
Step 63417/93750
Step 63418/93750
Step 63419/93750
Step 63420/93750
Step 63421/93750
Step 63422/93750
Step 63423/93750
Step 63424/93750
Step 63425/93750
Step 63426/93750
Step 63427/93750
Step 63428/93750
Step 63429/93750
Step 63430/93750
Step 63431/93750
Step 63432/93750
Step 63433/93750
Step 63434/93750
Step 63435/93750
Step 63436/93750
Step 63437/93750
Step 63438/93750
Step 63439/93750
Step 63440/93750
Step 63441/93750
Step 63442/93750
Step 63443/93750
Step 63444/93750
Step 63445/93750
Step 63446/93750
Step 63447/93750
Step 63448/93750
Step 63449/93750
Step 63450/93750
Step 63451/93750
Step 63452/93750
Step 63453/93750
Step 63454/93750
Step 63455/93750
Step 63456/93750
Step 63457/93750
Step 63458/93750
Step 63459/93750
Step 63460/93750
Step 63461/93750
Step 63462/93750
Step 63463/93750
Step 63464/93750
Step 63465/93750
Step 63466/93750
Step 63467/93750
Step 63468/93750
Step 63469/93750
Step 63470/93750
Step 63471/93750
Step 63472/93750
Step 63473/93750
Step 63474/93750
Step 63475/93750
Step 63476/93750
Step 63477/93750
Step 63478/93750
Step 63479/93750
Step 63480/93750
Step 63481/93750
Step 63482/93750
Step 63483/93750
Step 63484/93750
Step 63485/93750
Step 63486/93750
Step 63487/93750
Step 63488/93750
Step 63489/93750
Step 63490/93750
Step 63491/93750
Step 63492/93750
Step 63493/93750
Step 63494/93750
Step 63495/93750
Step 63496/93750
Step 63497/93750
Step 63498/93750
Step 63499/93750
Step 63500/93750
Step 63501/93750
Step 63502/93750
Step 63503/93750
Step 63504/93750
Step 63505/93750
Step 63506/93750
Step 63507/93750
Step 63508/93750
Step 63509/93750
Step 63510/93750
Step 63511/93750
Step 63512/93750
Step 63513/93750
Step 63514/93750
Step 63515/93750
Step 63516/93750
Step 63517/93750
Step 63518/93750
Step 63519/93750
Step 63520/93750
Step 63521/93750
Step 63522/93750
Step 63523/93750
Step 63524/93750
Step 63525/93750
Step 63526/93750
Step 63527/93750
Step 63528/93750
Step 63529/93750
Step 63530/93750
Step 63531/93750
Step 63532/93750
Step 63533/93750
Step 63534/93750
Step 63535/93750
Step 63536/93750
Step 63537/93750
Step 63538/93750
Step 63539/93750
Step 63540/93750
Step 63541/93750
Step 63542/93750
Step 63543/93750
Step 63544/93750
Step 63545/93750
Step 63546/93750
Step 63547/93750
Step 63548/93750
Step 63549/93750
Step 63550/93750
Step 63551/93750
Step 63552/93750
Step 63553/93750
Step 63554/93750
Step 63555/93750
Step 63556/93750
Step 63557/93750
Step 63558/93750
Step 63559/93750
Step 63560/93750
Step 63561/93750
Step 63562/93750
Step 63563/93750
Step 63564/93750
Step 63565/93750
Step 63566/93750
Step 63567/93750
Step 63568/93750
Step 63569/93750
Step 63570/93750
Step 63571/93750
Step 63572/93750
Step 63573/93750
Step 63574/93750
Step 63575/93750
Step 63576/93750
Step 63577/93750
Step 63578/93750
Step 63579/93750
Step 63580/93750
Step 63581/93750
Step 63582/93750
Step 63583/93750
Step 63584/93750
Step 63585/93750
Step 63586/93750
Step 63587/93750
Step 63588/93750
Step 63589/93750
Step 63590/93750
Step 63591/93750
Step 63592/93750
Step 63593/93750
Step 63594/93750
Step 63595/93750
Step 63596/93750
Step 63597/93750
Step 63598/93750
Step 63599/93750
Step 63600/93750
Step 63601/93750
Step 63602/93750
Step 63603/93750
Step 63604/93750
Step 63605/93750
Step 63606/93750
Step 63607/93750
Step 63608/93750
Step 63609/93750
Step 63610/93750
Step 63611/93750
Step 63612/93750
Step 63613/93750
Step 63614/93750
Step 63615/93750
Step 63616/93750
Step 63617/93750
Step 63618/93750
Step 63619/93750
Step 63620/93750
Step 63621/93750
Step 63622/93750
Step 63623/93750
Step 63624/93750
Step 63625/93750
Step 63626/93750
Step 63627/93750
Step 63628/93750
Step 63629/93750
Step 63630/93750
Step 63631/93750
Step 63632/93750
Step 63633/93750
Step 63634/93750
Step 63635/93750
Step 63636/93750
Step 63637/93750
Step 63638/93750
Step 63639/93750
Step 63640/93750
Step 63641/93750
Step 63642/93750
Step 63643/93750
Step 63644/93750
Step 63645/93750
Step 63646/93750
Step 63647/93750
Step 63648/93750
Step 63649/93750
Step 63650/93750
Step 63651/93750
Step 63652/93750
Step 63653/93750
Step 63654/93750
Step 63655/93750
Step 63656/93750
Step 63657/93750
Step 63658/93750
Step 63659/93750
Step 63660/93750
Step 63661/93750
Step 63662/93750
Step 63663/93750
Step 63664/93750
Step 63665/93750
Step 63666/93750
Step 63667/93750
Step 63668/93750
Step 63669/93750
Step 63670/93750
Step 63671/93750
Step 63672/93750
Step 63673/93750
Step 63674/93750
Step 63675/93750
Step 63676/93750

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: language, generator, code. If language, generator, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 100000
  Batch size = 16
Saving model checkpoint to /kaggle/working/checkpoints_task_a/checkpoint-93750
Configuration saved in /kaggle/working/checkpoints_task_a/checkpoint-93750/config.json
Model weights saved in /kaggle/working/checkpoints_task_a/checkpoint-93750/model.safetensors
tokenizer config file saved in /kaggle/working/checkpoints_task_a/checkpoint-93750/tokenizer_config.json
Special tokens file saved in /kaggle/working/checkpoints_task_a/checkpoint-93750/special_tokens_map.json
Deleting older checkpoint [/kaggle/working/checkpoints_task_a/checkpoint-31250] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from /kaggle/working/checkpoints_task_a/checkpoint-93750 (score: 0.9939207402167887).
The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: language, generator, code. If language, generator, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 100000
  Batch size = 16
/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

The following columns in the Evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: language, generator, ID, code. If language, generator, ID, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16

Eval on validation: {'eval_loss': 0.024901509284973145, 'eval_macro_f1': 0.9939207402167887, 'eval_accuracy': 0.99364, 'eval_precision': 0.993844742224686, 'eval_recall': 0.993996749832712, 'eval_runtime': 1022.9962, 'eval_samples_per_second': 97.752, 'eval_steps_per_second': 6.11, 'epoch': 3.0}

/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
The following columns in the test set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: __index_level_0__, ID, code. If __index_level_0__, ID, code are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 1000
  Batch size = 16

Eval on test_sample_merged (labeled subset): {'eval_loss': 5.335013389587402, 'eval_macro_f1': 0.3435251798561151, 'eval_accuracy': 0.27, 'eval_precision': 0.21484814398200225, 'eval_recall': 0.8565022421524664, 'eval_runtime': 10.2865, 'eval_samples_per_second': 97.215, 'eval_steps_per_second': 6.125, 'epoch': 3.0}
Missing labels after merge: 0
Saved: /kaggle/working/submission.csv

     ID  label
0  2005      1
1  2384      0
2  3526      0
3  3926      0
4  7222      1

In [1]:
print("test_sample_df:", test_sample_df.shape)
print("test_sample_merged:", test_sample_merged.shape)

print("Unique IDs in test_sample_df:", test_sample_df["ID"].nunique())
print("Unique IDs in test_sample_merged:", test_sample_merged["ID"].nunique())

test_sample_df: (1000, 4)
test_sample_merged: (1000, 5)

KeyError: 'ID'

In [2]:
print("train cols:", training_df.columns.tolist())
print("val cols:", validation_df.columns.tolist())
print("test cols:", test_df.columns.tolist())
print("test_sample cols:", test_sample_df.columns.tolist())

train cols: ['code', 'generator', 'label', 'language']
val cols: ['code', 'generator', 'label', 'language']
test cols: ['ID', 'code']
test_sample cols: ['code', 'generator', 'label', 'language']

In [3]:
train_g = set(training_df["generator"].unique())
val_g = set(validation_df["generator"].unique())
ts_g = set(test_sample_df["generator"].unique())

print("train generators:", len(train_g))
print("val generators:", len(val_g))
print("test_sample generators:", len(ts_g))

print("generators in test_sample but not in train:", sorted(ts_g - train_g)[:50])
print("generators in val but not in train:", sorted(val_g - train_g)[:50])

train generators: 35
val generators: 35
test_sample generators: 63
generators in test_sample but not in train: ['GPT-4o', 'Human', 'Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen2.5-Codder-14B-Instruct', 'deepseek-ai/DeepSeek-V3-0324', 'gemini-1.5-flash', 'gemini-1.5-flash-8b', 'gemini-2.0-flash', 'gemini-2.0-flash-lite', 'gemini-2.5-flash-preview-05-20', 'gemma-3-27b-it', 'google/codegemma-7b-it', 'google/gemma-3-12b-it', 'google/gemma-3-27b-it', 'google/gemma-3-4b-it', 'meta-llama/Llama-3.2-11B-Vision-Instruct', 'meta-llama/Llama-3.2-90B-Vision-Instruct', 'meta-llama/Llama-3.3-70B-Instruct-Turbo', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo', 'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'meta-llama/Meta-Llama-3.1-405B-Instruct', 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', 'microsoft/Phi-4-multimodal-instruct', 'microsoft/phi-4', 'mistralai/Devstral-Small-2505', 'mistralai/Mistral-7B-Instruct-v0.3', 'mistralai/Mistral-Nemo-Instruct-2407', 'mistralai/Mistral-Small-24B-Instruct-2501', 'mistralai/Mixtral-8x7B-Instruct-v0.1']
generators in val but not in train: []

In [4]:
# ============================================================
# Re-evaluate a saved UniXcoder checkpoint + generate submission
# (NO retraining)
# - Loads best/last checkpoint from OUTPUT_DIR
# - Evaluates on: validation.parquet and test_sample.parquet (labeled)
# - Optionally tunes a probability threshold on test_sample
# - Generates submission on test.parquet
# ============================================================

import os
import numpy as np
import pandas as pd
import torch

from datasets import Dataset
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
)
from transformers.trainer_utils import get_last_checkpoint

# ----------------------------
# Paths (edit if needed)
# ----------------------------
BASE_PATH = "/kaggle/input/sem-eval-2026-task-13-subtask-a/Task_A"
TRAIN_PATH = os.path.join(BASE_PATH, "train.parquet")
VAL_PATH = os.path.join(BASE_PATH, "validation.parquet")
TEST_SAMPLE_PATH = os.path.join(BASE_PATH, "test_sample.parquet")
TEST_PATH = os.path.join(BASE_PATH, "test.parquet")

# Where your checkpoints were saved during training
OUTPUT_DIR = "/kaggle/working/checkpoints_task_a"

# Output submission paths
SUBMISSION_ARGMAX_PATH = "/kaggle/working/submission_argmax.csv"
SUBMISSION_THRESH_PATH = "/kaggle/working/submission_thresholded.csv"

# Model + tokenization settings (must match training)
PRETRAINED_MODEL = "microsoft/unixcoder-base"
MAX_LENGTH = 256
BATCH_SIZE = 8

# ----------------------------
# Load dataframes
# ----------------------------
training_df = pd.read_parquet(TRAIN_PATH)
validation_df = pd.read_parquet(VAL_PATH)
test_sample_df = pd.read_parquet(TEST_SAMPLE_PATH)
test_df = pd.read_parquet(TEST_PATH)

for df in [training_df, validation_df, test_sample_df, test_df]:
    if "__index_level_0__" in df.columns:
        df.drop(columns=["__index_level_0__"], inplace=True)

print("Loaded shapes:")
print("train:", training_df.shape)
print("val:", validation_df.shape)
print("test_sample:", test_sample_df.shape)
print("test:", test_df.shape)
print("test columns:", test_df.columns.tolist())

# ----------------------------
# Quick generator shift summary (optional but useful)
# ----------------------------
train_g = set(training_df["generator"].unique()) if "generator" in training_df.columns else set()
val_g = set(validation_df["generator"].unique()) if "generator" in validation_df.columns else set()
ts_g = set(test_sample_df["generator"].unique()) if "generator" in test_sample_df.columns else set()

if train_g and ts_g:
    unseen = sorted(ts_g - train_g)
    print(f"\nGenerators: train={len(train_g)}, val={len(val_g)}, test_sample={len(ts_g)}")
    print(f"Unseen generators in test_sample (not in train): {len(unseen)}")
    print("First 25 unseen:", unseen[:25])

# ----------------------------
# Load checkpoint (NO training)
# ----------------------------
ckpt = get_last_checkpoint(OUTPUT_DIR)
if ckpt is None:
    raise FileNotFoundError(
        f"No checkpoint found under {OUTPUT_DIR}. "
        "Make sure training finished and saved checkpoints."
    )

print("\nLoading checkpoint:", ckpt)

tokenizer = AutoTokenizer.from_pretrained(PRETRAINED_MODEL)
model = AutoModelForSequenceClassification.from_pretrained(ckpt, num_labels=2)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
print("Device:", device)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def preprocess_function(examples):
    return tokenizer(examples["code"], truncation=True, max_length=MAX_LENGTH)

def df_to_tokenized_dataset(df: pd.DataFrame, has_labels: bool):
    ds = Dataset.from_pandas(df)
    if has_labels:
        # Make label column explicit for Trainer/prediction code below
        if "label" in ds.column_names and "labels" not in ds.column_names:
            ds = ds.rename_column("label", "labels")
    ds = ds.map(preprocess_function, batched=True)
    ds.set_format("torch")
    return ds

# Tokenized datasets
val_tok = df_to_tokenized_dataset(validation_df, has_labels=True)
ts_tok = df_to_tokenized_dataset(test_sample_df, has_labels=True)
test_tok = df_to_tokenized_dataset(test_df, has_labels=False)

# Minimal eval args
args = TrainingArguments(
    output_dir="/kaggle/working/tmp_eval",
    per_device_eval_batch_size=BATCH_SIZE,
    report_to=[],
)

trainer = Trainer(
    model=model,
    args=args,
    tokenizer=tokenizer,
    data_collator=data_collator,
)

# ----------------------------
# Evaluation helper
# ----------------------------
def eval_and_print(name: str, tokenized_ds):
    pred = trainer.predict(tokenized_ds)
    logits = pred.predictions
    y_true = np.array(tokenized_ds["labels"])

    probs = torch.softmax(torch.tensor(logits), dim=1).numpy()
    y_hat = np.argmax(probs, axis=1)

    out = {
        "accuracy": accuracy_score(y_true, y_hat),
        "f1_binary": f1_score(y_true, y_hat, average="binary"),
        "f1_macro": f1_score(y_true, y_hat, average="macro"),
        "precision": precision_score(y_true, y_hat, average="binary", zero_division=0),
        "recall": recall_score(y_true, y_hat, average="binary", zero_division=0),
    }
    print(f"\n{name} metrics:")
    for k, v in out.items():
        print(f"  {k}: {v:.6f}")
    return out, probs, y_true

# Evaluate on validation and labeled test_sample
val_metrics, _, _ = eval_and_print("VALIDATION", val_tok)
ts_metrics, ts_probs, ts_y = eval_and_print("TEST_SAMPLE (labeled subset)", ts_tok)

# ----------------------------
# Threshold tuning on test_sample (optional, but often helps OOD)
# ----------------------------
def find_best_threshold(y_true, p_pos, metric="f1_binary"):
    best_t, best_score = 0.5, -1.0
    # coarse grid; increase resolution if you want
    for t in np.linspace(0.05, 0.95, 19):
        y_pred = (p_pos >= t).astype(int)
        if metric == "f1_macro":
            score = f1_score(y_true, y_pred, average="macro")
        else:
            score = f1_score(y_true, y_pred, average="binary")
        if score > best_score:
            best_score, best_t = score, float(t)
    return best_t, best_score

p_ai_ts = ts_probs[:, 1]
best_t, best_f1 = find_best_threshold(ts_y, p_ai_ts, metric="f1_binary")
print(f"\nBest threshold on TEST_SAMPLE for F1(binary): t={best_t:.2f}, F1={best_f1:.6f}")

# ----------------------------
# Predict on real TEST and save submissions
# ----------------------------
test_pred = trainer.predict(test_tok)
test_logits = test_pred.predictions
test_probs = torch.softmax(torch.tensor(test_logits), dim=1).numpy()

# 1) Argmax submission (what you already did)
test_labels_argmax = np.argmax(test_probs, axis=1).astype(int)
sub_argmax = pd.DataFrame({"ID": test_df["ID"].values, "label": test_labels_argmax})
sub_argmax.to_csv(SUBMISSION_ARGMAX_PATH, index=False)
print("\nSaved:", SUBMISSION_ARGMAX_PATH)
print(sub_argmax.head())

# 2) Thresholded submission (uses tuned threshold from test_sample)
test_labels_thresh = (test_probs[:, 1] >= best_t).astype(int)
sub_thresh = pd.DataFrame({"ID": test_df["ID"].values, "label": test_labels_thresh})
sub_thresh.to_csv(SUBMISSION_THRESH_PATH, index=False)
print("\nSaved:", SUBMISSION_THRESH_PATH)
print(sub_thresh.head())

print("\nDone. Submit one (or both) of these:")
print(" -", SUBMISSION_ARGMAX_PATH)
print(" -", SUBMISSION_THRESH_PATH)

Loaded shapes:
train: (500000, 4)
val: (100000, 4)
test_sample: (1000, 4)
test: (500000, 2)
test columns: ['ID', 'code']

Generators: train=35, val=35, test_sample=63
Unseen generators in test_sample (not in train): 30
First 25 unseen: ['GPT-4o', 'Human', 'Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen2.5-Codder-14B-Instruct', 'deepseek-ai/DeepSeek-V3-0324', 'gemini-1.5-flash', 'gemini-1.5-flash-8b', 'gemini-2.0-flash', 'gemini-2.0-flash-lite', 'gemini-2.5-flash-preview-05-20', 'gemma-3-27b-it', 'google/codegemma-7b-it', 'google/gemma-3-12b-it', 'google/gemma-3-27b-it', 'google/gemma-3-4b-it', 'meta-llama/Llama-3.2-11B-Vision-Instruct', 'meta-llama/Llama-3.2-90B-Vision-Instruct', 'meta-llama/Llama-3.3-70B-Instruct-Turbo', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo', 'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'meta-llama/Meta-Llama-3.1-405B-Instruct', 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', 'microsoft/Phi-4-multimodal-instruct', 'microsoft/phi-4']

Loading checkpoint: /kaggle/working/checkpoints_task_a/checkpoint-93750

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Device: cuda

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500000 [00:00<?, ? examples/s]

/tmp/ipykernel_55/2158367193.py:125: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

VALIDATION metrics:
  accuracy: 0.993640
  f1_binary: 0.993921
  f1_macro: 0.993626
  precision: 0.993845
  recall: 0.993997

/usr/local/lib/python3.12/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

TEST_SAMPLE (labeled subset) metrics:
  accuracy: 0.270000
  f1_binary: 0.343525
  f1_macro: 0.260727
  precision: 0.214848
  recall: 0.856502

Best threshold on TEST_SAMPLE for F1(binary): t=0.10, F1=0.345568

Saved: /kaggle/working/submission_argmax.csv
   ID  label
0   0      0
1   2      0
2   5      1
3   6      0
4   7      0

Saved: /kaggle/working/submission_thresholded.csv
   ID  label
0   0      0
1   2      0
2   5      1
3   6      0
4   7      0

Done. Submit one (or both) of these:
 - /kaggle/working/submission_argmax.csv
 - /kaggle/working/submission_thresholded.csv